export const engDescriptions: Record<string, string> = {
  SmallAnemoSlime: "On Reveal: I apply Anemo to myself.",
  SmallCryoSlime: "On Reveal: I apply Cryo to myself.",
  SmallDendroSlime: "Passive: I take 2 damage whenever Pyro is applied to me.",
  SmallElectroSlime: "On Reveal: I apply Electro to myself.",
  SmallGeoSlime: "On Reveal: I apply Geo to myself.",
  SmallHydroSlime: "On Reveal: I apply Hydro to myself.",
  SmallPyroSlime: "On Reveal: I apply Pyro to myself.",
  GiantAnemoSlime: "On Reveal: All players discard 1 random card.",
  GiantCryoSlime: "On Reveal: All players add 1 Freeze card to their discard.",
  GiantDendroSlime: "Passive: I take 2 damage whenever Pyro is applied to me.",
  GiantElectroSlime: "On Reveal: All players discard 2 energy.",
  GiantGeoSlime: "Created through the buildup of Geo, they can harden the energy within their bodies into a carapace of stone that protects them and prevents damage.",
  GiantHydroSlime: "On Reveal: All players with Freeze cards in their hand lose 1 Action Point this turn.",
  HilichurlGang: "Most people have already given up on trying to communicate with the hilichurls, believing tha they are monsters simply incapable of communication.",
  HilichurlGuard: "According to many reports, hilichurls often charge at travelers making camp to cook and will snatch their pot lids after chasing them away.",
  HilichurlGrenadier: "On Death: All players places 1 Burn card on the top of their deck.",
  HilichurlBerserk: "Passive: If I damage you, you must add 2 Burn cards to your discard.",
  CryoHilichurlShooter: "Passive: I ignore guard. If I damage you, you must add 1 Freeze card to your discard.",
  ElectroHilichurlShooter: "Passive: I ignore guard. If I damage you, you must discard 2 energy.",
  PyroHilichurlShooter: "Passive: I ignore guard. If I damage you, you must add 1 Burn card to your discard.",
  AnemoShamachurl: "On Death: All players must discard 3 energy or take 2 piercing damage.",
  DendroShamachurl: "On Death: All players take 3 damage.",
  GeoShamachurl: "On Death: All players must discard 4 guard or take 2 piercing damage.",
  UnusualHilichurl: "On Death: All players draw 1 card. If it was an upgradeable Action card, upgrade it immediately for free.",
  CryoAbyssMage: "Passive: I ignore guard. If I damage you, you must shuffle 1 Freeze card into your deck.",
  HydroAbyssMage: "Passive: I ignore guard. If I damage you, you must discard 2 random cards",
  PyroAbyssMage: "Passive: I ignore guard. If I damage you, you must shuffle 1 Burn card into your deck.",
  AnemoBoxer: "Passive: If i damage you, you must discard 3 cards.",
  CryoGunner: "Passive: If I damage you, you must add 2 Freeze cards to your discard.",
  ElectroHammer: "A soldier encased within a Fatui war machine. These skirmishers do not question if they will live or die as they advance into nations far from home.",
  GeoChanter: "On Reveal: All enemies everywhere with 0 Shields gain 1 Shield.",
  HydroGunner: "Passive: If i damage you, you must trash the top card of your deck.",
  PyroSlinger: "On Reveal: All players shuffle 1 Burn card into their decks.",
  TreasureHoarderGang: "On Reveal: All players discard 1 mora.",
  VishapHatchling: "Passive: I deal no damage against players with 2 or more Guard.",
  CryoCicinSwarm: `Passive: I take no damage from "Normal Attack" and "Upgraded Normal Attack" cards.`,
  ElectroCicinSwarm: `Passive: I take no damage from "Normal Attack" and "Upgraded Normal Attack" cards.`,
  CryoWhopperflower: "Passive: If I damage you, you must add 2 Freeze cards to your discard.",
  PyroWhopperflower: "Passive: If I damage you, you must add 2 Burn cards to your discard.",
  PyroAgent: "Passive: I take half damage from all instances of damage (rounded down to a minimum of 1).",
  CicinCryoMage: "On Death: All players shuffle 2 Freeze cards into their deck.",
  CicinElectroMage: "On Death: All players must trash an upgraded card or take 3 piercing damage.",
  RuinGuard: "Legend has it that these machines were combat automatons created by a long-destroyed nation. They now wander ruins, attacking offending travelers.",
  RuinHunter: "Relics from a lost ancient nation. Extremely dangerous, one must wonder that the civilization that produced them looked like at its height.",
  RuinGrader: "Passive: I am immune to piercing damage.",
  ShieldBearerMitachurl: "All young hilichurls dream of growing up to become a big and strong Mitachurl, because that way they can eat more meat and fight more battles.",
  BlazingAxeMitachurl: "On Reveal: All players shuffle 2 Burn cards into their deck.",
  FrostarmLawachurl: "Passive: I cannot be applied with Cryo. I regain all of my shields at the start of each player phase.",
  StonehideLawachurl: "Passive: I cannot be applied with Geo. I regain all of my shields at the start of each player phase.",
  EyeOfStorm: "On Death: All players must discard 5 energy or take 3 piercing damage.",
  CryoRegisvine: "Passive: I lose a shield whenever Pyro is applied to me.",
  PyroRegisvine: "Passive: I lose a shield whenever Hydro is applied to me.",
  AnemoHypostasis: "Passive: I cannot be applied with Anemo. I regain all of my health at the start of each player phase.",
  ElectroHypostasis: "Passive: I cannot be applied with Electro. I regain all of my health at the start of each player phase.",
  GeoHypostasis: "Passive: I cannot be applied with Geo. I regain all of my health at the start of each player phase.",
};

export const ruDescriptions: Record<string, string> = {
  SmallAnemoSlime: "При появлении: Накладывает на себя Анемо.",
  SmallCryoSlime: "При появлении: Накладывает на себя Крио.",
  SmallDendroSlime: "Пассивно: Получает 2 урона, когда накладывается Пиро.",
  SmallElectroSlime: "При появлении: Накладывает на себя Электро.",
  SmallGeoSlime: "При появлении: Накладывает на себя Гео.",
  SmallHydroSlime: "При появлении: Накладывает на себя Гидро.",
  SmallPyroSlime: "При появлении: Накладывает на себя Пиро.",
  GiantAnemoSlime: "При появлении: Все игроки сбрасывают 1 случайную карту.",
  GiantCryoSlime: "При появлении: Все игроки добавляют 1 Заморозку в колоду сброса.",
  GiantDendroSlime: "Пассивно: Получает 2 урона, когда накладывается Пиро.",
  GiantElectroSlime: "При появлении: Все игроки теряют 2 энергии.",
  GiantGeoSlime: "Созданные путем накопления Гео, они могут превращать энергию внутри своего тела в каменный панцирь, который защищает их и предотвращает повреждения.",
  GiantHydroSlime: "При появлении: Все игроки с картой заморозки в руке теряют 1 очко действия на этот ход.",
  HilichurlGang: "Большинство людей уже отказались от попыток общения с хиличурлами, считая, что это монстры, неспособные к общению.",
  HilichurlGuard: "Согласно многочисленным сообщениям, хиличурлы часто нападают на путешественников, разбивающих лагерь для приготовления пищи, и, прогнав их, забирают крышки котелков.",
  HilichurlGrenadier: "После смерти: Все игроки добавляют 1 Горение на верх колоды.",
  HilichurlBerserk: "Пассивно: При нанесении урона добавляет 2 Горения в колоду сброса.",
  CryoHilichurlShooter: "Пассивно: Игнорирует защиту. При нанесении урона добавляет 1 Заморозку в колоду сброса.",
  ElectroHilichurlShooter: "Пассивно: Игнорирует защиту. При нанесении урона игрок теряет 2 энергии.",
  PyroHilichurlShooter: "Пассивно: Игнорирует защиту. При нанесении урона добавляет 1 Горение в колоду сброса.",
  AnemoShamachurl: "После смерти: Все игроки теряют 3 энергии или получают 2 пронзающего урона.",
  DendroShamachurl: "После смерти: Все игроки получают 3 урона.",
  GeoShamachurl: "После смерти: Все игроки должны потерять 4 защиты или получить 2 пронзающего урона.",
  UnusualHilichurl: "После смерти: Все игроки вытягивают 1 карту. Если это была карта действия, бесплатно улучшает её.",
  CryoAbyssMage: "Пассивно: Игнорирует защиту. При нанесении урона замешивает 1 Заморозку в колоду.",
  HydroAbyssMage: "Пассивно: Игнорирует защиту. При нанесении урона игрок сбрасывает 2 случайные карты",
  PyroAbyssMage: "Пассивно: Игнорирует защиту. При нанесении урона замешивает 1 Горение в колоду.",
  AnemoBoxer: "Пассивно: При нанесении урона, игрок сбрасывает 3 карты.",
  CryoGunner: "Пассивно: При нанесении урона добавляет 2 Заморозки в колоду сброса.",
  ElectroHammer: "Солдат, заключенный в военную машину Фатуи. Эти бойцы не задаются вопросом, жить им или умереть, когда они продвигаются в страны, находящиеся далеко от дома.",
  GeoChanter: "При появлении: Все враги везде без щитов щитов получают 1 щит.",
  HydroGunner: "Пассивно: При нанесении урона удаляет верхнюю карту в колоде.",
  PyroSlinger: "При появлении: Все игроки замешивают 1 Горение в колоду.",
  TreasureHoarderGang: "При появлении: Все игроки теряют 1 мору.",
  VishapHatchling: "Пассивно: Не наносит урон игроку, если у него 2+ защиты.",
  CryoCicinSwarm: `Пассивно: Не получает урон от "Обычной атаки" и "Улучшенной обычной атаки".`,
  ElectroCicinSwarm: `Пассивно: Не получает урон от "Обычной атаки" и "Улучшенной обычной атаки".`,
  CryoWhopperflower: "Пассивно: При нанесении урона добавляет 2 Заморозки в колоду сброса.",
  PyroWhopperflower: "Пассивно: При нанесении урона добавляет 2 Горения в колоду сброса.",
  PyroAgent: "Пассивно: Получает только половину урона (округляется вниз, но не меньше 1).",
  CicinCryoMage: "После смерти: Все игроки замешивают 2 Заморозки в их колоду.",
  CicinElectroMage: "После смерти: Все игроки должны избавиться от улучшенной карты или получают 3 пронзающего урона.",
  RuinGuard: "Легенда гласит, что эти машины были боевыми роботами, созданными давно уничтоженной нацией. Теперь они бродят по руинам, нападая на путешественников.",
  RuinHunter: "Реликвии исчезнувшей древней нации. Чрезвычайно опасные, стоит задуматься, как выглядела цивилизация, создавшая их, в период своего расцвета.",
  RuinGrader: "Пассивно: Не получает пронзающий урон.",
  ShieldBearerMitachurl: "Все молодые хиличурлы мечтают вырасти и стать большим и сильным Митачурлами, потому что так они смогут есть больше мяса и сражаться в большем количестве битв.",
  BlazingAxeMitachurl: "При появлении: Все игроки замешивают 2 Горения в их колоду.",
  FrostarmLawachurl: "Пассивно: Нельзя наложить Крио. Восстанавливает все щиты в начале каждого хода.",
  StonehideLawachurl: "Пассивно: Нельзя наложить Гео. Восстанавливает все щиты в начале каждого хода.",
  EyeOfStorm: "После смерти: Все игроки теряют 5 энергии или получают 3 пронзающего урона.",
  CryoRegisvine: "Пассивно: Теряет щит, когда накладывается Пиро.",
  PyroRegisvine: "Пассивно: Теряет щит, когда накладывается Гидро.",
  AnemoHypostasis: "Пассивно: Нельзя наложить Анемо. Восстанавливает всё здоровье в начале каждого хода.",
  ElectroHypostasis: "Пассивно: Нельзя наложить Электро. Восстанавливает всё здоровье в начале каждого хода.",
  GeoHypostasis: "Пассивно: Нельзя наложить Гео. Восстанавливает всё здоровье в начале каждого хода.",
};
