import { EEnemy } from "../../types/enums";

export const engDescriptions: Record<EEnemy, string> = {
  [EEnemy.SmallAnemoSlime]: "On Reveal: I apply Anemo to myself.",
  [EEnemy.SmallCryoSlime]: "On Reveal: I apply Cryo to myself.",
  [EEnemy.SmallDendroSlime]: "Passive: I take 2 damage whenever Pyro is applied to me.",
  [EEnemy.SmallElectroSlime]: "On Reveal: I apply Electro to myself.",
  [EEnemy.SmallGeoSlime]: "On Reveal: I apply Geo to myself.",
  [EEnemy.SmallHydroSlime]: "On Reveal: I apply Hydro to myself.",
  [EEnemy.SmallPyroSlime]: "On Reveal: I apply Pyro to myself.",
  [EEnemy.GiantAnemoSlime]: "On Reveal: All players discard 1 random card.",
  [EEnemy.GiantCryoSlime]: "On Reveal: All players add 1 Freeze card to their discard.",
  [EEnemy.GiantDendroSlime]: "Passive: I take 2 damage whenever Pyro is applied to me.",
  [EEnemy.GiantElectroSlime]: "On Reveal: All players discard 2 energy.",
  [EEnemy.GiantGeoSlime]: "Created through the buildup of Geo, they can harden the energy within their bodies into a carapace of stone that protects them and prevents damage.",
  [EEnemy.GiantHydroSlime]: "On Reveal: All players with Freeze cards in their hand lose 1 Action Point this turn.",
  [EEnemy.GiantPyroSlime]: "On Reveal: All players add 1 Burn card to their discard.",
  [EEnemy.HilichurlGang]: "Most people have already given up on trying to communicate with the hilichurls, believing tha they are monsters simply incapable of communication.",
  [EEnemy.HilichurlGuard]: "According to many reports, hilichurls often charge at travelers making camp to cook and will snatch their pot lids after chasing them away.",
  [EEnemy.HilichurlGrenadier]: "On Death: All players places 1 Burn card on the top of their deck.",
  [EEnemy.HilichurlBerserk]: "Passive: If I damage you, you must add 2 Burn cards to your discard.",
  [EEnemy.CryoHilichurlShooter]: "Passive: I ignore guard. If I damage you, you must add 1 Freeze card to your discard.",
  [EEnemy.ElectroHilichurlShooter]: "Passive: I ignore guard. If I damage you, you must discard 2 energy.",
  [EEnemy.PyroHilichurlShooter]: "Passive: I ignore guard. If I damage you, you must add 1 Burn card to your discard.",
  [EEnemy.AnemoShamachurl]: "On Death: All players must discard 3 energy or take 2 piercing damage.",
  [EEnemy.DendroShamachurl]: "On Death: All players take 3 damage.",
  [EEnemy.GeoShamachurl]: "On Death: All players must discard 4 guard or take 2 piercing damage.",
  [EEnemy.UnusualHilichurl]: "On Death: All players draw 1 card. If it was an upgradeable Action card, upgrade it immediately for free.",
  [EEnemy.CryoAbyssMage]: "Passive: I ignore guard. If I damage you, you must shuffle 1 Freeze card into your deck.",
  [EEnemy.HydroAbyssMage]: "Passive: I ignore guard. If I damage you, you must discard 2 random cards",
  [EEnemy.PyroAbyssMage]: "Passive: I ignore guard. If I damage you, you must shuffle 1 Burn card into your deck.",
  [EEnemy.AnemoBoxer]: "Passive: If i damage you, you must discard 3 cards.",
  [EEnemy.CryoGunner]: "Passive: If I damage you, you must add 2 Freeze cards to your discard.",
  [EEnemy.ElectroHammer]: "A soldier encased within a Fatui war machine. These skirmishers do not question if they will live or die as they advance into nations far from home.",
  [EEnemy.GeoChanter]: "On Reveal: All enemies everywhere with 0 Shields gain 1 Shield.",
  [EEnemy.HydroGunner]: "Passive: If i damage you, you must trash the top card of your deck.",
  [EEnemy.PyroSlinger]: "On Reveal: All players shuffle 1 Burn card into their decks.",
  [EEnemy.TreasureHoarderGang]: "On Reveal: All players discard 1 mora.",
  [EEnemy.VishapHatchling]: "Passive: I deal no damage against players with 2 or more Guard.",
  [EEnemy.CryoCicinSwarm]: `Passive: I take no damage from "Normal Attack" and "Upgraded Normal Attack" cards.`,
  [EEnemy.ElectroCicinSwarm]: `Passive: I take no damage from "Normal Attack" and "Upgraded Normal Attack" cards.`,
  [EEnemy.CryoWhopperflower]: "Passive: If I damage you, you must add 2 Freeze cards to your discard.",
  [EEnemy.PyroWhopperflower]: "Passive: If I damage you, you must add 2 Burn cards to your discard.",
  [EEnemy.PyroAgent]: "Passive: I take half damage from all instances of damage (rounded down to a minimum of 1).",
  [EEnemy.CicinCryoMage]: "On Death: All players shuffle 2 Freeze cards into their deck.",
  [EEnemy.CicinElectroMage]: "On Death: All players must trash an upgraded card or take 3 piercing damage.",
  [EEnemy.RuinGuard]: "Legend has it that these machines were combat automatons created by a long-destroyed nation. They now wander ruins, attacking offending travelers.",
  [EEnemy.RuinHunter]: "Relics from a lost ancient nation. Extremely dangerous, one must wonder that the civilization that produced them looked like at its height.",
  [EEnemy.RuinGrader]: "Passive: I am immune to piercing damage.",
  [EEnemy.ShieldBearerMitachurl]: "All young hilichurls dream of growing up to become a big and strong Mitachurl, because that way they can eat more meat and fight more battles.",
  [EEnemy.BlazingAxeMitachurl]: "On Reveal: All players shuffle 2 Burn cards into their deck.",
  [EEnemy.FrostarmLawachurl]: "Passive: I cannot be applied with Cryo. I regain all of my shields at the start of each player phase.",
  [EEnemy.StonehideLawachurl]: "Passive: I cannot be applied with Geo. I regain all of my shields at the start of each player phase.",
  [EEnemy.EyeOfStorm]: "On Death: All players must discard 5 energy or take 3 piercing damage.",
  [EEnemy.CryoRegisvine]: "Passive: I lose a shield whenever Pyro is applied to me.",
  [EEnemy.PyroRegisvine]: "Passive: I lose a shield whenever Hydro is applied to me.",
  [EEnemy.AnemoHypostasis]: "Passive: I cannot be applied with Anemo. I regain all of my health at the start of each player phase.",
  [EEnemy.ElectroHypostasis]: "Passive: I cannot be applied with Electro. I regain all of my health at the start of each player phase.",
  [EEnemy.GeoHypostasis]: "Passive: I cannot be applied with Geo. I regain all of my health at the start of each player phase.",
};

export const rusDescriptions: Record<EEnemy, string> = {
  [EEnemy.SmallAnemoSlime]: "При появлении: Накладывает на себя Анемо.",
  [EEnemy.SmallCryoSlime]: "При появлении: Накладывает на себя Крио.",
  [EEnemy.SmallDendroSlime]: "Пассивно: Получает 2 урона, когда накладывается Пиро.",
  [EEnemy.SmallElectroSlime]: "При появлении: Накладывает на себя Электро.",
  [EEnemy.SmallGeoSlime]: "При появлении: Накладывает на себя Гео.",
  [EEnemy.SmallHydroSlime]: "При появлении: Накладывает на себя Гидро.",
  [EEnemy.SmallPyroSlime]: "При появлении: Накладывает на себя Пиро.",
  [EEnemy.GiantAnemoSlime]: "При появлении: Все игроки сбрасывают 1 случайную карту.",
  [EEnemy.GiantCryoSlime]: "При появлении: Все игроки добавляют 1 Заморозку в колоду сброса.",
  [EEnemy.GiantDendroSlime]: "Пассивно: Получает 2 урона, когда накладывается Пиро.",
  [EEnemy.GiantElectroSlime]: "При появлении: Все игроки теряют 2 энергии.",
  [EEnemy.GiantGeoSlime]: "Созданные путем накопления Гео, они могут превращать энергию внутри своего тела в каменный панцирь, который защищает их и предотвращает повреждения.",
  [EEnemy.GiantHydroSlime]: "При появлении: Все игроки с картой заморозки в руке теряют 1 очко действия на этот ход.",
  [EEnemy.GiantPyroSlime]: "При появлении: Все игроки добавляют 1 Горение в колоду сброса.",
  [EEnemy.HilichurlGang]: "Большинство людей уже отказались от попыток общения с хиличурлами, считая, что это монстры, неспособные к общению.",
  [EEnemy.HilichurlGuard]: "Согласно многочисленным сообщениям, хиличурлы часто нападают на путешественников, разбивающих лагерь для приготовления пищи, и, прогнав их, забирают крышки котелков.",
  [EEnemy.HilichurlGrenadier]: "После смерти: Все игроки добавляют 1 Горение на верх колоды.",
  [EEnemy.HilichurlBerserk]: "Пассивно: При нанесении урона добавляет 2 Горения в колоду сброса.",
  [EEnemy.CryoHilichurlShooter]: "Пассивно: Игнорирует защиту. При нанесении урона добавляет 1 Заморозку в колоду сброса.",
  [EEnemy.ElectroHilichurlShooter]: "Пассивно: Игнорирует защиту. При нанесении урона игрок теряет 2 энергии.",
  [EEnemy.PyroHilichurlShooter]: "Пассивно: Игнорирует защиту. При нанесении урона добавляет 1 Горение в колоду сброса.",
  [EEnemy.AnemoShamachurl]: "После смерти: Все игроки теряют 3 энергии или получают 2 пронзающего урона.",
  [EEnemy.DendroShamachurl]: "После смерти: Все игроки получают 3 урона.",
  [EEnemy.GeoShamachurl]: "После смерти: Все игроки должны потерять 4 защиты или получить 2 пронзающего урона.",
  [EEnemy.UnusualHilichurl]: "После смерти: Все игроки вытягивают 1 карту. Если это была карта действия, бесплатно улучшает её.",
  [EEnemy.CryoAbyssMage]: "Пассивно: Игнорирует защиту. При нанесении урона замешивает 1 Заморозку в колоду.",
  [EEnemy.HydroAbyssMage]: "Пассивно: Игнорирует защиту. При нанесении урона игрок сбрасывает 2 случайные карты",
  [EEnemy.PyroAbyssMage]: "Пассивно: Игнорирует защиту. При нанесении урона замешивает 1 Горение в колоду.",
  [EEnemy.AnemoBoxer]: "Пассивно: При нанесении урона, игрок сбрасывает 3 карты.",
  [EEnemy.CryoGunner]: "Пассивно: При нанесении урона добавляет 2 Заморозки в колоду сброса.",
  [EEnemy.ElectroHammer]: "Солдат, заключенный в военную машину Фатуи. Эти бойцы не задаются вопросом, жить им или умереть, когда они продвигаются в страны, находящиеся далеко от дома.",
  [EEnemy.GeoChanter]: "При появлении: Все враги везде без щитов щитов получают 1 щит.",
  [EEnemy.HydroGunner]: "Пассивно: При нанесении урона удаляет верхнюю карту в колоде.",
  [EEnemy.PyroSlinger]: "При появлении: Все игроки замешивают 1 Горение в колоду.",
  [EEnemy.TreasureHoarderGang]: "При появлении: Все игроки теряют 1 мору.",
  [EEnemy.VishapHatchling]: "Пассивно: Не наносит урон игроку, если у него 2+ защиты.",
  [EEnemy.CryoCicinSwarm]: `Пассивно: Не получает урон от "Обычной атаки" и "Улучшенной обычной атаки".`,
  [EEnemy.ElectroCicinSwarm]: `Пассивно: Не получает урон от "Обычной атаки" и "Улучшенной обычной атаки".`,
  [EEnemy.CryoWhopperflower]: "Пассивно: При нанесении урона добавляет 2 Заморозки в колоду сброса.",
  [EEnemy.PyroWhopperflower]: "Пассивно: При нанесении урона добавляет 2 Горения в колоду сброса.",
  [EEnemy.PyroAgent]: "Пассивно: Получает только половину урона (округляется вниз, но не меньше 1).",
  [EEnemy.CicinCryoMage]: "После смерти: Все игроки замешивают 2 Заморозки в их колоду.",
  [EEnemy.CicinElectroMage]: "После смерти: Все игроки должны избавиться от улучшенной карты или получают 3 пронзающего урона.",
  [EEnemy.RuinGuard]: "Легенда гласит, что эти машины были боевыми роботами, созданными давно уничтоженной нацией. Теперь они бродят по руинам, нападая на путешественников.",
  [EEnemy.RuinHunter]: "Реликвии исчезнувшей древней нации. Чрезвычайно опасные, стоит задуматься, как выглядела цивилизация, создавшая их, в период своего расцвета.",
  [EEnemy.RuinGrader]: "Пассивно: Не получает пронзающий урон.",
  [EEnemy.ShieldBearerMitachurl]: "Все молодые хиличурлы мечтают вырасти и стать большим и сильным Митачурлами, потому что так они смогут есть больше мяса и сражаться в большем количестве битв.",
  [EEnemy.BlazingAxeMitachurl]: "При появлении: Все игроки замешивают 2 Горения в их колоду.",
  [EEnemy.FrostarmLawachurl]: "Пассивно: Нельзя наложить Крио. Восстанавливает все щиты в начале каждого хода.",
  [EEnemy.StonehideLawachurl]: "Пассивно: Нельзя наложить Гео. Восстанавливает все щиты в начале каждого хода.",
  [EEnemy.EyeOfStorm]: "После смерти: Все игроки теряют 5 энергии или получают 3 пронзающего урона.",
  [EEnemy.CryoRegisvine]: "Пассивно: Теряет щит, когда накладывается Пиро.",
  [EEnemy.PyroRegisvine]: "Пассивно: Теряет щит, когда накладывается Гидро.",
  [EEnemy.AnemoHypostasis]: "Пассивно: Нельзя наложить Анемо. Восстанавливает всё здоровье в начале каждого хода.",
  [EEnemy.ElectroHypostasis]: "Пассивно: Нельзя наложить Электро. Восстанавливает всё здоровье в начале каждого хода.",
  [EEnemy.GeoHypostasis]: "Пассивно: Нельзя наложить Гео. Восстанавливает всё здоровье в начале каждого хода.",
};
