import { EEnemy } from "../../types/enums";

export const engNames: Record<EEnemy, string> = {
  [EEnemy.SmallAnemoSlime]: "Small Anemo Slime",
  [EEnemy.SmallCryoSlime]: "Small Cryo Slime",
  [EEnemy.SmallDendroSlime]: "Small Dendro Slime",
  [EEnemy.SmallElectroSlime]: "Small Electro Slime",
  [EEnemy.SmallGeoSlime]: "Small Geo Slime",
  [EEnemy.SmallHydroSlime]: "Small Hydro Slime",
  [EEnemy.SmallPyroSlime]: "Small Pyro Slime",
  [EEnemy.GiantAnemoSlime]: "Giant Anemo Slime",
  [EEnemy.GiantCryoSlime]: "Giant Cryo Slime",
  [EEnemy.GiantDendroSlime]: "Giant Dendro Slime",
  [EEnemy.GiantElectroSlime]: "Giant Electro Slime",
  [EEnemy.GiantGeoSlime]: "Giant Geo Slime",
  [EEnemy.GiantHydroSlime]: "Giant Hydro Slime",
  [EEnemy.GiantPyroSlime]: "Giant Pyro Slime",
  [EEnemy.HilichurlGang]: "Hilichurl Gang",
  [EEnemy.HilichurlGuard]: "Hilichurl Guard",
  [EEnemy.HilichurlGrenadier]: "Hilichurl Grenadier",
  [EEnemy.HilichurlBerserk]: "Hilichurl Berserk",
  [EEnemy.CryoHilichurlShooter]: "Cryo Hilichurl Shooter",
  [EEnemy.ElectroHilichurlShooter]: "Electro Hilichurl Shooter",
  [EEnemy.PyroHilichurlShooter]: "Pyro Hilichurl Shooter",
  [EEnemy.AnemoShamachurl]: "Anemo Shamachurl",
  [EEnemy.DendroShamachurl]: "Dendro Shamachurl",
  [EEnemy.GeoShamachurl]: "Geo Shamachurl",
  [EEnemy.UnusualHilichurl]: "Unusual Hilichurl",
  [EEnemy.CryoAbyssMage]: "Cryo Abyss Mage",
  [EEnemy.HydroAbyssMage]: "Hydro Abyss Mage",
  [EEnemy.PyroAbyssMage]: "Pyro Abyss Mage",
  [EEnemy.AnemoBoxer]: "Anemo Boxer",
  [EEnemy.CryoGunner]: "Cryo Gunner",
  [EEnemy.ElectroHammer]: "Electro Hammer",
  [EEnemy.GeoChanter]: "Geo Chanter",
  [EEnemy.HydroGunner]: "Hydro Gunner",
  [EEnemy.PyroSlinger]: "Pyro Slinger",
  [EEnemy.TreasureHoarderGang]: "Treasure Hoarder Gang",
  [EEnemy.VishapHatchling]: "Vishap Hatchling",
  [EEnemy.CryoCicinSwarm]: "Cryo Cicin Swarm",
  [EEnemy.ElectroCicinSwarm]: "Electro Cicin Swarm",
  [EEnemy.CryoWhopperflower]: "Cryo Whopperflower",
  [EEnemy.PyroWhopperflower]: "Pyro Whopperflower",
  [EEnemy.PyroAgent]: "Pyro Agent",
  [EEnemy.CicinCryoMage]: "Cicin Cryo Mage",
  [EEnemy.CicinElectroMage]: "Cicin Electro Mage",
  [EEnemy.RuinGuard]: "Ruin Guard",
  [EEnemy.RuinHunter]: "Ruin Hunter",
  [EEnemy.RuinGrader]: "Ruin Grader",
  [EEnemy.ShieldBearerMitachurl]: "Shield Bearer Mitachurl",
  [EEnemy.BlazingAxeMitachurl]: "Blazing Axe Mitachurl",
  [EEnemy.FrostarmLawachurl]: "Frostarm Lawachurl",
  [EEnemy.StonehideLawachurl]: "Stonehide Lawachurl",
  [EEnemy.EyeOfStorm]: "Eye Of Storm",
  [EEnemy.CryoRegisvine]: "Cryo Regisvine",
  [EEnemy.PyroRegisvine]: "Pyro Regisvine",
  [EEnemy.AnemoHypostasis]: "Anemo Hypostasis",
  [EEnemy.ElectroHypostasis]: "Electro Hypostasis",
  [EEnemy.GeoHypostasis]: "Geo Hypostasis",
};

export const rusNames: Record<EEnemy, string> = {
  [EEnemy.SmallAnemoSlime]: "Анемо слайм",
  [EEnemy.SmallCryoSlime]: "Крио слайм",
  [EEnemy.SmallDendroSlime]: "Дендро слайм",
  [EEnemy.SmallElectroSlime]: "Электро слайм",
  [EEnemy.SmallGeoSlime]: "Гео слайм",
  [EEnemy.SmallHydroSlime]: "Гидро слайм",
  [EEnemy.SmallPyroSlime]: "Пиро слайм",
  [EEnemy.GiantAnemoSlime]: "Большой Анемо слайм",
  [EEnemy.GiantCryoSlime]: "Большой Крио слайм",
  [EEnemy.GiantDendroSlime]: "Большой Дендро слайм",
  [EEnemy.GiantElectroSlime]: "Большой электро слайм",
  [EEnemy.GiantGeoSlime]: "Большой Гео слайм",
  [EEnemy.GiantHydroSlime]: "Большой Гидро слайм",
  [EEnemy.GiantPyroSlime]: "Большой Пиро слайм",
  [EEnemy.HilichurlGang]: "Банда хиличурлов",
  [EEnemy.HilichurlGuard]: "Хиличурл со щитом",
  [EEnemy.HilichurlGrenadier]: "Хиличурл-гренадёр",
  [EEnemy.HilichurlBerserk]: "Хиличурл-берсерк",
  [EEnemy.CryoHilichurlShooter]: "Крио хиличурл-стрелок",
  [EEnemy.ElectroHilichurlShooter]: "Электро хиличурл-стрелок",
  [EEnemy.PyroHilichurlShooter]: "Пиро хиличурл-стрелок",
  [EEnemy.AnemoShamachurl]: "Анемо шамачурл",
  [EEnemy.DendroShamachurl]: "Дендро шамачурл",
  [EEnemy.GeoShamachurl]: "Гео шамачурл",
  [EEnemy.UnusualHilichurl]: "Странный хиличурл",
  [EEnemy.CryoAbyssMage]: "Крио маг Бездны",
  [EEnemy.HydroAbyssMage]: "Гидро маг Бездны",
  [EEnemy.PyroAbyssMage]: "Пиро маг Бездны",
  [EEnemy.AnemoBoxer]: "Анемо борец",
  [EEnemy.CryoGunner]: "Крио бомбардир",
  [EEnemy.ElectroHammer]: "Электро молотобоец",
  [EEnemy.GeoChanter]: "Гео заклинатель",
  [EEnemy.HydroGunner]: "Гидро бомбардир",
  [EEnemy.PyroSlinger]: "Пиро мушкетёр",
  [EEnemy.TreasureHoarderGang]: "Банда похитителей сокровищ",
  [EEnemy.VishapHatchling]: "Детёныш геовишапа",
  [EEnemy.CryoCicinSwarm]: "Крио цицин",
  [EEnemy.ElectroCicinSwarm]: "Электро цицин",
  [EEnemy.CryoWhopperflower]: "Крио попрыгунья",
  [EEnemy.PyroWhopperflower]: "Пиро попрыгунья",
  [EEnemy.PyroAgent]: "Пиро агент",
  [EEnemy.CicinCryoMage]: "Маг Крио цицинов",
  [EEnemy.CicinElectroMage]: "Маг Электро цицинов",
  [EEnemy.RuinGuard]: "Страх руин",
  [EEnemy.RuinHunter]: "Руинный охотник",
  [EEnemy.RuinGrader]: "Руинный молотильщик",
  [EEnemy.ShieldBearerMitachurl]: "Митачурл со щитом",
  [EEnemy.BlazingAxeMitachurl]: "Митачурл с огненным топором",
  [EEnemy.FrostarmLawachurl]: "Лавачурл с инеевым панцирем",
  [EEnemy.StonehideLawachurl]: "Лавачурл с каменным панцирем",
  [EEnemy.EyeOfStorm]: "Глаз бури",
  [EEnemy.CryoRegisvine]: "Крио папоротник",
  [EEnemy.PyroRegisvine]: "Пиро папоротник",
  [EEnemy.AnemoHypostasis]: "Анемо гипостазис",
  [EEnemy.ElectroHypostasis]: "Электро гипостазис",
  [EEnemy.GeoHypostasis]: "Гео гипостазис",
};
