export const engNames: Record<string, string> = {
  SmallAnemoSlime: "Small Anemo Slime",
  SmallCryoSlime: "Small Cryo Slime",
  SmallDendroSlime: "Small Dendro Slime",
  SmallElectroSlime: "Small Electro Slime",
  SmallGeoSlime: "Small Geo Slime",
  SmallHydroSlime: "Small Hydro Slime",
  SmallPyroSlime: "Small Pyro Slime",
  GiantAnemoSlime: "Giant Anemo Slime",
  GiantCryoSlime: "Giant Cryo Slime",
  GiantDendroSlime: "Giant Dendro Slime",
  GiantElectroSlime: "Giant Electro Slime",
  GiantGeoSlime: "Giant Geo Slime",
  GiantHydroSlime: "Giant Hydro Slime",
  GiantPyroSlime: "Giant Pyro Slime",
  HilichurlGang: "Hilichurl Gang",
  HilichurlGuard: "Hilichurl Guard",
  HilichurlGrenadier: "Hilichurl Grenadier",
  HilichurlBerserk: "Hilichurl Berserk",
  CryoHilichurlShooter: "Cryo Hilichurl Shooter",
  ElectroHilichurlShooter: "Electro Hilichurl Shooter",
  PyroHilichurlShooter: "Pyro Hilichurl Shooter",
  AnemoShamachurl: "Anemo Shamachurl",
  DendroShamachurl: "Dendro Shamachurl",
  GeoShamachurl: "Geo Shamachurl",
  UnusualHilichurl: "Unusual Hilichurl",
  CryoAbyssMage: "Cryo Abyss Mage",
  HydroAbyssMage: "Hydro Abyss Mage",
  PyroAbyssMage: "Pyro Abyss Mage",
  AnemoBoxer: "Anemo Boxer",
  CryoGunner: "Cryo Gunner",
  ElectroHammer: "Electro Hammer",
  GeoChanter: "Geo Chanter",
  HydroGunner: "Hydro Gunner",
  PyroSlinger: "Pyro Slinger",
  TreasureHoarderGang: "Treasure Hoarder Gang",
  VishapHatchling: "Vishap Hatchling",
  CryoCicinSwarm: "Cryo Cicin Swarm",
  ElectroCicinSwarm: "Electro Cicin Swarm",
  CryoWhopperflower: "Cryo Whopperflower",
  PyroWhopperflower: "Pyro Whopperflower",
  PyroAgent: "Pyro Agent",
  CicinCryoMage: "Cicin Cryo Mage",
  CicinElectroMage: "Cicin Electro Mage",
  RuinGuard: "Ruin Guard",
  RuinHunter: "Ruin Hunter",
  RuinGrader: "Ruin Grader",
  ShieldBearerMitachurl: "Shield Bearer Mitachurl",
  BlazingAxeMitachurl: "Blazing Axe Mitachurl",
  FrostarmLawachurl: "Frostarm Lawachurl",
  EyeOfStorm: "Eye Of Storm",
  CryoRegisvine: "Cryo Regisvine",
  PyroRegisvine: "Pyro Regisvine",
  AnemoHypostasis: "Anemo Hypostasis",
  ElectroHypostasis: "Electro Hypostasis",
  GeoHypostasis: "Geo Hypostasis",
};

export const rusNames: Record<string, string> = {
  SmallAnemoSlime: "Анемо слайм",
  SmallCryoSlime: "Крио слайм",
  SmallDendroSlime: "Дендро слайм",
  SmallElectroSlime: "Электро слайм",
  SmallGeoSlime: "Гео слайм",
  SmallHydroSlime: "Гидро слайм",
  SmallPyroSlime: "Пиро слайм",
  GiantAnemoSlime: "Большой Анемо слайм",
  GiantCryoSlime: "Большой Крио слайм",
  GiantDendroSlime: "Большой Дендро слайм",
  GiantElectroSlime: "Большой электро слайм",
  GiantGeoSlime: "Большой Гео слайм",
  GiantHydroSlime: "Большой Гидро слайм",
  GiantPyroSlime: "Большой Пиро слайм",
  HilichurlGang: "Банда хиличурлов",
  HilichurlGuard: "Хиличурл со щитом",
  HilichurlGrenadier: "Хиличурл-гренадёр",
  HilichurlBerserk: "Хиличурл-берсерк",
  CryoHilichurlShooter: "Крио хиличурл-стрелок",
  ElectroHilichurlShooter: "Электро хиличурл-стрелок",
  PyroHilichurlShooter: "Пиро хиличурл-стрелок",
  AnemoShamachurl: "Анемо шамачурл",
  DendroShamachurl: "Дендро шамачурл",
  GeoShamachurl: "Гео шамачурл",
  UnusualHilichurl: "Странный хиличурл",
  CryoAbyssMage: "Крио маг Бездны",
  HydroAbyssMage: "Гидро маг Бездны",
  PyroAbyssMage: "Пиро маг Бездны",
  AnemoBoxer: "Анемо борец",
  CryoGunner: "Крио бомбардир",
  ElectroHammer: "Электро молотобоец",
  GeoChanter: "Гео заклинатель",
  HydroGunner: "Гидро бомбардир",
  PyroSlinger: "Пиро мушкетёр",
  TreasureHoarderGang: "Банда похитителей сокровищ",
  VishapHatchling: "Детёныш геовишапа",
  CryoCicinSwarm: "Крио цицин",
  ElectroCicinSwarm: "Электро цицин",
  CryoWhopperflower: "Крио попрыгунья",
  PyroWhopperflower: "Пиро попрыгунья",
  PyroAgent: "Пиро агент",
  CicinCryoMage: "Маг Крио цицинов",
  CicinElectroMage: "Маг Электро цицинов",
  RuinGuard: "Страх руин",
  RuinHunter: "Руинный охотник",
  RuinGrader: "Руинный молотильщик",
  ShieldBearerMitachurl: "Митачурл со щитом",
  BlazingAxeMitachurl: "Митачурл с огненным топором",
  FrostarmLawachurl: "Лавачурл с инеевым панцирем",
  EyeOfStorm: "Глаз бури",
  CryoRegisvine: "Крио папоротник",
  PyroRegisvine: "Пиро папоротник",
  AnemoHypostasis: "Анемо гипостазис",
  ElectroHypostasis: "Электро гипостазис",
  GeoHypostasis: "Гео гипостазис",
};
