import { ECharacter } from "../../types/enums";

export const burstCosts: Record<ECharacter, number> = {
  [ECharacter.Aether]: 4,
  [ECharacter.Albedo]: 6,
  [ECharacter.Amber]: 5,
  [ECharacter.Barbara]: 5,
  [ECharacter.Beidou]: 4,
  [ECharacter.Bennett]: 7,
  [ECharacter.ChongYun]: 3,
  [ECharacter.Diluc]: 7,
  [ECharacter.Diona]: 5,
  [ECharacter.Eula]: 4,
  [ECharacter.Fischl]: 5,
  [ECharacter.Ganyu]: 7,
  [ECharacter.HuTao]: 6,
  [ECharacter.Jean]: 5,
  [ECharacter.Kaeya]: 3,
  [ECharacter.Kazuha]: 6,
  [ECharacter.KeQing]: 8,
  [ECharacter.Klee]: 4,
  [ECharacter.Lisa]: 3,
  [ECharacter.Lumine]: 3,
  [ECharacter.Mona]: 3,
  [ECharacter.NingGuang]: 7,
  [ECharacter.Noelle]: 3,
  [ECharacter.QiQi]: 5,
  [ECharacter.Raiden]: 10,
  [ECharacter.Razor]: 5,
  [ECharacter.Rosaria]: 8,
  [ECharacter.Sucrose]: 4,
  [ECharacter.Tartaglia]: 8,
  [ECharacter.Venti]: 10,
  [ECharacter.XiangLing]: 4,
  [ECharacter.Xiao]: 2,
  [ECharacter.XingQiu]: 4,
  [ECharacter.Xinyan]: 6,
  [ECharacter.Yanfei]: 3,
  [ECharacter.Yoimiya]: 4,
  [ECharacter.ZhongLi]: 10,
};
