export const characterSkillCards: Record<
  string,
  { card1: string; card2: string }
> = {
  Aether: { card1: "ForeignRockblade", card2: "StarfellSword" },
  Albedo: { card1: "WeissBladework", card2: "SolarIsotoma" },
  Amber: { card1: "Sharpshooter", card2: "ExplosivePuppet" },
  Barbara: { card1: "WhisperOfWater", card2: "LetTheShowBegin" },
  Beidou: { card1: "Oceanborn", card2: "Tidecaller" },
  Bennett: { card1: "StrikeOfFortune", card2: "PassionOverload" },
  ChongYun: { card1: "Demonbane", card2: "LayeredFrost" },
  Diluc: { card1: "TemperedSword", card2: "SearingOnslaught" },
  Diona: { card1: "KatzleinStyle", card2: "IcyPaws" },
  Eula: { card1: "EdelBladework", card2: "IcetideVortex" },
  Fischl: { card1: "BoltsOfDownfall", card2: "Nightrider" },
  Ganyu: { card1: "LiutianArchery", card2: "TrailOfTheQilin" },
  HuTao: { card1: "SpearOfWangsheng", card2: "GuideOfAfterlife" },
  Jean: { card1: "FavoniusBladework", card2: "GaleBlade" },
  Kaeya: { card1: "CeremonialBladework", card2: "Frostgnaw" },
  Kazuha: { card1: "GaryuuBladework", card2: "Chihayaburu" },
  KeQing: { card1: "YunlaiSwordsmanship", card2: "StellarRestoration" },
  Klee: { card1: "Kaboom", card2: "JumpyDumpty" },
  Lisa: { card1: "LightningTouch", card2: "VioletArc" },
  Lumine: { card1: "ForeignIronwind", card2: "PalmVortex" },
  Mona: { card1: "RippleOfFate", card2: "MirrorReflections" },
  NingGuang: { card1: "SparklingScatter", card2: "JadeScreen" },
  Noelle: { card1: "MaidsBladework", card2: "Breastplate" },
  QiQi: { card1: "AncientSwordArt", card2: "HeraldOfFrost" },
  Raiden: { card1: "Origin", card2: "BalefulOmen" },
  Razor: { card1: "SteelFang", card2: "ClawAndThunder" },
  Rosaria: { card1: "SpearOfTheChurch", card2: "RavagingConfession" },
  Sucrose: { card1: "WindSpiritCreation", card2: "AnemoHypostatis" },
  Tartaglia: { card1: "CuttingTorrent", card2: "RagingTide" },
  Venti: { card1: "DivineArchery", card2: "SkywardSonnet" },
  XiangLing: { card1: "DoughFu", card2: "GuobaFire" },
  Xiao: { card1: "WhirlwindThrust", card2: "LemniscaticWind" },
  XingQiu: { card1: "GuhuaStyle", card2: "FatalRainscreen" },
  Xinyan: { card1: "DanceOfFire", card2: "SweepingFervor" },
  Yanfei: { card1: "SealOfApproval", card2: "SignedEdict" },
  Yoimiya: { card1: "FireworkFlareUp", card2: "NiwabiFireDance" },
  ZhongLi: { card1: "RainOfStone", card2: "DominusLapidis" },
};
