export const engNames: Record<string, string> = {
  Aether: "Aether",
  Albedo: "Albedo",
  Amber: "Amber",
  Barbara: "Barbara",
  Beidou: "Beidou",
  Bennett: "Bennett",
  ChongYun: "Chong Yun",
  Diluc: "Diluc",
  Diona: "Diona",
  Eula: "Eula",
  Fischl: "Fischl",
  Ganyu: "Ganyu",
  HuTao: "Hu Tao",
  Jean: "Jean",
  Kaeya: "Kaeya",
  Kazuha: "Kazuha",
  KeQing: "Ke Qing",
  Klee: "Klee",
  Lisa: "Lisa",
  Lumine: "Lumine",
  Mona: "Mona",
  NingGuang: "Ning Guang",
  Noelle: "Noelle",
  QiQi: "Qi Qi",
  Raiden: "Raiden",
  Razor: "Razor",
  Rosaria: "Rosaria",
  Sucrose: "Sucrose",
  Tartaglia: "Tartaglia",
  Venti: "Venti",
  XiangLing: "Xiang Ling",
  Xiao: "Xiao",
  XingQiu: "Xing Qiu",
  Xinyan: "Xinyan",
  Yanfei: "Yanfei",
  Yoimiya: "Yoimiya",
  ZhongLi: "Zhong Li",
};

export const rusNames: Record<string, string> = {
    Aether: "Итэр",
    Albedo: "Альбедо",
    Amber: "Эмбер",
    Barbara: "Барбара",
    Beidou: "Бэй Доу",
    Bennett: "Беннет",
    ChongYun: "Чун Юнь",
    Diluc: "Дилюк",
    Diona: "Диона",
    Eula: "Эола",
    Fischl: "Фишль",
    Ganyu: "Гань Юй",
    HuTao: "Ху Тао",
    Jean: "Джинн",
    Kaeya: "Кэйа",
    Kazuha: "Кадзуха",
    KeQing: "Кэ Цин",
    Klee: "Кли",
    Lisa: "Лиза",
    Lumine: "Люмин",
    Mona: "Мона",
    NingGuang: "Нин Гуан",
    Noelle: "Ноэлль",
    QiQi: "Ци Ци",
    Raiden: "Райдэн",
    Razor: "Рэйзор",
    Rosaria: "Розария",
    Sucrose: "Сахароза",
    Tartaglia: "Тарталья",
    Venti: "Венти",
    XiangLing: "Сян Лин",
    Xiao: "Сяо",
    XingQiu: "Син Цю",
    Xinyan: "Синь Янь",
    Yanfei: "Янь Фэй",
    Yoimiya: "Ёимия",
    ZhongLi: "Чжун Ли",
  };
  
