import { ECharacter } from "../../types/enums";

export const engNames: Record<ECharacter, string> = {
  [ECharacter.Aether]: "Aether",
  [ECharacter.Albedo]: "Albedo",
  [ECharacter.Amber]: "Amber",
  [ECharacter.Barbara]: "Barbara",
  [ECharacter.Beidou]: "Beidou",
  [ECharacter.Bennett]: "Bennett",
  [ECharacter.ChongYun]: "Chong Yun",
  [ECharacter.Diluc]: "Diluc",
  [ECharacter.Diona]: "Diona",
  [ECharacter.Eula]: "Eula",
  [ECharacter.Fischl]: "Fischl",
  [ECharacter.Ganyu]: "Ganyu",
  [ECharacter.HuTao]: "Hu Tao",
  [ECharacter.Jean]: "Jean",
  [ECharacter.Kaeya]: "Kaeya",
  [ECharacter.Kazuha]: "Kazuha",
  [ECharacter.KeQing]: "Ke Qing",
  [ECharacter.Klee]: "Klee",
  [ECharacter.Lisa]: "Lisa",
  [ECharacter.Lumine]: "Lumine",
  [ECharacter.Mona]: "Mona",
  [ECharacter.NingGuang]: "Ning Guang",
  [ECharacter.Noelle]: "Noelle",
  [ECharacter.QiQi]: "Qi Qi",
  [ECharacter.Raiden]: "Raiden",
  [ECharacter.Razor]: "Razor",
  [ECharacter.Rosaria]: "Rosaria",
  [ECharacter.Sucrose]: "Sucrose",
  [ECharacter.Tartaglia]: "Tartaglia",
  [ECharacter.Venti]: "Venti",
  [ECharacter.XiangLing]: "Xiang Ling",
  [ECharacter.Xiao]: "Xiao",
  [ECharacter.XingQiu]: "Xing Qiu",
  [ECharacter.Xinyan]: "Xinyan",
  [ECharacter.Yanfei]: "Yanfei",
  [ECharacter.Yoimiya]: "Yoimiya",
  [ECharacter.ZhongLi]: "Zhong Li",
};

export const rusNames: Record<ECharacter, string> = {
  [ECharacter.Aether]: "Итэр",
  [ECharacter.Albedo]: "Альбедо",
  [ECharacter.Amber]: "Эмбер",
  [ECharacter.Barbara]: "Барбара",
  [ECharacter.Beidou]: "Бэй Доу",
  [ECharacter.Bennett]: "Беннет",
  [ECharacter.ChongYun]: "Чун Юнь",
  [ECharacter.Diluc]: "Дилюк",
  [ECharacter.Diona]: "Диона",
  [ECharacter.Eula]: "Эола",
  [ECharacter.Fischl]: "Фишль",
  [ECharacter.Ganyu]: "Гань Юй",
  [ECharacter.HuTao]: "Ху Тао",
  [ECharacter.Jean]: "Джинн",
  [ECharacter.Kaeya]: "Кэйа",
  [ECharacter.Kazuha]: "Кадзуха",
  [ECharacter.KeQing]: "Кэ Цин",
  [ECharacter.Klee]: "Кли",
  [ECharacter.Lisa]: "Лиза",
  [ECharacter.Lumine]: "Люмин",
  [ECharacter.Mona]: "Мона",
  [ECharacter.NingGuang]: "Нин Гуан",
  [ECharacter.Noelle]: "Ноэлль",
  [ECharacter.QiQi]: "Ци Ци",
  [ECharacter.Raiden]: "Райдэн",
  [ECharacter.Razor]: "Рэйзор",
  [ECharacter.Rosaria]: "Розария",
  [ECharacter.Sucrose]: "Сахароза",
  [ECharacter.Tartaglia]: "Тарталья",
  [ECharacter.Venti]: "Венти",
  [ECharacter.XiangLing]: "Сян Лин",
  [ECharacter.Xiao]: "Сяо",
  [ECharacter.XingQiu]: "Син Цю",
  [ECharacter.Xinyan]: "Синь Янь",
  [ECharacter.Yanfei]: "Янь Фэй",
  [ECharacter.Yoimiya]: "Ёимия",
  [ECharacter.ZhongLi]: "Чжун Ли",
};

