export const engLeylines: Record<string, string> = {
  EngulfingStorm: "Engulfing Storm",
  SmolderingFlames: "Smoldering Flames",
  MonsterAttendants: "Monster Attendants",
  Adrenaline: "Adrenaline",
  CondensedIce: "Condensed Ice",
  LightingBolts: "Lighting Bolts",
  ReinforcedShields: "Reinforced Shields",
  ElementalRefresh: "Elemental Refresh",
  SlowingWater: "Slowing Water",
  ChaosCluster: "Chaos Cluster",
  HighEnergyCores: "High Energy Cores",
  IcicleBlast: "Icicle Blast",
  PlasmaField: "Plasma Field",
  EnergyTides: "Energy Tides",
  WindCurrent: "Wind Current",
  SheerCold: "Sheer Cold",

  EngulfingStormEffect: "All players take 1 piercing damage.",
  SmolderingFlamesEffect: "All players add 1 Burn card to their discard, then apply Pyro to all enemies with no elements applied.",
  MonsterAttendantsEffect: "All enemies have their damage fully removed.",
  AdrenalineEffect: "Players with 7 or less HP add 1 Overheat card to their hand.",
  CondensedIceEffect: "All players add 1 Freeze card to their discard, then apply Cryo to all enemies with no elements applied.",
  LightingBoltsEffect: "All players discard 2 energy, then apply Electro to all enemies with no elements applied.",
  ReinforcedShieldsEffect: "All players gain 3 Guard.",
  ElementalRefreshEffect: "All enemies have their applied elements removed.",
  SlowingWaterEffect: "All players discard 1 random card, then apply Hydro to all enemies with no elements applied.",
  ChaosClusterEffect: "Players with 5 or more energy take 2 damage.",
  HighEnergyCoresEffect: "Players with 5 or more energy restore 1 HP.",
  IcicleBlastEffect: "All players must trash their every Freeze card in their hand or discard pile, then take 1 piercing damage per card trashed.",
  PlasmaFieldEffect: "All players with no energy gain 3 energy.",
  EnergyTidesEffect: "Players with 5 or more energy loose 2 energy, everyone else gain 2 energy.",
  WindCurrentEffect: "Players with 7 or less HP add 1 Dash card to their hand.",
  SheerColdEffect: "All players with no Freeze card in their hands adds 1 Freeze card to the top of their deck.",
};

export const rusLeylines: Record<string, string> = {
  EngulfingStorm: "Охватывающий шторм",
  SmolderingFlames: "Тлеющее пламя",
  MonsterAttendants: "Прислужники монстров",
  Adrenaline: "Адреналин",
  CondensedIce: "Конденсированный лёд",
  LightingBolts: "Удары молний",
  ReinforcedShields: "Укрепление щитов",
  ElementalRefresh: "Элементальное очищение",
  SlowingWater: "Замедляющая вода",
  ChaosCluster: "Кластер хаоса",
  HighEnergyCores: "Высокоэнергетическое ядро",
  IcicleBlast: "Взрывные сосульки",
  PlasmaField: "Плазменное поле",
  EnergyTides: "Прилив энергии",
  WindCurrent: "Течение ветров",
  SheerCold: "Абсолютный холод",

  EngulfingStormEffect: "Все игроки получают 1 пронзающий урон.",
  SmolderingFlamesEffect: "Все игроки добавляют 1 Горение в их колоду сброса, затем накладывается Пиро на всех врагов без эффектов.",
  MonsterAttendantsEffect: "Все враги полностью восстанавливаются.",
  AdrenalineEffect: "Игроки с 7 или меньше ОЗ получают 1 Перегрузку в их руку.",
  CondensedIceEffect: "Все игроки добавляют 1 Заморозку в их колоду сброса, затем накладывается Крио на всех врагов без эффектов.",
  LightingBoltsEffect: "Все игроки теряют 2 энергии, затем накладывается Электро на всех врагов без эффектов.",
  ReinforcedShieldsEffect: "Все игроки получают 3 защиты.",
  ElementalRefreshEffect: "Со всех врагов снимаются элементы.",
  SlowingWaterEffect: "Все игроки сбрасывают 1 случайную карту, затем накладывается Гидро на всех врагов без эффектов.",
  ChaosClusterEffect: "Игроки с 5 или больше энергии получают 2 урона.",
  HighEnergyCoresEffect: "Игроки с 5 или больше энергии восстанавливают 1 ОЗ.",
  IcicleBlastEffect: "Все игроки должны удалить все карты Заморозки из руки или колоды сброса, затем получите 1 пронзающий урон за каждую удалённую карту.",
  PlasmaFieldEffect: "Все игроки без энергии получают 3 энергии.",
  EnergyTidesEffect: "Игроки с 5 или больше энергии теряют 2 энергии, остальные получают 2 энергии.",
  WindCurrentEffect: "Игроки с 7 или меньше ОЗ получают 1 Рывок в руку.",
  SheerColdEffect: "Все игроки, у которых нет Заморозки в руке получают 1 Заморозку на верх колоды.",
};
