export const engPlayerEffects: Record<string, string> = {
  Breastplate: "Breastplate",
  DominusLapidis: "Dominus Lapidis",
  ExplosivePuppet: "Explosive Puppet",
  GuideOfAfterlife: "Guide Of Afterlife",
  GuobaFire: "Guoba Fire",
  LayeredFrost: "Layered Frost",
  LetTheShowBegin: "Let The Show Begin",
  MirrorReflections: "Mirror Reflections",
  Nightrider: "Nightrider",
  NightriderPlus: "Nightrider+",
  NiwabiFireDance: "Niwabi Fire-Dance",
  Overheat: "Overheat",
  Pyronado: "Pyronado",
  Raincutter: "Raincutter",
  SkywardSonnet: "Skyward Sonnet",
  SkywardSonnetPlus: "Skyward Sonnet+",
  SolarIsotoma: "Solar Isotoma",
  Stormbreaker: "Stormbreaker",
  TrailOfTheQilin: "Trail Of The Qilin",

  BreastplateEffect: "This turn: your normal attacks restore 1 HP to any 1 player. (Breastplate+)",
  DominusLapidisEffect: "Give 3 Guard to yourself and 1 other player. Apply Geo to all enemies in your zone. At the start of next turn, apply Geo to all enemies in your zone.",
  ExplosivePuppetEffect: "Target enemy cannot attack this round. At the start of next turn: apply Pyro and deal 2 damage to all enemies in your zone.",
  GuideOfAfterlifeEffect: "This turn: your Normal Attacks apply Pyro to any enemies they target.",
  GuobaFireEffect: "Apply Pyro and deal 2 damage to all enemies in your zone. At the start of next turn, repeat this effect.",
  LayeredFrostEffect: "This turn: your normal attacks apply Cryo to any enemies they target.",
  LetTheShowBeginEffect: "This turn: your normal attacks restore 1 HP to any 1 player. (Let The Show Begin+)",
  MirrorReflectionsEffect: "Target enemy cannot attack this round. At the start of next turn: apply Hydro and deal 2 damage to all enemies in your zone.",
  NightriderEffect: "Apply Electro and deal 1 piercing damage to 1 enemy in your zone. At the start of next turn, repeat this effect.",
  NightriderPlusEffect: "Apply Electro and deal 2 piercing damage to 1 enemy anywhere. At the start of next turn, repeat this effect.",
  NiwabiFireDanceEffect: "This turn: your next normal attack will apply Pyro to any enemies it targets.",
  OverheatEffect: "The next time you deal damage this turn, increase the damage dealt by 1. If this damage defeats the enemy, gain 2 Energy.",
  PyronadoEffect: "Applied when switching to Xiang Ling. At the start of next turn: apply Pyro and deal 2 damage to all enemies in your zone.",
  RaincutterEffect: "Applied when switching to Xing Qiu. This turn: your Normal Attacks apply Hydro to any enemies they target and can restore HP.",
  SkywardSonnetEffect: "Apply Anemo to all enemies in your zone. This turn: your next Normal attack deals +1 damage.",
  SkywardSonnetPlusEffect: "Apply Anemo to all enemies in your zone and any one player's zone. This turn: your next Normal attack deals +2 damage.",
  SolarIsotomaEffect: "Apply Geo to all enemies in your zone. At the start of next turn, apply Geo again. You may trash a card from hand or discard to draw a card.",
  StormbreakerEffect: "Applied when switching to Beidou. This turn: after your Normal Attack cards resolve, deal 1 piercing damage to 1 enemy that was targeted.",
  TrailOfTheQilinEffect: "Target enemy cannot attack this round. At the start of next turn: apply Cryo and deal 2 damage to all enemies in your zone.",
};

export const rusPlayerEffects: Record<string, string> = {
  Breastplate: "Нагрудник",
  DominusLapidis: "Доминус Лапидис",
  ExplosivePuppet: "Взрывная кукла",
  GuideOfAfterlife: "Путеводная в загробную жизнь",
  GuobaFire: "Огонь Гобы",
  LayeredFrost: "Слоёный иней",
  LetTheShowBegin: "Начинаем концерт",
  MirrorReflections: "Зеркальные отражения",
  Nightrider: "Тень расправленных крыльев",
  NightriderPlus: "Тень расправленных крыльев+",
  NiwabiFireDance: "Танец огня Ниваби",
  Overheat: "Перегрузка",
  Pyronado: "Пиронадо",
  Raincutter: "Дождевой меч",
  SkywardSonnet: "Небесная соната",
  SkywardSonnetPlus: "Небесная соната+",
  SolarIsotoma: "Солнечная изотома",
  Stormbreaker: "Громобой",
  TrailOfTheQilin: "Тропа Цилиня",

  BreastplateEffect: "На этом ходу ваши обычные атаки восстанавливают 1 ОЗ любому игроку. (Нагрудник+)",
  DominusLapidisEffect: "Даёт 3 защиты вам и 1 другому игроку. Накладывает Гео всем врагам в вашей зоне. В начале следующего хода накладывает Гео всем врагам в вашей зоне.",
  ExplosivePuppetEffect: "Выбранный враг не может атаковать в этом раунде. В начале следующего хода: наложите Пиро и нанесите 2 урона всем врагам в вашей зоне.",
  GuideOfAfterlifeEffect: "На этом ходу ваши обычные атаки накладывают Пиро на атакованных врагов.",
  GuobaFireEffect: "Накладывает Пиро и наносит 2 урона всем врагам в вашей зоне. В начале следующего хода повторяет этот эффект.",
  LayeredFrostEffect: "На этом ходу ваши обычные атаки накладывают Крио на атакованных врагов.",
  LetTheShowBeginEffect: "На этом ходу ваши обычные атаки восстанавливают 1 ОЗ любому игроку. (Начинаем концерт+)",
  MirrorReflectionsEffect: "Выбранный враг не может атаковать в этом раунде. В начале следующего хода: наложите Гидро и нанесите 2 урона всем врагам в вашей зоне.",
  NightriderEffect: "Накладывает Электро и наносит 1 пронзающий урон 1 врагу в вашей зоне. В начале следующего хода повторяет эффект.",
  NightriderPlusEffect: "Накладывает Электро и наносит 2 пронзающего урона 1 врагу где угодно. В начале следующего хода повторяет эффект.",
  NiwabiFireDanceEffect: "На этом ходу ваша следующая обычная атака наложит Пиро на атакованных врагов.",
  OverheatEffect: "В следующий раз, когда вы нанесёте урон в этот ход, увеличьте нанесённый урон на 1. Если этот урон побеждает врага, получите 2 энергии.",
  PyronadoEffect: "Накладывается при смене на Сян Лин. В начале следующего хода: наложите Пиро и нанесите 2 урона всем врагам в вашей зоне.",
  RaincutterEffect: "Накладывается при смене на Син Цю. На этом ходу ваши обычные атаки накладывают Гидро и могут восстанавливать ОЗ.",
  SkywardSonnetEffect: "Накладывает Анемо всем врагам в вашей зоне. На этом ходу ваша следующая обычная атака наносит +1 урона.",
  SkywardSonnetPlusEffect: "Накладывает Анемо всем врагам в вашей зоне и зоне одного игрока. На этом ходу ваша следующая обычная атака наносит +2 урона.",
  SolarIsotomaEffect: "Накладывает Гео всем врагам в вашей зоне. В начале следующего хода накладывает Гео снова. Вы можете выбросить карту из руки или сброса, чтобы вытянуть карту.",
  StormbreakerEffect: "Накладывается при смене на Бэй Доу. На этом ходу после разрешения ваших обычных атак: нанесите 1 пронзающий урон 1 атакованному врагу.",
  TrailOfTheQilinEffect: "Выбранный враг не может атаковать в этом раунде. В начале следующего хода: наложите Крио и нанесите 2 урона всем врагам в вашей зоне.",
};
