export const engPlayerEffects: Record<string, string> = {
  Breastplate: "Breastplate",
  DominusLapidis: "Dominus Lapidis",
  ExplosivePuppet: "Explosive Puppet",
  GuideOfAfterlife: "Guide Of Afterlife",
  GuobaFire: "Guoba Fire",
  LayeredFrost: "Layered Frost",
  LetTheShowBegin: "Let The Show Begin",
  MirrorReflections: "Mirror Reflections",
  NiwabiFireDance: "Niwabi Fire-Dance",
  Overheat: "Overheat",
  Pyronado: "Pyronado",
  Raincutter: "Raincutter",
  SkywardSonnet: "Skyward Sonnet",
  SkywardSonnetPlus: "Skyward Sonnet+",
  SolarIsotoma: "Solar Isotoma",
  Stormbreaker: "Stormbreaker",
  TrailOfTheQilin: "Trail Of The Qilin",
  GlacialIllumination: "Glacial Illumination",

  BreastplateEffect: "This turn: your normal attacks restore 1 HP to any 1 player.",
  DominusLapidisEffect: "At the start of next turn, apply Geo to all enemies in your zone.",
  ExplosivePuppetEffect: "At the start of next turn: apply Pyro and deal 2 damage to all enemies in your zone.",
  GuideOfAfterlifeEffect: "This turn: your Normal Attacks apply Pyro to any enemies they target.",
  GuobaFireEffect: "At the start of next turn: apply Pyro and deal 2 damage to all enemies in your zone.",
  LayeredFrostEffect: "This turn: your normal attacks apply Cryo to any enemies they target.",
  LetTheShowBeginPlusEffect: "This turn: your normal attacks restore 1 HP to 1 random player.",
  MirrorReflectionsEffect: "At the start of next turn: apply Hydro and deal 2 damage to all enemies in your zone.",
  NiwabiFireDanceEffect: "This turn: your next normal attack will apply Pyro to any enemies it targets.",
  OverheatEffect: "The next time you deal damage this turn, increase the damage dealt by 1. If this damage defeats the enemy, gain 2 Energy.",
  PyronadoEffect: "This turn: you Normal Attacks will apply Pyro to any enemies they target.",
  RaincutterEffect: "This turn: your Normal Attacks apply Hydro to any enemies they target.",
  SkywardSonnetEffect: "This turn: your next Normal attack deals +1 damage.",
  SkywardSonnetPlusEffect: "This turn: your next Normal attack deals +2 damage.",
  SolarIsotomaEffect: "At the start of next turn, apply Geo to all enemies in your zone.",
  StormbreakerEffect: "This turn: after your Normal Attack cards resolve, deal 1 piercing damage to 1 enemy that was targeted.",
  TrailOfTheQilinEffect: "At the start of next turn: apply Cryo and deal 2 damage to all enemies in your zone.",
  GlacialIlluminationEffect: "When you play an Eula card, add 1 ❄.",
};

export const rusPlayerEffects: Record<string, string> = {
  Breastplate: "Бронефартук",
  DominusLapidis: "Власть над камнем",
  ExplosivePuppet: "Барон Зайчик",
  GuideOfAfterlife: "Путеводитель по загробной жизни",
  GuobaFire: "Атака Гобы",
  LayeredFrost: "Духовное лезвие: Холод Чунхуа",
  LetTheShowBegin: "Да начнётся шоу",
  MirrorReflections: "Отражение фатума",
  NiwabiFireDance: "Огненный танец Ниваби",
  Overheat: "Перегрузка",
  Pyronado: "Огневихрь",
  Raincutter: "Радужная стойка",
  SkywardSonnet: "Небесная поэзия",
  SkywardSonnetPlus: "Небесная поэзия+",
  SolarIsotoma: "Цветок солнца",
  Stormbreaker: "Крушитель бури",
  TrailOfTheQilin: "След цилиня",
  GlacialIllumination: "Сумеречный меч",

  BreastplateEffect: "На этом ходу ваши обычные атаки восстанавливают 1 ОЗ любому игроку.",
  DominusLapidisEffect: "В начале следующего хода накладывает Гео всем врагам в вашей зоне.",
  ExplosivePuppetEffect: "В начале следующего хода накладывает Пиро и наносит 2 урона всем врагам в вашей зоне.",
  GuideOfAfterlifeEffect: "На этом ходу ваши обычные атаки будут накладывать Пиро.",
  GuobaFireEffect: "В начале следующего хода накладывает Пиро и наносит 2 урона всем врагам в вашей зоне.",
  LayeredFrostEffect: "На этом ходу ваши обычные атаки будут накладывать Крио.",
  LetTheShowBeginPlusEffect: "На этом ходу ваши обычные атаки восстанавливают 1 ОЗ случайному игроку.",
  MirrorReflectionsEffect: "В начале следующего хода накладывает Гидро и наносит 2 урона всем врагам в вашей зоне.",
  NiwabiFireDanceEffect: "На этом ходу ваша следующая обычная атака наложит Пиро.",
  OverheatEffect: "Следующий нанесённый урон будет увеличен на 1. Если этот урон побеждает врага, получите 2 энергии.",
  PyronadoEffect: "На этом ходу ваши обычные атаки будут накладывать Пиро.",
  RaincutterEffect: "На этом ходу ваши обычные атаки будут накладывать Гидро.",
  SkywardSonnetEffect: "На этом ходу ваша следующая обычная атака нанесёт +1 урон.",
  SkywardSonnetPlusEffect: "На этом ходу ваша следующая обычная атака нанесёт +2 урона.",
  SolarIsotomaEffect: "В начале следующего хода, накладывает Гео всем врагам в вашей зоне.",
  StormbreakerEffect: "На этом ходу после обычной атаки враг получит дополнительно 1 пронзающий урон.",
  TrailOfTheQilinEffect: "В начале следующего хода накладывает Крио и наносит 2 урона всем врагам в вашей зоне.",
  GlacialIlluminationEffect: "Когда разыгрывается карты Эолы, добавляется 1 ❄.",
};
