import { ECard, ECardType } from "../../types/enums";

export const cards: Record<
  ECard,
  {
    cost: number;
    cardType: ECardType;
    isUpgraded: boolean;
    canPlay: boolean;
    canUpgrade: boolean;
    isCanSelectItself?: boolean;
    require?: {
      enemiesCount?: number;
      enemiesCountMax?: number;
      isRange?: boolean;
      isCanAlternative?: boolean;
      isNeedPlayer?: boolean;
      isNeedCardFrom?: ("hand" | "discard" | "deck")[];
    };
  }
> = {
  [ECard.ForeignRockblade]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1 },
  },
  [ECard.ForeignRockbladePlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.StarfellSword]: { cost: 2, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.StarfellSwordPlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.WeissBladework]: { cost: 1, cardType: ECardType.Attack, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.WeissBladeworkPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.SolarIsotoma]: {
    cost: 2,
    cardType: ECardType.Skill,
    isUpgraded: false,
    canUpgrade: true,
    canPlay: true,
    isCanSelectItself: false,
    require: { isNeedCardFrom: ["hand", "discard"] },
  },
  [ECard.SolarIsotomaPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    isUpgraded: true,
    canUpgrade: false,
    canPlay: true,
    isCanSelectItself: false,
    require: { isNeedCardFrom: ["hand", "discard"] },
  },
  [ECard.Sharpshooter]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.SharpshooterPlus]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.ExplosivePuppet]: { cost: 2, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.ExplosivePuppetPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.WhisperOfWater]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.WhisperOfWaterPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { isNeedPlayer: true },
  },
  [ECard.LetTheShowBegin]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isNeedPlayer: true, isCanAlternative: true },
  },
  [ECard.LetTheShowBeginPlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.Oceanborn]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.OceanbornPlus]: { cost: 1, cardType: ECardType.Attack, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.Tidecaller]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.TidecallerPlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.StrikeOfFortune]: { cost: 1, cardType: ECardType.Attack, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.StrikeOfFortunePlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.PassionOverload]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.PassionOverloadPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.Demonbane]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.DemonbanePlus]: {
    cost: 1, cardType: ECardType.Attack, isUpgraded: true, canUpgrade: false, canPlay: true, require: {
      enemiesCount: 1
    }
  },
  [ECard.LayeredFrost]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.LayeredFrostPlus]: { cost: 0, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.TemperedSword]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.TemperedSwordPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.SearingOnslaught]: {
    cost: 2,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1 },
  },
  [ECard.SearingOnslaughtPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.KatzleinStyle]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.KatzleinStylePlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.IcyPaws]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true, require: { isCanAlternative: true } },
  [ECard.IcyPawsPlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.EdelBladework]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.EdelBladeworkPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.IcetideVortex]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.IcetideVortexPlus]: {
    cost: 0,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.BoltsOfDownfall]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.BoltsOfDownfallPlus]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.Nightrider]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.NightriderPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.LiutianArchery]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.LiutianArcheryPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.TrailOfTheQilin]: { cost: 2, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.TrailOfTheQilinPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.SpearOfWangsheng]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1 },
  },
  [ECard.SpearOfWangshengPlus]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.GuideOfAfterlife]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { isCanAlternative: true },
  },
  [ECard.GuideOfAfterlifePlus]: {
    cost: 0,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { isCanAlternative: true },
  },
  [ECard.FavoniusBladework]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1 },
  },
  [ECard.FavoniusBladeworkPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.GaleBlade]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, enemiesCountMax: 2, isRange: true, isCanAlternative: true },
  },
  [ECard.GaleBladePlus]: {
    cost: 0,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, enemiesCountMax: 2, isRange: true, isCanAlternative: true },
  },
  [ECard.CeremonialBladework]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1 },
  },
  [ECard.CeremonialBladeworkPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.Frostgnaw]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.FrostgnawPlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.GaryuuBladework]: { cost: 1, cardType: ECardType.Attack, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.GaryuuBladeworkPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.Chihayaburu]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 2, isRange: true, isCanAlternative: true },
  },
  [ECard.ChihayaburuPlus]: { cost: 0, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.YunlaiSwordsmanship]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1 },
  },
  [ECard.YunlaiSwordsmanshipPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.StellarRestoration]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.StellarRestorationPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 3, isRange: true },
  },
  [ECard.Kaboom]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.KaboomPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.JumpyDumpty]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 2, isCanAlternative: true },
  },
  [ECard.JumpyDumptyPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 2, isCanAlternative: true },
  },
  [ECard.LightningTouch]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.LightningTouchPlus]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.VioletArc]: { cost: 2, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.VioletArcPlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.ForeignIronwind]: { cost: 1, cardType: ECardType.Attack, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.ForeignIronwindPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.PalmVortex]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.PalmVortexPlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.RippleOfFate]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.RippleOfFatePlus]: { cost: 0, cardType: ECardType.Attack, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.MirrorReflections]: {
    cost: 2,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1 },
  },
  [ECard.MirrorReflectionsPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.SparklingScatter]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.SparklingScatterPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 2, isRange: true },
  },
  [ECard.JadeScreen]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true, require: { isNeedPlayer: true } },
  [ECard.JadeScreenPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { isNeedPlayer: true },
  },
  [ECard.MaidsBladework]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.MaidsBladeworkPlus]: { cost: 0, cardType: ECardType.Attack, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.Breastplate]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.BreastplatePlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.AncientSwordArt]: { cost: 1, cardType: ECardType.Attack, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.AncientSwordArtPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1 },
  },
  [ECard.HeraldOfFrost]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.HeraldOfFrostPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.Origin]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.OriginPlus]: { cost: 1, cardType: ECardType.Attack, isUpgraded: true, canUpgrade: false, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.BalefulOmen]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true, require: { isNeedPlayer: true } },
  [ECard.BalefulOmenPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { isNeedPlayer: true },
  },
  [ECard.SteelFang]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.SteelFangPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.ClawAndThunder]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.ClawAndThunderPlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.SpearOfTheChurch]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 2, isRange: true, isCanAlternative: true },
  },
  [ECard.SpearOfTheChurchPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.RavagingConfession]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.RavagingConfessionPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.WindSpiritCreation]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.WindSpiritCreationPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 2, isRange: true },
  },
  [ECard.AnemoHypostatis]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.AnemoHypostatisPlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.CuttingTorrent]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.CuttingTorrentPlus]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.RagingTide]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.RagingTidePlus]: { cost: 0, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.DivineArchery]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.DivineArcheryPlus]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true, isCanAlternative: true },
  },
  [ECard.SkywardSonnet]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.SkywardSonnetPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { isNeedPlayer: true },
  },
  [ECard.DoughFu]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.DoughFuPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.GuobaFire]: { cost: 2, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.GuobaFirePlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.WhirlwindThrust]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 2, isRange: true, isCanAlternative: true },
  },
  [ECard.WhirlwindThrustPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.LemniscaticWind]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.LemniscaticWindPlus]: { cost: 1, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.GuhuaStyle]: { cost: 1, cardType: ECardType.Attack, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.GuhuaStylePlus]: { cost: 1, cardType: ECardType.Attack, isUpgraded: true, canUpgrade: false, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.FatalRainscreen]: {
    cost: 2,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isNeedPlayer: true },
  },
  [ECard.FatalRainscreenPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isNeedPlayer: true },
  },
  [ECard.DanceOfFire]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.DanceOfFirePlus]: { cost: 1, cardType: ECardType.Attack, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.SweepingFervor]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.SweepingFervorPlus]: { cost: 0, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.SealOfApproval]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.SealOfApprovalPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.SignedEdict]: { cost: 1, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true, require: { enemiesCount: 1 } },
  [ECard.SignedEdictPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { isCanAlternative: true, isNeedPlayer: true },
  },
  [ECard.FireworkFlareUp]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 1, isRange: true },
  },
  [ECard.FireworkFlareUpPlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 3, isRange: true },
  },
  [ECard.NiwabiFireDance]: { cost: 0, cardType: ECardType.Skill, isUpgraded: false, canUpgrade: true, canPlay: true },
  [ECard.NiwabiFireDancePlus]: { cost: 0, cardType: ECardType.Skill, isUpgraded: true, canUpgrade: false, canPlay: true },
  [ECard.RainOfStone]: {
    cost: 0,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { enemiesCount: 2, isRange: true, isCanAlternative: true },
  },
  [ECard.RainOfStonePlus]: {
    cost: 1,
    cardType: ECardType.Attack,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { enemiesCount: 1, isCanAlternative: true },
  },
  [ECard.DominusLapidis]: {
    cost: 2,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: false,
    canUpgrade: true,
    require: { isNeedPlayer: true },
  },
  [ECard.DominusLapidisPlus]: {
    cost: 1,
    cardType: ECardType.Skill,
    canPlay: true,
    isUpgraded: true,
    canUpgrade: false,
    require: { isNeedPlayer: true },
  },
  [ECard.Dash]: { cost: 0, cardType: ECardType.Other, isUpgraded: false, canUpgrade: false, canPlay: true },
  [ECard.Overheat]: { cost: 0, cardType: ECardType.Other, isUpgraded: false, canUpgrade: false, canPlay: true },
  [ECard.Burn]: { cost: 0, cardType: ECardType.Other, isUpgraded: false, canPlay: false, canUpgrade: false },
  [ECard.Freeze]: { cost: 1, cardType: ECardType.Other, isUpgraded: false, canUpgrade: false, canPlay: true },
};
