export const engDescriptions: Record<string, string> = {
  ForeignRockblade: "Deal 3 damage to 1 enemy in your zone.",
  ForeignRockbladePlus: "Apply Geo and deal 3 damage to 1 enemy in your zone. Gain 2 energy.",
  StarfellSword: "Apply Geo and then deal 2 piercing damage to all enemies in your zone.",
  StarfellSwordPlus: "Apply Geo and then deal 2 piercing damage to all enemies in your zone.",
  WeissBladework: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Geo applied.",
  WeissBladeworkPlus: "Deal 3 damage to 1 enemy in your zone. If effect of the Abiogenesis: Solar Isotoma card was triggered This turn: gain 1 Action Point to spend to spend this turn and draw 1 card.",
  SolarIsotoma: "Apply Geo to all enemies in your zone. At the start next turn, apply Geo to all enemies in your zone. You may trash a card from you hand or discard to draw a card.",
  SolarIsotomaPlus: "Apply Geo to all enemies in your zone. At the start next turn, apply Geo to all enemies in your zone. You may trash a card from you hand or discard to draw a card.",
  Sharpshooter: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Pyro to that enemy.",
  SharpshooterPlus: "Deal 1 piercing damage to 1 enemy anywhere. Deal 3 damage instead if the enemy had no shields.",
  ExplosivePuppet: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Pyro and deal 2 damage to all enemies in your zone.",
  ExplosivePuppetPlus: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Pyro and deal 2 damage to all enemies in your zone.",
  WhisperOfWater: "Apply Hydro and deal 1 piercing damage to 1 enemy to anywhere. Draw 1 card.",
  WhisperOfWaterPlus: "Restore 2 HP to yourself and 1 other player.",
  LetTheShowBegin: "Apply Hydro to 1 enemy in your zone. Restore 1 HP to any 1 player. You may spend 2 energy to restore 3 HP instead.",
  LetTheShowBeginPlus: "Apply Hydro to all enemies in your zone. This Turn: your normal attacks will restore 1 HP to any 1 player.",
  Oceanborn: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  OceanbornPlus: "Deal 2 damage to all enemies in your zone. Deal 4 damage instead if you took damage last turn.",
  Tidecaller: "Apply Electro to all enemies in your zone. Gain 2 Guard.",
  TidecallerPlus: "Apply Electro to all enemies in your zone. Gain 3 Guard and add an Overheat card to your hand.",
  StrikeOfFortune: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Pyro applied.",
  StrikeOfFortunePlus: "Deal 3 damage to 1 enemy in your zone. If you have 7 or less HP, deal 1 additional damage and gain 3 energy.",
  PassionOverload: "Apply Pyro and deal 2 damage to 1 enemy in your zone. Discard the top card of your deck. If it was a Burn or Bennett card, take 1 damage and deal 1 damage to all enemies in your zone. Trash Burn cards discarded this way.",
  PassionOverloadPlus: "Apply Pyro and deal 4 damage to 1 enemy in your zone. Discard the top card of your deck. If it was a Burn or Bennett card, take 1 damage and deal 1 damage to all enemies in your zone. Trash Burn cards discarded this way.",
  Demonbane: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  DemonbanePlus: "Deal 2 damage to all enemies in your zone. 1 enemy with Cryo applied takes 4 damage instead.",
  LayeredFrost: "Draw 1 card. This turn: your normal attacks will apply Cryo to any enemies they target.",
  LayeredFrostPlus: "Draw 1 card. This turn: your normal attacks will apply Cryo to any enemies they target.",
  TemperedSword: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  TemperedSwordPlus: "Destroy all shields to 1 enemy in your zone. Deal 4 damage instead if the enemy has no shields.",
  SearingOnslaught: "Apply Pyro and deal 2 damage to 1 enemy in your zone. Immediately repeat this effect 2 more times.",
  SearingOnslaughtPlus: "Apply Pyro and deal 2 damage to 1 enemy in your zone. Immediately repeat this effect 2 more times.",
  KatzleinStyle: "Deal 2 piercing damage to 1 enemy anywhere.",
  KatzleinStylePlus: "Deal 2 piercing damage to 1 enemy anywhere. If you have any Guard, deal 5 piercing damage instead.",
  IcyPaws: "Either gain 3 Guard OR apply Cryo to all enemies in your zone. You may trash a Burn card in your discard.",
  IcyPawsPlus: "Apply Cryo to all enemies in your zone. Gain 3 Guard. You may trash a Burn cards in your discard.",
  EdelBladework: "Destroy 1 shield to 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 2 energy to apply Cryo to this enemy.",
  EdelBladeworkPlus: "Apply Cryo and deal 2 damage to 1 enemy in your zone. Place a ❄ to Eula's Burst.",
  IcetideVortex: "Apply Cryo to 1 enemy in your zone. Either search your deck for a Eula card and add it to your hand or add all Eula cards from your discard into your hand.",
  IcetideVortexPlus: "Apply Cryo to 1 enemy in your zone. Either search your deck for a Eula card and add it to your hand or add all Eula cards from your discard into your hand.",
  BoltsOfDownfall: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Electro to this enemy.",
  BoltsOfDownfallPlus: "Deal 1 piercing damage to 1 enemy anywhere. If effect of the Nightrider card was triggered This turn: deal 3 piercing damage instead.",
  Nightrider: "Apply Electro and deal 1 piercing damage to 1 enemy in your zone. At the start next turn repeat this effect.",
  NightriderPlus: "Apply Electro and deal 2 piercing damage to 1 enemy anywhere. At the start next turn repeat this effect.",
  LiutianArchery: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Cryo to this enemy.",
  LiutianArcheryPlus: "Deal 2 damage to 1 enemy anywhere. You may spend 2 energy to apply Cryo to this enemy and triple the damage dealt.",
  TrailOfTheQilin: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Cryo and deal 2 damage to all enemies in your zone.",
  TrailOfTheQilinPlus: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Cryo and deal 2 damage to all enemies in your zone.",
  SpearOfWangsheng: "Deal 1 piercing damage to 1 enemy in your zone. If you had 7 or less HP, deal 2 piercing damage instead.",
  SpearOfWangshengPlus: "Take 1 damage. Deal 1 piercing damage to 1 enemy in your zone. If you had 7 or less HP, deal 4 piercing damage instead and shuffle this back into your deck.",
  GuideOfAfterlife: "Take 1 damage. Either gain 1 energy or draw 2 cards. This turn: your Normal Attacks will apply Pyro to any enemies they target.",
  GuideOfAfterlifePlus: "Take 1 damage. Either gain 1 energy or draw 2 cards. This turn: your Normal Attacks will apply Pyro to any enemies they target.",
  FavoniusBladework: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Anemo applied.",
  FavoniusBladeworkPlus: "Deal 2 damage to 1 enemy in your zone and gain 2 energy. Restore 2 HP to yourself.",
  GaleBlade: "Apply Anemo and deal 1 piercing damage to 1 enemy in your zone. You may swap this enemy with any other faceup enemy.",
  GaleBladePlus: "Apply Anemo and deal 1 piercing damage to 1 enemy in your zone. You may swap this enemy with any other faceup enemy.",
  CeremonialBladework: "Deal 3 damage to 1 enemy in your zone.",
  CeremonialBladeworkPlus: "Deal 2 plus 1d6 damage to 1 enemy in your zone.",
  Frostgnaw: "Apply Cryo to all enemies in your zone. Gain 1 energy.",
  FrostgnawPlus: "Apply Cryo to all enemies in your zone. Gain 2 energy. Restore 2 HP to yourself.",
  GaryuuBladework: "Deal 3 damage to 1 enemy in your zone.",
  GaryuuBladeworkPlus: "Deal 3 damage to 1 enemy in your zone. If the last card you played was Chihayaburu or Dash, deal 6 damage instead.",
  Chihayaburu: "Apply Anemo to 2 different enemies anywhere. You may swap these 2 enemies.",
  ChihayaburuPlus: "Apply Anemo to all enemies in your zone. Draw 2 cards.",
  YunlaiSwordsmanship: "Deal 3 damage to 1 enemy in your zone.",
  YunlaiSwordsmanshipPlus: "Apply Electro and deal 3 damage to 1 enemy in your zone. Gain 2 energy.",
  StellarRestoration: "Apply Electro to 1 enemy anywhere. You may flip 1 other enemy anywhere facedown, removing any tokens it had, and place this enemy on top of it.",
  StellarRestorationPlus: "Apply Electro to up to 3 different enemies anywhere. Gain 2 energy.",
  Kaboom: "Apply Pyro and deal 1 piercing damage to 1 enemy anywhere. Gain 1 energy.",
  KaboomPlus: "Apply Pyro and deal 2 piercing damage to 1 enemy anywhere. You may spend 2 energy to double this damage.",
  JumpyDumpty: "Apply Pyro and deal 1 damage to up to 2 different enemies in your zone. You may return this card to top of your deck after playing it.",
  JumpyDumptyPlus: "Apply Pyro and deal 1 damage to up to 2 different enemies in your zone. You may spend 2 energy to immediately repeat this effect once.",
  LightningTouch: "Apply Electro and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  LightningTouchPlus: "Apply Electro and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  VioletArc: "Deal 5 piercing damage to all enemies in your zone with Electro applied.",
  VioletArcPlus: "Deal 5 piercing damage to all enemies in your zone with Electro applied.",
  ForeignIronwind: "Deal 3 damage to 1 enemy in your zone.",
  ForeignIronwindPlus: "Apply Anemo and deal 3 damage to 1 enemy in your zone. Gain 2 energy.",
  PalmVortex: "Deal 2 energy to all enemies in your zone with Hydro, Pyro, Cryo or Electro applied.",
  PalmVortexPlus: "Deal 4 energy to all enemies in your zone with Hydro, Pyro, Cryo or Electro applied.",
  RippleOfFate: "Apply Hydro and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  RippleOfFatePlus: "Draw 2 cards. Gain 2 energy for every Mona card you drew with this effect.",
  MirrorReflections: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Hydro and deal 2 damage to all enemies in your zone.",
  MirrorReflectionsPlus: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Hydro and deal 2 damage to all enemies in your zone.",
  SparklingScatter: "Apply Geo and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  SparklingScatterPlus: "Apply Geo and deal 2 piercing damage to 2 different enemies anywhere.",
  JadeScreen: "Give any 1 player 3 Guard.",
  JadeScreenPlus: "Give yourself and any 1 other player 3 Guard and 1 energy.",
  MaidsBladework: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  MaidsBladeworkPlus: "Draw 3 cards. Gain 2 Guard.",
  Breastplate: "Apply Geo to all enemies in your zone. Restore 1 HP to yourself.",
  BreastplatePlus: "Apply Geo to all enemies in your zone. This turn: your normal attacks will restore 1 HP to 1 any player.",
  AncientSwordArt: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Cryo applied.",
  AncientSwordArtPlus: "Deal 2 damage to 1 enemy in your zone and gain 2 energy. Deal 5 damage instead if the enemy has Cryo applied.",
  HeraldOfFrost: "Apply Cryo to 1 enemy anywhere. This turn: the next player to target this enemy restores 2 HP.",
  HeraldOfFrostPlus: "Apply Cryo to 1 enemy anywhere. This turn: the next player to target this enemy restores 3 HP and gains 2 energy.",
  Origin: "Deal 2 damage to 1 enemy in your zone. You may spend 2 energy to gain 1 Action Point to spend this turn.",
  OriginPlus: "Deal 2 damage to 1 enemy in your zone. Deal 5 damage instead if he enemy has Electro applied. Gain 2 energy.",
  BalefulOmen: "Apply Electro to all enemies in your zone. Place a 🟣 on another player's board (max 5). Any time played any Normal Attack card, a player may discard a 🟣 to deal 1 piercing damage to 1 enemy in their zone.",
  BalefulOmenPlus: "Apply Electro to all enemies in your zone. Place 2 🟣 on yours and 1 on another player's board (max 5). Any time played any Normal Attack card, a player may discard a 🟣 to deal 1 piercing damage to 1 enemy in their zone.",
  SteelFang: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if he enemy has no shields. You may spend 1 energy to place a 🟣 on Razor's Burst (max 3).",
  SteelFangPlus: "Destroy 1 shield on 1 enemy in your zone and deal 2 damage to that enemy. You may spend 1 energy to place a 🟣 on Razor's Burst (max 3).",
  ClawAndThunder: "Apply Electro to all enemies in our zone. Place a 🟣 on Razor's Burst (max 3) if it has not been activated yet this turn.",
  ClawAndThunderPlus: "Apply Electro to all enemies in your zone. Place a 🟣 on Razor's Burst (max 3) if it has not been activated yet this turn. You may remove all 🟣 from Razor's Burst to gain 2 energy for each 🟣 removed.",
  SpearOfTheChurch: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  SpearOfTheChurchPlus: "Apply Cryo and deal 3 damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  RavagingConfession: "Deal 1 piercing damage to 1 enemy anywhere. You may take the enemy you damaged and place in in your zone.",
  RavagingConfessionPlus: "Apply Cryo and deal 3 damage to 1 enemy anywhere. You may take the enemy you damaged and place in in your zone.",
  WindSpiritCreation: "Apply Anemo and deal 1 piercing damage to 1 enemy anywhere. Gain 1 energy.",
  WindSpiritCreationPlus: "Apply Anemo and deal 2 piercing damage to 2 different enemies anywhere.",
  AnemoHypostatis: "Apply Anemo to 1 enemy anywhere. You may flip 1 other enemy anywhere facedown, removing any tokens it had, and place this enemy on top of it.",
  AnemoHypostatisPlus: "Apply Anemo to all enemies in your zone. For any reactions this triggers, you may choose to restore 3 HP to to any 1 player instead of gaining a Dash card.",
  CuttingTorrent: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Hydro to that enemy.",
  CuttingTorrentPlus: "Deal 1 piercing damage to 1 enemy anywhere. Deal 3 damage instead if the enemy has Hydro applied.",
  RagingTide: "Draw 3 cards. You may discard up to 3 cards to apply Hydro to 1 enemy in your zone per card.",
  RagingTidePlus: "Draw 3 cards. You may discard up to 3 cards to apply Hydro to 1 enemy in your zone per card.",
  DivineArchery: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Anemo to that enemy.",
  DivineArcheryPlus: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to deal 3 piercing damage instead.",
  SkywardSonnet: "Apply Anemo to all enemies in your zone. This turn: your next Normal attack has any damage dealt increased by 1.",
  SkywardSonnetPlus: "Apply Anemo to all enemies in your zone and any one player's zone. This turn: your next Normal attack has any damage dealt increased by 2.",
  DoughFu: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to deal 1 piercing damage to a different enemy anywhere.",
  DoughFuPlus: "Apply Pyro and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 action point.",
  GuobaFire: "Apply Pyro and deal 2 damage to all enemies in your zone. At the start next turn, apply Pyro and deal 2 damage to all enemies in your zone.",
  GuobaFirePlus: "Apply Pyro and deal 2 damage to all enemies in your zone. At the start next turn, apply Pyro and deal 2 damage to all enemies in your zone.",
  WhirlwindThrust: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  WhirlwindThrustPlus: "Apply Anemo and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  LemniscaticWind: "Apply Anemo and deal 1 piercing damage to 1 enemy in your zone. You may return this card to your hand after playing it.",
  LemniscaticWindPlus: "Apply Anemo and deal 2 piercing damage to 1 enemy in your zone. if the last card you played was Dash, deal 5 piercing damage instead.",
  GuhuaStyle: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Hydro applied.",
  GuhuaStylePlus: "Deal 3 damage to 1 enemy in your zone. Deal 5 damage instead if the enemy has Hydro applied.",
  FatalRainscreen: "Gain 4 Guard and apply Hydro to 1 enemy in your zone. Restore 2 HP to 1 any player.",
  FatalRainscreenPlus: "Gain 4 Guard and apply Hydro to 1 enemy in your zone. Restore 2 HP to 1 any player.",
  DanceOfFire: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  DanceOfFirePlus: "Deal 1 damage to all enemies in your zone. If you have Guard, deal 3 damage instead.",
  SweepingFervor: "Gain 3 Guard. Apply Pyro to all enemies in your zone.",
  SweepingFervorPlus: "Gain 3 Guard. Apply Pyro to all enemies in your zone.",
  SealOfApproval: "Apply Pyro and deal 1 piercing damage to 1 enemy anywhere.",
  SealOfApprovalPlus: "Apply Pyro and deal 2 piercing damage to 1 enemy anywhere. Draw 1 card, if there are any 🔥 on Yanfei's Burst. Draw 2 cards instead if there are 3+ 🔥.",
  SignedEdict: "Apply Pyro to 1 enemy in your zone and deal 1 damage to each enemy for each 🔥 on Yanfei's Burst.",
  SignedEdictPlus: "Apply Pyro to 1 enemy in your zone and deal 1 damage to each enemy for each 🔥 on Yanfei's Burst. You may spend 1 energy to target another player's zone instead.",
  FireworkFlareUp: "Deal 2 damage to 1 enemy anywhere. This card costs 0 Action Points if th enemy has Pyro applied.",
  FireworkFlareUpPlus: "Apply Pyro and deal 2 damage to 3 different enemies anywhere.",
  NiwabiFireDance: "This turn: Your next normal attack will apply Pyro to any enemies they target.",
  NiwabiFireDancePlus: "This turn: Your next normal attack will apply Pyro to any enemies they target. Draw 3 cards.",
  RainOfStone: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  RainOfStonePlus: "Apply Geo and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  DominusLapidis: "Give 3 Guard to yourself and 1 other player. Apply Geo to all enemies in your zone. At the start of next turn, apply Geo to all enemies in your zone.",
  DominusLapidisPlus: "Give 3 Guard to yourself and 1 other player. Apply Geo to all enemies in your zone. At the start of next turn, apply Geo to all enemies in your zone.",
};

export const rusDescriptions:Record<string, string>={
  ForeignRockblade: "Наносит 3 урона 1 врагу в вашей зоне.",
  ForeignRockbladePlus: "Накладывает Гео и наносит 3 урона 1 врагу в вашей зоне. Даёт 2 энергии.",
  StarfellSword: "Накладывает Гео и наносит 2 пронзающего урона всем врагам в вашей зоне.",
  StarfellSwordPlus: "Накладывает Гео и наносит 2 пронзающего урона всем врагам в вашей зоне.",
  WeissBladework: "Наносит 2 урона 1 врагу в вашей зоне. Даёт 2 энергии, если на враге есть Гео.",
  WeissBladeworkPlus: "Наносит 3 урона 1 врагу в вашей зоне. Если у вас есть эффект Тектоническая волна, на этом ходе: получите 1 Очко действия и вытяните 1 карту.",
  SolarIsotoma: "Накладывает Гео всем врагам в вашей зоне. В начале следующего хода, накладывает Гео всем врагам в вашей зоне. Вы можете выбросить карту из вашей руки или сброса чтобы вытянуть карту.",
  SolarIsotomaPlus: "Накладывает Гео всем врагам в вашей зоне. В начале следующего хода, накладывает Гео всем врагам в вашей зоне. Вы можете выбросить карту из вашей руки или сброса чтобы вытянуть карту.",
  Sharpshooter: "Наносит 1 пронзающий урон 1 врагу где угодно. Вы можете потратить 1 энергию, чтобы наложить Пиро на этого врага.",
  SharpshooterPlus: "Наносит 1 пронзающий урон 1 врагу где угодно. Наносит 3 урона если у врага нету щитов.",
  ExplosivePuppet: "Выбранный 1 враг, не босс, в вашей зоне не будет атаковать в этом ходу. В начале следующего хода накладывает Пиро и наносит 2 урона всем врагам в вашей зоне.",
  ExplosivePuppetPlus: "Выбранный 1 враг, не босс, в вашей зоне не будет атаковать в этом ходу. В начале следующего хода накладывает Пиро и наносит 2 урона всем врагам в вашей зоне.",
  WhisperOfWater: "Накладывает Гидро и наносит 1 пронзающий урон 1 врагу де угодно. Вытягивает 1 карту.",
  WhisperOfWaterPlus: "Восстанавливает 2 ОЗ себе и 1 другому игроку.",
  LetTheShowBegin: "Накладывает Гидро 1 врагу в вашей зоне. Восстанавливает 1 ОЗ 1 любому игроку. Вы можете потратить 2 энергии, чтобы восстановить 3 ОЗ.",
  LetTheShowBeginPlus: "Накладывает Гидро всем врагам в вашей зоне. На этом ходу: ваши обычные атаки восстанавливают 1 ОЗ 1 любому игроку.",
  Oceanborn: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щитов. Вы можете потратить 1 Очко действия, чтобы моментально повторить этот эффект на этом же враге.",
  OceanbornPlus: "Наносит 2 урона всем врагам в вашей зоне. Наносит 4 урона если вы получали урон на последнем ходу.",
  Tidecaller: "Накладывает Электро to всем врагам в вашей зоне. Даёт 2 защиты.",
  TidecallerPlus: "Накладывает Электро to всем врагам в вашей зоне Даёт 3 защиты и даёт Перегрузку в вашу руку.",
  StrikeOfFortune: "Наносит 2 урона 1 врагу в вашей зоне. Даёт 2 энергии, если на враге есть Пиро.",
  StrikeOfFortunePlus: "Наносит 3 урона 1 врагу в вашей зоне. Если у вас 7 ОЗ или меньше, наносит 1 дополнительный урон и даёт 3 энергии.",
  PassionOverload: "Накладывает Пиро и наносит 2 урона 1 врагу в вашей зоне. Сбрасывает карту сверху колоды. Если это было Горение или карта Беннета, получите 1 урон и нанесите 1 уроне всем врага в вашей зоне. Карта Горение выбрасывается.",
  PassionOverloadPlus: "Накладывает Пиро и наносит 4 урона 1 врагу в вашей зоне. Сбрасывает карту сверху колоды. Если это было Горение или карта Беннета, получите 1 урон и нанесите 1 уроне всем врага в вашей зоне. Карта Горение выбрасывается.",
  Demonbane: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щитов. Вы можете потратить 1 Очко действия, чтобы моментально повторить этот эффект на этом же враге.",
  DemonbanePlus: "Наносит 2 урона всем врагам в вашей зоне. 1 враг с Крио получит 4 урона.",
  LayeredFrost: "Вытягивает 1 карту. На этом ходу ваши обычные атаки будут накладывать Крио.",
  LayeredFrostPlus: "Вытягивает 1 карту. На этом ходу ваши обычные атаки будут накладывать Крио.",
  TemperedSword: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щитов. Вы можете потратить 1 Очко действия, чтобы моментально повторить этот эффект на этом же враге.",
  TemperedSwordPlus: "Уничтожает все щиты 1 врагу в вашей зоне. Наносит 4 урона, если у врага нет щитов.",
  SearingOnslaught: "Накладывает Пиро и наносит 2 урона 1 врагу в вашей зоне. Моментально повторяет этот эффект ещё 2 раза.",
  SearingOnslaughtPlus: "Накладывает Пиро и наносит 2 урона 1 врагу в вашей зоне. Моментально повторяет этот эффект ещё 2 раза.",
  KatzleinStyle: "Наносит 2 пронзающих урона 1 врагу где угодно.",
  KatzleinStylePlus: "Наносит 2 пронзающего урона 1 врагу где угодно. Если у вас есть защита, наносит 5 пронзающего урона.",
  IcyPaws: "Даёт 3 защиты ИЛИ накладывает Крио на всех врагов в вашей зоне. Вы можете выбросить карту Горение из вашей колоды сброса.",
  IcyPawsPlus: "Накладывает Крио на всех врагов в вашей зоне. Даёт 3 защиты. Вы можете выбросить карту Горение из вашей колоды сброса.",
  EdelBladework: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щита. Вы можете потратить 2 энергии, чтобы наложить Крио на этого врага.",
  EdelBladeworkPlus: "Накладывает Крио и наносит 2 урона 1 врагу в вашей зоне. Даёт ❄ Взрыву стихий Эолы.",
  IcetideVortex: "Накладывает Крио 1 врагу в вашей зоне. Either search your deck for a Eula card and add it to your hand or add all Eula cards from your discard into your hand.",
  IcetideVortexPlus: "Накладывает Крио 1 врагу в вашей зоне. Either search your deck for a Eula card and add it to your hand or add all Eula cards from your discard into your hand.",
  BoltsOfDownfall: "Наносит 1 пронзающий урон 1 врагу где угодно. Вы можете потратить 1 энергию, чтобы наложить Электро на этого врага.",
  BoltsOfDownfallPlus: "Наносит 1 пронзающий урон 1 врагу где угодно. If effect of the Nightrider card was triggered This turn: deal 3 piercing damage instead.",
  Nightrider: "Накладывает Электро и наносит 1 пронзающий урон 1 врагу в вашей зоне. В начале следующего хода повторяет эффект.",
  NightriderPlus: "Накладывает Электро и наносит 2 пронзающего урона 1 врагу где угодно. В начале следующего хода повторяет эффект.",
  LiutianArchery: "Наносит 1 пронзающий урон 1 врагу где угодно. Вы можете потратить 1 энергию, чтобы наложить Крио на этого врага.",
  LiutianArcheryPlus: "Наносит 2 урона 1 врагу где угодно. Вы можете потратить 2 энергии, чтобы наложить Крио на этого врага и утроить наносимый урон.",
  TrailOfTheQilin: "Выберете 1 врага в вашей зоне. Он не может атаковать на этом ходу. В начале следующего хода накладывает Крио и наносит 2 урона всем врагам в вашей зоне.",
  TrailOfTheQilinPlus: "Выберете 1 врага в вашей зоне. Он не может атаковать на этом ходу. В начале следующего хода накладывает Крио и наносит 2 урона всем врагам в вашей зоне.",
  SpearOfWangsheng: "Наносит 1 пронзающий урон 1 врагу в вашей зоне. Если у вас 7 ОЗ или меньше, наносит 2 пронзающего урона.",
  SpearOfWangshengPlus: "Получите 1 урон. Нанесите 1 пронзающий урон 1 врагу в вашей зоне. Если у вас 7 ОЗ или меньше, наносит 4 пронзающего урона и замешивает себя обратно в колоду.",
  GuideOfAfterlife: "Получите 1 урон. Получите 1 энергию или вытяните 2 карты. На этом ходу ваши обычные атаки будут накладывать Пиро.",
  GuideOfAfterlifePlus: "Получите 1 урон. Получите 1 энергию или вытяните 2 карты. На этом ходу ваши обычные атаки будут накладывать Пиро.",
  FavoniusBladework: "Наносит 2 урона 1 врагу в вашей зоне. Получите 2 энергии, если на враге есть Анемо.",
  FavoniusBladeworkPlus: "Нанесите 2 урона 1 врагу в вашей зоне и получите 2 энергии. Восстанавливает вам 2 ОЗ.",
  GaleBlade: "Накладывает Анемо и наносит 1 пронзающий урон 1 врагу в вашей зоне. Вы можете поменять местами этого врага с любым другим.",
  GaleBladePlus: "Накладывает Анемо и наносит 1 пронзающий урон 1 врагу в вашей зоне. Вы можете поменять местами этого врага с любым другим",
  CeremonialBladework: "Наносит 3 урона 1 врагу в вашей зоне.",
  CeremonialBladeworkPlus: "Наносит 2 + 1d6 урона 1 врагу в вашей зоне.",
  Frostgnaw: "Наносит Крио всем врагам в вашей зоне. Даёт 1 энергию.",
  FrostgnawPlus: "Наносит Крио всем врагам в вашей зоне. Даёт 2 энергии. Восстанавливает вам 2 ОЗ.",
  GaryuuBladework: "Наносит 3 урона 1 врагу в вашей зоне.",
  GaryuuBladeworkPlus: "Наносит 3 урона 1 врагу в вашей зоне. Если последняя сыгранная карта была Chihayaburu или Рывок, наносит 6 урона.",
  Chihayaburu: "Накладывает Анемо 2 разным врагам где угодно. Вы можете поменять местами этих врагов.",
  ChihayaburuPlus: "Накладывает Анемо на всех врагов в вашей зоне. Вытяните 2 карты.",
  YunlaiSwordsmanship: "Наносит 3 урона 1 врагу в вашей зоне.",
  YunlaiSwordsmanshipPlus: "Накладывает Электро и наносит 3 урона 1 врагу в вашей зоне. Даёт 2 энергии.",
  StellarRestoration: "Накладывает Электро 1 врагу где угодно. You may flip 1 other enemy anywhere facedown, removing any tokens it had, and place this enemy on top of it.",
  StellarRestorationPlus: "Накладывает Электро 3 разным врагам где угодно. Даёт 2 энергии.",
  Kaboom: "Накладывает Пиро и наносит 1 пронзающий урон 1 врагу где угодно. Даёт 1 энергию.",
  KaboomPlus: "Накладывает Пиро и наносит 2 пронзающего урона 1 врагу где угодно. Вы можете потратить 2 энергии, чтобы удвоить этот урон.",
  JumpyDumpty: "Накладывает Пиро и наносит 1 урон 2 разным врагам в вашей зоне. Вы можете вернуть эту карту наверх колоды.",
  JumpyDumptyPlus: "Накладывает Пиро и наносит 1 урон 2 разным врагам в вашей зоне. Вы можете потратить 2 энергии, чтобы повторить этот эффект один раз.",
  LightningTouch: "Накладывает Электро и наносит 1 пронзающий урон 1 врагу где угодно. Вытяните 1 карту.",
  LightningTouchPlus: "Накладывает Электро и наносит 1 пронзающий урон 1 врагу где угодно. Вытяните 1 карту.",
  VioletArc: "Наносит 5 пронзающего урона всем врагам в вашей зоне, если на них есть Электро.",
  VioletArcPlus: "Наносит 5 пронзающего урона всем врагам в вашей зоне, если на них есть Электро.",
  ForeignIronwind: "Наносит 3 урона 1 врагу в вашей зоне.",
  ForeignIronwindPlus: "Накладывает Анемо и наносит 3 урона 1 врагу в вашей зоне. Даёт 2 энергии.",
  PalmVortex: "Deal 2 energy to all enemies in your zone with Hydro, Pyro, Cryo or Electro applied.",
  PalmVortexPlus: "Deal 4 energy to all enemies in your zone with Hydro, Pyro, Cryo or Electro applied.",
  RippleOfFate: "Apply Hydro and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  RippleOfFatePlus: "Draw 2 cards. Gain 2 energy for every Mona card you drew with this effect.",
  MirrorReflections: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Hydro and deal 2 damage to all enemies in your zone.",
  MirrorReflectionsPlus: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Hydro and deal 2 damage to all enemies in your zone.",
  SparklingScatter: "Apply Geo and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  SparklingScatterPlus: "Apply Geo and deal 2 piercing damage to 2 different enemies anywhere.",
  JadeScreen: "Give any 1 player 3 Guard.",
  JadeScreenPlus: "Give yourself and any 1 other player 3 Guard and 1 energy.",
  MaidsBladework: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щитов. Вы можете потратить 1 Очко действия, чтобы моментально повторить этот эффект на этом же враге.",
  MaidsBladeworkPlus: "Вытягивает 3 карты. Даёт 2 Защиты.",
  Breastplate: "Apply Geo to all enemies in your zone. Restore 1 HP to yourself.",
  BreastplatePlus: "Apply Geo to all enemies in your zone. This turn: your normal attacks will restore 1 HP to 1 any player.",
  AncientSwordArt: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Cryo applied.",
  AncientSwordArtPlus: "Deal 2 damage to 1 enemy in your zone and gain 2 energy. Deal 5 damage instead if the enemy has Cryo applied.",
  HeraldOfFrost: "Apply Cryo to 1 enemy anywhere. This turn: the next player to target this enemy restores 2 HP.",
  HeraldOfFrostPlus: "Apply Cryo to 1 enemy anywhere. This turn: the next player to target this enemy restores 3 HP and gains 2 energy.",
  Origin: "Deal 2 damage to 1 enemy in your zone. You may spend 2 energy to gain 1 Action Point to spend this turn.",
  OriginPlus: "Deal 2 damage to 1 enemy in your zone. Deal 5 damage instead if he enemy has Electro applied. Gain 2 energy.",
  BalefulOmen: "Apply Electro to all enemies in your zone. Place a 🟣 on another player's board (max 5). Any time played any Normal Attack card, a player may discard a 🟣 to deal 1 piercing damage to 1 enemy in their zone.",
  BalefulOmenPlus: "Apply Electro to all enemies in your zone. Place 2 🟣 on yours and 1 on another player's board (max 5). Any time played any Normal Attack card, a player may discard a 🟣 to deal 1 piercing damage to 1 enemy in their zone.",
  SteelFang: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if he enemy has no shields. You may spend 1 energy to place a 🟣 on Razor's Burst (max 3).",
  SteelFangPlus: "Destroy 1 shield on 1 enemy in your zone and deal 2 damage to that enemy. You may spend 1 energy to place a 🟣 on Razor's Burst (max 3).",
  ClawAndThunder: "Apply Electro to all enemies in our zone. Place a 🟣 on Razor's Burst (max 3) if it has not been activated yet this turn.",
  ClawAndThunderPlus: "Apply Electro to all enemies in your zone. Place a 🟣 on Razor's Burst (max 3) if it has not been activated yet this turn. You may remove all 🟣 from Razor's Burst to gain 2 energy for each 🟣 removed.",
  SpearOfTheChurch: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  SpearOfTheChurchPlus: "Apply Cryo and deal 3 damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  RavagingConfession: "Deal 1 piercing damage to 1 enemy anywhere. You may take the enemy you damaged and place in in your zone.",
  RavagingConfessionPlus: "Apply Cryo and deal 3 damage to 1 enemy anywhere. You may take the enemy you damaged and place in in your zone.",
  WindSpiritCreation: "Apply Anemo and deal 1 piercing damage to 1 enemy anywhere. Gain 1 energy.",
  WindSpiritCreationPlus: "Apply Anemo and deal 2 piercing damage to 2 different enemies anywhere.",
  AnemoHypostatis: "Apply Anemo to 1 enemy anywhere. You may flip 1 other enemy anywhere facedown, removing any tokens it had, and place this enemy on top of it.",
  AnemoHypostatisPlus: "Apply Anemo to all enemies in your zone. For any reactions this triggers, you may choose to restore 3 HP to to any 1 player instead of gaining a Dash card.",
  CuttingTorrent: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Hydro to that enemy.",
  CuttingTorrentPlus: "Deal 1 piercing damage to 1 enemy anywhere. Deal 3 damage instead if the enemy has Hydro applied.",
  RagingTide: "Draw 3 cards. You may discard up to 3 cards to apply Hydro to 1 enemy in your zone per card.",
  RagingTidePlus: "Draw 3 cards. You may discard up to 3 cards to apply Hydro to 1 enemy in your zone per card.",
  DivineArchery: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Anemo to that enemy.",
  DivineArcheryPlus: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to deal 3 piercing damage instead.",
  SkywardSonnet: "Apply Anemo to all enemies in your zone. This turn: your next Normal attack has any damage dealt increased by 1.",
  SkywardSonnetPlus: "Apply Anemo to all enemies in your zone and any one player's zone. This turn: your next Normal attack has any damage dealt increased by 2.",
  DoughFu: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to deal 1 piercing damage to a different enemy anywhere.",
  DoughFuPlus: "Apply Pyro and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 action point.",
  GuobaFire: "Apply Pyro and deal 2 damage to all enemies in your zone. At the start next turn, apply Pyro and deal 2 damage to all enemies in your zone.",
  GuobaFirePlus: "Apply Pyro and deal 2 damage to all enemies in your zone. At the start next turn, apply Pyro and deal 2 damage to all enemies in your zone.",
  WhirlwindThrust: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  WhirlwindThrustPlus: "Apply Anemo and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  LemniscaticWind: "Apply Anemo and deal 1 piercing damage to 1 enemy in your zone. You may return this card to your hand after playing it.",
  LemniscaticWindPlus: "Apply Anemo and deal 2 piercing damage to 1 enemy in your zone. if the last card you played was Dash, deal 5 piercing damage instead.",
  GuhuaStyle: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Hydro applied.",
  GuhuaStylePlus: "Deal 3 damage to 1 enemy in your zone. Deal 5 damage instead if the enemy has Hydro applied.",
  FatalRainscreen: "Gain 4 Guard and apply Hydro to 1 enemy in your zone. Restore 2 HP to 1 any player.",
  FatalRainscreenPlus: "Gain 4 Guard and apply Hydro to 1 enemy in your zone. Restore 2 HP to 1 any player.",
  DanceOfFire: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щитов. Вы можете потратить 1 Очко действия, чтобы моментально повторить этот эффект на этом же враге.",
  DanceOfFirePlus: "Deal 1 damage to all enemies in your zone. If you have Guard, deal 3 damage instead.",
  SweepingFervor: "Даёт 3 защиты. Накладывает Пиро всем врагам в вашей зоне.",
  SweepingFervorPlus: "Даёт 3 защиты. Накладывает Пиро всем врагам в вашей зоне.",
  SealOfApproval: "Накладывает Пио и наносит 1 пронзающий урон 1 врагу где угодно.",
  SealOfApprovalPlus: "Apply Pyro and deal 2 piercing damage to 1 enemy anywhere. Draw 1 card, if there are any 🔥 on Yanfei's Burst. Draw 2 cards instead if there are 3+ 🔥.",
  SignedEdict: "Apply Pyro to 1 enemy in your zone and deal 1 damage to each enemy for each 🔥 on Yanfei's Burst.",
  SignedEdictPlus: "Apply Pyro to 1 enemy in your zone and deal 1 damage to each enemy for each 🔥 on Yanfei's Burst. You may spend 1 energy to target another player's zone instead.",
  FireworkFlareUp: "Deal 2 damage to 1 enemy anywhere. This card costs 0 Action Points if th enemy has Pyro applied.",
  FireworkFlareUpPlus: "Накладывает Пиро и наносит 2 урона 3 разным врагам где угодно.",
  NiwabiFireDance: "This turn: Your next normal attack will apply Pyro to any enemies they target.",
  NiwabiFireDancePlus: "This turn: Your next normal attack will apply Pyro to any enemies they target. Draw 3 cards.",
  RainOfStone: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  RainOfStonePlus: "Apply Geo and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  DominusLapidis: "Даёт 3 защиты вам и 1 другому игроку. Накладывает Гео всем врагам в вашей зоне. В начале следующего хода накладывает Гео всем врагам в вашей зоне.",
  DominusLapidisPlus: "Даёт 3 защиты вам и 1 другому игроку. Накладывает Гео всем врагам в вашей зоне. В начале следующего хода накладывает Гео всем врагам в вашей зоне.",
}
