import { ECard } from "../../types/enums";

export const engDescriptions: Record<ECard, string> = {
  [ECard.ForeignRockblade]: "Deal 3 damage to 1 enemy in your zone.",
  [ECard.ForeignRockbladePlus]: "Apply Geo and deal 3 damage to 1 enemy in your zone. Gain 2 energy.",
  [ECard.StarfellSword]: "Apply Geo and then deal 2 piercing damage to all enemies in your zone.",
  [ECard.StarfellSwordPlus]: "Apply Geo and then deal 2 piercing damage to all enemies in your zone.",
  [ECard.WeissBladework]: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Geo applied.",
  [ECard.WeissBladeworkPlus]: "Deal 3 damage to 1 enemy in your zone. If effect of the Abiogenesis: Solar Isotoma card was triggered This turn: gain 1 Action Point to spend to spend this turn and draw 1 card.",
  [ECard.SolarIsotoma]: "Apply Geo to all enemies in your zone. At the start next turn, apply Geo to all enemies in your zone. You may trash a card from you hand or discard to draw a card.",
  [ECard.SolarIsotomaPlus]: "Apply Geo to all enemies in your zone. At the start next turn, apply Geo to all enemies in your zone. You may trash a card from you hand or discard to draw a card.",
  [ECard.Sharpshooter]: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Pyro to that enemy.",
  [ECard.SharpshooterPlus]: "Deal 1 piercing damage to 1 enemy anywhere. Deal 3 damage instead if the enemy had no shields.",
  [ECard.ExplosivePuppet]: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Pyro and deal 2 damage to all enemies in your zone.",
  [ECard.ExplosivePuppetPlus]: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Pyro and deal 2 damage to all enemies in your zone.",
  [ECard.WhisperOfWater]: "Apply Hydro and deal 1 piercing damage to 1 enemy to anywhere. Draw 1 card.",
  [ECard.WhisperOfWaterPlus]: "Restore 2 HP to yourself and 1 other player.",
  [ECard.LetTheShowBegin]: "Apply Hydro to 1 enemy in your zone. Restore 1 HP to any 1 player. You may spend 2 energy to restore 3 HP instead.",
  [ECard.LetTheShowBeginPlus]: "Apply Hydro to all enemies in your zone. This Turn: your normal attacks will restore 1 HP to 1 random player.",
  [ECard.Oceanborn]: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  [ECard.OceanbornPlus]: "Deal 2 damage to all enemies in your zone. Deal 4 damage instead if you took damage last turn.",
  [ECard.Tidecaller]: "Apply Electro to all enemies in your zone. Gain 2 Guard.",
  [ECard.TidecallerPlus]: "Apply Electro to all enemies in your zone. Gain 3 Guard and add an Overheat card to your hand.",
  [ECard.StrikeOfFortune]: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Pyro applied.",
  [ECard.StrikeOfFortunePlus]: "Deal 3 damage to 1 enemy in your zone. If you have 7 or less HP, deal 1 additional damage and gain 3 energy.",
  [ECard.PassionOverload]: "Apply Pyro and deal 2 damage to 1 enemy in your zone. Discard the top card of your deck. If it was a Burn or Bennett card, take 1 damage and deal 1 damage to all enemies in your zone. Trash Burn cards discarded this way.",
  [ECard.PassionOverloadPlus]: "Apply Pyro and deal 4 damage to 1 enemy in your zone. Discard the top card of your deck. If it was a Burn or Bennett card, take 1 damage and deal 1 damage to all enemies in your zone. Trash Burn cards discarded this way.",
  [ECard.Demonbane]: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  [ECard.DemonbanePlus]: "Deal 2 damage to all enemies in your zone. 1 enemy with Cryo applied takes 4 damage instead.",
  [ECard.LayeredFrost]: "Draw 1 card. This turn: your normal attacks will apply Cryo to any enemies they target.",
  [ECard.LayeredFrostPlus]: "Draw 1 card. This turn: your normal attacks will apply Cryo to any enemies they target.",
  [ECard.TemperedSword]: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  [ECard.TemperedSwordPlus]: "Destroy all shields to 1 enemy in your zone. Deal 4 damage instead if the enemy has no shields.",
  [ECard.SearingOnslaught]: "Apply Pyro and deal 2 damage to 1 enemy in your zone. Immediately repeat this effect 2 more times.",
  [ECard.SearingOnslaughtPlus]: "Apply Pyro and deal 2 damage to 1 enemy in your zone. Immediately repeat this effect 2 more times.",
  [ECard.KatzleinStyle]: "Deal 2 piercing damage to 1 enemy anywhere.",
  [ECard.KatzleinStylePlus]: "Deal 2 piercing damage to 1 enemy anywhere. If you have any Guard, deal 5 piercing damage instead.",
  [ECard.IcyPaws]: "Either gain 3 Guard OR apply Cryo to all enemies in your zone. Trash a Burn card in your discard.",
  [ECard.IcyPawsPlus]: "Apply Cryo to all enemies in your zone. Gain 3 Guard. Trash a Burn cards in your discard.",
  [ECard.EdelBladework]: "Destroy 1 shield to 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 2 energy to apply Cryo to this enemy.",
  [ECard.EdelBladeworkPlus]: "Apply Cryo and deal 2 damage to 1 enemy in your zone. Place a ❄ to Eula's Burst.",
  [ECard.IcetideVortex]: "Apply Cryo to 1 enemy in your zone. Either search your deck for a Eula card and add it to your hand or add all Eula cards from your discard into your hand.",
  [ECard.IcetideVortexPlus]: "Apply Cryo to 1 enemy in your zone. Either search your deck for a Eula card and add it to your hand or add all Eula cards from your discard into your hand.",
  [ECard.BoltsOfDownfall]: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Electro to this enemy.",
  [ECard.BoltsOfDownfallPlus]: "Deal 1 piercing damage to 1 enemy anywhere. If effect of the Nightrider card was triggered This turn on this enemy: deal 3 piercing damage instead.",
  [ECard.Nightrider]: "Apply Electro and deal 1 piercing damage to 1 enemy in your zone. At the start next turn repeat this effect.",
  [ECard.NightriderPlus]: "Apply Electro and deal 2 piercing damage to 1 enemy anywhere. At the start next turn repeat this effect.",
  [ECard.LiutianArchery]: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Cryo to this enemy.",
  [ECard.LiutianArcheryPlus]: "Deal 2 damage to 1 enemy anywhere. You may spend 2 energy to apply Cryo to this enemy and triple the damage dealt.",
  [ECard.TrailOfTheQilin]: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Cryo and deal 2 damage to all enemies in your zone.",
  [ECard.TrailOfTheQilinPlus]: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Cryo and deal 2 damage to all enemies in your zone.",
  [ECard.SpearOfWangsheng]: "Deal 1 piercing damage to 1 enemy in your zone. If you had 7 or less HP, deal 2 piercing damage instead.",
  [ECard.SpearOfWangshengPlus]: "Take 1 damage. Deal 1 piercing damage to 1 enemy in your zone. If you had 7 or less HP, deal 4 piercing damage instead and shuffle this back into your deck.",
  [ECard.GuideOfAfterlife]: "Take 1 damage. Either gain 1 energy or draw 2 cards. This turn: your Normal Attacks will apply Pyro to any enemies they target.",
  [ECard.GuideOfAfterlifePlus]: "Take 1 damage. Either gain 1 energy or draw 2 cards. This turn: your Normal Attacks will apply Pyro to any enemies they target.",
  [ECard.FavoniusBladework]: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Anemo applied.",
  [ECard.FavoniusBladeworkPlus]: "Deal 2 damage to 1 enemy in your zone and gain 2 energy. Restore 2 HP to yourself.",
  [ECard.GaleBlade]: "Apply Anemo and deal 1 piercing damage to 1 enemy in your zone. You may swap this enemy with any other faceup enemy.",
  [ECard.GaleBladePlus]: "Apply Anemo and deal 1 piercing damage to 1 enemy in your zone. You may swap this enemy with any other faceup enemy.",
  [ECard.CeremonialBladework]: "Deal 3 damage to 1 enemy in your zone.",
  [ECard.CeremonialBladeworkPlus]: "Deal 2 plus 1d6 damage to 1 enemy in your zone.",
  [ECard.Frostgnaw]: "Apply Cryo to all enemies in your zone. Gain 1 energy.",
  [ECard.FrostgnawPlus]: "Apply Cryo to all enemies in your zone. Gain 2 energy. Restore 2 HP to yourself.",
  [ECard.GaryuuBladework]: "Deal 3 damage to 1 enemy in your zone.",
  [ECard.GaryuuBladeworkPlus]: "Deal 3 damage to 1 enemy in your zone. If the last card you played was Chihayaburu or Dash, deal 6 damage instead.",
  [ECard.Chihayaburu]: "Apply Anemo to 2 different enemies anywhere. You may swap these 2 enemies.",
  [ECard.ChihayaburuPlus]: "Apply Anemo to all enemies in your zone. Draw 2 cards.",
  [ECard.YunlaiSwordsmanship]: "Deal 3 damage to 1 enemy in your zone.",
  [ECard.YunlaiSwordsmanshipPlus]: "Apply Electro and deal 3 damage to 1 enemy in your zone. Gain 2 energy.",
  [ECard.StellarRestoration]: "Apply Electro to 1 enemy anywhere. You may flip 1 other enemy anywhere facedown, removing any tokens it had, and place this enemy on top of it.",
  [ECard.StellarRestorationPlus]: "Apply Electro to up to 3 different enemies anywhere. Gain 2 energy.",
  [ECard.Kaboom]: "Apply Pyro and deal 1 piercing damage to 1 enemy anywhere. Gain 1 energy.",
  [ECard.KaboomPlus]: "Apply Pyro and deal 2 piercing damage to 1 enemy anywhere. You may spend 2 energy to double this damage.",
  [ECard.JumpyDumpty]: "Apply Pyro and deal 1 damage to up to 2 different enemies in your zone. You may return this card to top of your deck after playing it.",
  [ECard.JumpyDumptyPlus]: "Apply Pyro and deal 1 damage to up to 2 different enemies in your zone. You may spend 2 energy to immediately repeat this effect once.",
  [ECard.LightningTouch]: "Apply Electro and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  [ECard.LightningTouchPlus]: "Apply Electro and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  [ECard.VioletArc]: "Deal 5 piercing damage to all enemies in your zone with Electro applied.",
  [ECard.VioletArcPlus]: "Deal 5 piercing damage to all enemies in your zone with Electro applied.",
  [ECard.ForeignIronwind]: "Deal 3 damage to 1 enemy in your zone.",
  [ECard.ForeignIronwindPlus]: "Apply Anemo and deal 3 damage to 1 enemy in your zone. Gain 2 energy.",
  [ECard.PalmVortex]: "Deal 2 damage to all enemies in your zone with Hydro, Pyro, Cryo or Electro applied.",
  [ECard.PalmVortexPlus]: "Deal 4 damage to all enemies in your zone with Hydro, Pyro, Cryo or Electro applied.",
  [ECard.RippleOfFate]: "Apply Hydro and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  [ECard.RippleOfFatePlus]: "Draw 2 cards. Gain 2 energy for every Mona card you drew with this effect.",
  [ECard.MirrorReflections]: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Hydro and deal 2 damage to all enemies in your zone.",
  [ECard.MirrorReflectionsPlus]: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Hydro and deal 2 damage to all enemies in your zone.",
  [ECard.SparklingScatter]: "Apply Geo and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  [ECard.SparklingScatterPlus]: "Apply Geo and deal 2 piercing damage to 2 different enemies anywhere.",
  [ECard.JadeScreen]: "Give any 1 player 3 Guard.",
  [ECard.JadeScreenPlus]: "Give yourself and any 1 other player 3 Guard and 1 energy.",
  [ECard.MaidsBladework]: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  [ECard.MaidsBladeworkPlus]: "Draw 3 cards. Gain 2 Guard.",
  [ECard.Breastplate]: "Apply Geo to all enemies in your zone. Restore 1 HP to yourself.",
  [ECard.BreastplatePlus]: "Apply Geo to all enemies in your zone. This turn: your normal attacks will restore 1 HP to 1 any player.",
  [ECard.AncientSwordArt]: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Cryo applied.",
  [ECard.AncientSwordArtPlus]: "Deal 2 damage to 1 enemy in your zone and gain 2 energy. Deal 5 damage instead if the enemy has Cryo applied.",
  [ECard.HeraldOfFrost]: "Apply Cryo to 1 enemy anywhere. This turn: the next player to target this enemy restores 2 HP.",
  [ECard.HeraldOfFrostPlus]: "Apply Cryo to 1 enemy anywhere. This turn: the next player to target this enemy restores 3 HP and gains 2 energy.",
  [ECard.Origin]: "Deal 2 damage to 1 enemy in your zone. You may spend 2 energy to gain 1 Action Point to spend this turn.",
  [ECard.OriginPlus]: "Deal 2 damage to 1 enemy in your zone. Deal 5 damage instead if the enemy has Electro applied. Gain 2 energy.",
  [ECard.BalefulOmen]: "Apply Electro to all enemies in your zone. Place a 🟣 on another player's board (max 5). Any time played any Normal Attack card, a player may discard a 🟣 to deal 1 piercing damage to 1 enemy in their zone.",
  [ECard.BalefulOmenPlus]: "Apply Electro to all enemies in your zone. Place 2 🟣 on yours and 1 on another player's board (max 5). Any time played any Normal Attack card, a player may discard a 🟣 to deal 1 piercing damage to 1 enemy in their zone.",
  [ECard.SteelFang]: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 energy to place a 🟣 on Razor's Burst (max 3).",
  [ECard.SteelFangPlus]: "Destroy 1 shield on 1 enemy in your zone and deal 2 damage to that enemy. You may spend 1 energy to place a 🟣 on Razor's Burst (max 3).",
  [ECard.ClawAndThunder]: "Apply Electro to all enemies in our zone. Place a 🟣 on Razor's Burst (max 3) if it has not been activated yet this turn.",
  [ECard.ClawAndThunderPlus]: "Apply Electro to all enemies in your zone. Place a 🟣 on Razor's Burst (max 3) if it has not been activated yet this turn. You may remove all 🟣 from Razor's Burst to gain 2 energy for each 🟣 removed.",
  [ECard.SpearOfTheChurch]: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  [ECard.SpearOfTheChurchPlus]: "Apply Cryo and deal 3 damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  [ECard.RavagingConfession]: "Apply Cryo to 1 enemy in any player's zone. Then deal 1 damage to all enemies in that enemy's zone.",
  [ECard.RavagingConfessionPlus]: "Apply Cryo to 1 enemy in any player's zone. Then deal 3 damage to all enemies in that enemy's zone. If it defeats enemy, gain 2 energy.",
  [ECard.WindSpiritCreation]: "Apply Anemo and deal 1 piercing damage to 1 enemy anywhere. Gain 1 energy.",
  [ECard.WindSpiritCreationPlus]: "Apply Anemo and deal 2 piercing damage to 2 different enemies anywhere.",
  [ECard.AnemoHypostatis]: "Apply Anemo to 1 enemy anywhere. You may flip 1 other enemy anywhere facedown, removing any tokens it had, and place this enemy on top of it.",
  [ECard.AnemoHypostatisPlus]: "Apply Anemo to all enemies in your zone. For any reactions this triggers, you may choose to restore 3 HP to to any 1 player instead of gaining a Dash card.",
  [ECard.CuttingTorrent]: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Hydro to that enemy.",
  [ECard.CuttingTorrentPlus]: "Deal 1 piercing damage to 1 enemy anywhere. Deal 3 damage instead if the enemy has Hydro applied.",
  [ECard.RagingTide]: "Draw 3 cards. You may discard up to 3 cards to apply Hydro to 1 enemy in your zone per card.",
  [ECard.RagingTidePlus]: "Draw 3 cards. You may discard up to 3 cards to apply Hydro to 1 enemy in your zone per card.",
  [ECard.DivineArchery]: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Anemo to that enemy.",
  [ECard.DivineArcheryPlus]: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to deal 3 piercing damage instead.",
  [ECard.SkywardSonnet]: "Apply Anemo to all enemies in your zone. This turn: your next Normal attack has any damage dealt increased by 1.",
  [ECard.SkywardSonnetPlus]: "Apply Anemo to all enemies in your zone and any one player's zone. This turn: your next Normal attack has any damage dealt increased by 2.",
  [ECard.DoughFu]: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  [ECard.DoughFuPlus]: "Apply Pyro and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point.",
  [ECard.GuobaFire]: "Apply Pyro and deal 2 damage to all enemies in your zone. At the start next turn, apply Pyro and deal 2 damage to all enemies in your zone.",
  [ECard.GuobaFirePlus]: "Apply Pyro and deal 2 damage to all enemies in your zone. At the start next turn, apply Pyro and deal 2 damage to all enemies in your zone.",
  [ECard.WhirlwindThrust]: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  [ECard.WhirlwindThrustPlus]: "Apply Anemo and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  [ECard.LemniscaticWind]: "Apply Anemo and deal 1 piercing damage to 1 enemy in your zone. You may return this card to your hand after playing it.",
  [ECard.LemniscaticWindPlus]: "Apply Anemo and deal 2 piercing damage to 1 enemy in your zone. if the last card you played was Dash, deal 5 piercing damage instead.",
  [ECard.GuhuaStyle]: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Hydro applied.",
  [ECard.GuhuaStylePlus]: "Deal 3 damage to 1 enemy in your zone. Deal 5 damage instead if the enemy has Hydro applied.",
  [ECard.FatalRainscreen]: "Gain 4 Guard and apply Hydro to 1 enemy in your zone. Restore 2 HP to 1 any player.",
  [ECard.FatalRainscreenPlus]: "Gain 4 Guard and apply Hydro to 1 enemy in your zone. Restore 2 HP to 1 any player.",
  [ECard.DanceOfFire]: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  [ECard.DanceOfFirePlus]: "Deal 1 damage to all enemies in your zone. If you have Guard, deal 3 damage instead.",
  [ECard.SweepingFervor]: "Gain 3 Guard. Apply Pyro to all enemies in your zone.",
  [ECard.SweepingFervorPlus]: "Gain 3 Guard. Apply Pyro to all enemies in your zone.",
  [ECard.SealOfApproval]: "Apply Pyro and deal 1 piercing damage to 1 enemy anywhere.",
  [ECard.SealOfApprovalPlus]: "Apply Pyro and deal 2 piercing damage to 1 enemy anywhere. Draw 1 card, if there are any 🔥 on Yanfei's Burst. Draw 2 cards instead if there are 3+ 🔥.",
  [ECard.SignedEdict]: "Apply Pyro to 1 enemy in your zone and deal 1 damage to each enemy for each 🔥 on Yanfei's Burst.",
  [ECard.SignedEdictPlus]: "Apply Pyro to 1 enemy in your zone and deal 1 damage to each enemy for each 🔥 on Yanfei's Burst. You may spend 1 energy to target another player's zone instead.",
  [ECard.FireworkFlareUp]: "Deal 2 damage to 1 enemy anywhere. This card costs 0 Action Points if th enemy has Pyro applied.",
  [ECard.FireworkFlareUpPlus]: "Apply Pyro and deal 2 damage to 3 different enemies anywhere.",
  [ECard.NiwabiFireDance]: "This turn: Your next normal attack will apply Pyro to any enemies they target.",
  [ECard.NiwabiFireDancePlus]: "This turn: Your next normal attack will apply Pyro to any enemies they target. Draw 3 cards.",
  [ECard.RainOfStone]: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  [ECard.RainOfStonePlus]: "Apply Geo and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  [ECard.DominusLapidis]: "Give 3 Guard to yourself and 1 other player. Apply Geo to all enemies in your zone. At the start of next turn, apply Geo to all enemies in your zone.",
  [ECard.DominusLapidisPlus]: "Give 3 Guard to yourself and 1 other player. Apply Geo to all enemies in your zone. At the start of next turn, apply Geo to all enemies in your zone.",
  [ECard.Dash]: "Trash this card, then draw 2 cards. You gain 1 additional Action Point to spend this turn.",
  [ECard.Overheat]: "Trash this card, then draw 2 cards. The next time you deal damage this turn, increase the damage dealt by 1. If this damage defeats the enemy, gain 2 Energy.",
  [ECard.Burn]: "Take 1 Damage when you draw this card. Take 2 Damage instead if this is the second or later Burn card you've drawn this turn. Trash all Burn cards in your hand when Hydro or Cryo is applied to an enemy in your zone.",
  [ECard.Freeze]: "While this is in your hand, you cannot gain nor spend any Energy. You may trash all Freeze cards in your hand by spending 1 Action Point.",
};

export const rusDescriptions: Record<ECard, string> = {
  [ECard.ForeignRockblade]: "Наносит 3 урона 1 врагу в вашей зоне.",
  [ECard.ForeignRockbladePlus]: "Накладывает Гео и наносит 3 урона 1 врагу в вашей зоне. Даёт 2 энергии.",
  [ECard.StarfellSword]: "Накладывает Гео и наносит 2 пронзающего урона всем врагам в вашей зоне.",
  [ECard.StarfellSwordPlus]: "Накладывает Гео и наносит 2 пронзающего урона всем врагам в вашей зоне.",
  [ECard.WeissBladework]: "Наносит 2 урона 1 врагу в вашей зоне. Даёт 2 энергии, если на враге есть Гео.",
  [ECard.WeissBladeworkPlus]: "Наносит 3 урона 1 врагу в вашей зоне. Если у вас есть эффект Тектоническая волна, на этом ходе: получите 1 Очко действия и вытяните 1 карту.",
  [ECard.SolarIsotoma]: "Накладывает Гео всем врагам в вашей зоне. В начале следующего хода, накладывает Гео всем врагам в вашей зоне. Вы можете выбросить карту из вашей руки или сброса чтобы вытянуть карту.",
  [ECard.SolarIsotomaPlus]: "Накладывает Гео всем врагам в вашей зоне. В начале следующего хода, накладывает Гео всем врагам в вашей зоне. Вы можете выбросить карту из вашей руки или сброса чтобы вытянуть карту.",
  [ECard.Sharpshooter]: "Наносит 1 пронзающий урон 1 врагу где угодно. Вы можете потратить 1 энергию, чтобы наложить Пиро на этого врага.",
  [ECard.SharpshooterPlus]: "Наносит 1 пронзающий урон 1 врагу где угодно. Наносит 3 урона если у врага нету щитов.",
  [ECard.ExplosivePuppet]: "Выбранный 1 враг, не босс, в вашей зоне не будет атаковать в этом ходу. В начале следующего хода накладывает Пиро и наносит 2 урона всем врагам в вашей зоне.",
  [ECard.ExplosivePuppetPlus]: "Выбранный 1 враг, не босс, в вашей зоне не будет атаковать в этом ходу. В начале следующего хода накладывает Пиро и наносит 2 урона всем врагам в вашей зоне.",
  [ECard.WhisperOfWater]: "Накладывает Гидро и наносит 1 пронзающий урон 1 врагу де угодно. Вытягивает 1 карту.",
  [ECard.WhisperOfWaterPlus]: "Восстанавливает 2 ОЗ себе и 1 другому игроку.",
  [ECard.LetTheShowBegin]: "Накладывает Гидро 1 врагу в вашей зоне. Восстанавливает 1 ОЗ 1 любому игроку. Вы можете потратить 2 энергии, чтобы восстановить 3 ОЗ.",
  [ECard.LetTheShowBeginPlus]: "Накладывает Гидро всем врагам в вашей зоне. На этом ходу: ваши обычные атаки восстанавливают 1 ОЗ 1 случайному игроку.",
  [ECard.Oceanborn]: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щитов. Вы можете потратить 1 Очко действия, чтобы моментально повторить этот эффект на этом же враге.",
  [ECard.OceanbornPlus]: "Наносит 2 урона всем врагам в вашей зоне. Наносит 4 урона если вы получали урон на последнем ходу.",
  [ECard.Tidecaller]: "Накладывает Электро всем врагам в вашей зоне. Даёт 2 защиты.",
  [ECard.TidecallerPlus]: "Накладывает Электро всем врагам в вашей зоне Даёт 3 защиты и даёт Перегрузку в вашу руку.",
  [ECard.StrikeOfFortune]: "Наносит 2 урона 1 врагу в вашей зоне. Даёт 2 энергии, если на враге есть Пиро.",
  [ECard.StrikeOfFortunePlus]: "Наносит 3 урона 1 врагу в вашей зоне. Если у вас 7 ОЗ или меньше, наносит 1 дополнительный урон и даёт 3 энергии.",
  [ECard.PassionOverload]: "Накладывает Пиро и наносит 2 урона 1 врагу в вашей зоне. Сбрасывает карту сверху колоды. Если это было Горение или карта Беннета, получите 1 урон и нанесите 1 уроне всем врага в вашей зоне. Карта Горение удаляется.",
  [ECard.PassionOverloadPlus]: "Накладывает Пиро и наносит 4 урона 1 врагу в вашей зоне. Сбрасывает карту сверху колоды. Если это было Горение или карта Беннета, получите 1 урон и нанесите 1 уроне всем врага в вашей зоне. Карта Горение удаляется.",
  [ECard.Demonbane]: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щитов. Вы можете потратить 1 Очко действия, чтобы моментально повторить этот эффект на этом же враге.",
  [ECard.DemonbanePlus]: "Наносит 2 урона всем врагам в вашей зоне. Или 1 враг с Крио получит 4 урона.",
  [ECard.LayeredFrost]: "Вытягивает 1 карту. На этом ходу ваши обычные атаки будут накладывать Крио.",
  [ECard.LayeredFrostPlus]: "Вытягивает 1 карту. На этом ходу ваши обычные атаки будут накладывать Крио.",
  [ECard.TemperedSword]: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щитов. Вы можете потратить 1 Очко действия, чтобы моментально повторить этот эффект на этом же враге.",
  [ECard.TemperedSwordPlus]: "Уничтожает все щиты 1 врагу в вашей зоне. Наносит 4 урона, если у врага нет щитов.",
  [ECard.SearingOnslaught]: "Накладывает Пиро и наносит 2 урона 1 врагу в вашей зоне. Моментально повторяет этот эффект ещё 2 раза.",
  [ECard.SearingOnslaughtPlus]: "Накладывает Пиро и наносит 2 урона 1 врагу в вашей зоне. Моментально повторяет этот эффект ещё 2 раза.",
  [ECard.KatzleinStyle]: "Наносит 2 пронзающих урона 1 врагу где угодно.",
  [ECard.KatzleinStylePlus]: "Наносит 2 пронзающего урона 1 врагу где угодно. Если у вас есть защита, наносит 5 пронзающего урона.",
  [ECard.IcyPaws]: "Даёт 3 защиты ИЛИ накладывает Крио на всех врагов в вашей зоне и выбрасывает карту Горение из вашей колоды сброса.",
  [ECard.IcyPawsPlus]: "Накладывает Крио на всех врагов в вашей зоне. Даёт 3 защиты. Выбрасывает карту Горение из вашей колоды сброса.",
  [ECard.EdelBladework]: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щита. Вы можете потратить 2 энергии, чтобы наложить Крио на этого врага.",
  [ECard.EdelBladeworkPlus]: "Накладывает Крио и наносит 2 урона 1 врагу в вашей зоне. Даёт ❄ Взрыву стихий Эолы.",
  [ECard.IcetideVortex]: "Накладывает Крио 1 врагу в вашей зоне. Вы можете вместо этого найти в колоде карту Эолы и добавить её в свою руку. Если карты нету, добавить все карты Эолы из колоды сброса.",
  [ECard.IcetideVortexPlus]: "Накладывает Крио 1 врагу в вашей зоне. Вы можете вместо этого найти в колоде карту Эолы и добавить её в свою руку. Если карты нету, добавить все карты Эолы из колоды сброса.",
  [ECard.BoltsOfDownfall]: "Наносит 1 пронзающий урон 1 врагу где угодно. Вы можете потратить 1 энергию, чтобы наложить Электро на этого врага.",
  [ECard.BoltsOfDownfallPlus]: "Наносит 1 пронзающий урон 1 врагу где угодно. Если эффект 'Тень расправленных крыльев' сработал на этом ходу на этом враге, наносит 3 пронзающего урона.",
  [ECard.Nightrider]: "Накладывает Электро и наносит 1 пронзающий урон 1 врагу в вашей зоне. В начале следующего хода повторяет эффект.",
  [ECard.NightriderPlus]: "Накладывает Электро и наносит 2 пронзающего урона 1 врагу где угодно. В начале следующего хода повторяет эффект.",
  [ECard.LiutianArchery]: "Наносит 1 пронзающий урон 1 врагу где угодно. Вы можете потратить 1 энергию, чтобы наложить Крио на этого врага.",
  [ECard.LiutianArcheryPlus]: "Наносит 2 урона 1 врагу где угодно. Вы можете потратить 2 энергии, чтобы наложить Крио на этого врага и утроить наносимый урон.",
  [ECard.TrailOfTheQilin]: "Выберете 1 врага в вашей зоне. Он не может атаковать на этом ходу. В начале следующего хода накладывает Крио и наносит 2 урона всем врагам в вашей зоне.",
  [ECard.TrailOfTheQilinPlus]: "Выберете 1 врага в вашей зоне. Он не может атаковать на этом ходу. В начале следующего хода накладывает Крио и наносит 2 урона всем врагам в вашей зоне.",
  [ECard.SpearOfWangsheng]: "Наносит 1 пронзающий урон 1 врагу в вашей зоне. Если у вас 7 ОЗ или меньше, наносит 2 пронзающего урона.",
  [ECard.SpearOfWangshengPlus]: "Получите 1 урон. Нанесите 1 пронзающий урон 1 врагу в вашей зоне. Если у вас 7 ОЗ или меньше, наносит 4 пронзающего урона и замешивает себя обратно в колоду.",
  [ECard.GuideOfAfterlife]: "Получите 1 урон. Получите 1 энергию или вытяните 2 карты. На этом ходу ваши обычные атаки будут накладывать Пиро.",
  [ECard.GuideOfAfterlifePlus]: "Получите 1 урон. Получите 1 энергию или вытяните 2 карты. На этом ходу ваши обычные атаки будут накладывать Пиро.",
  [ECard.FavoniusBladework]: "Наносит 2 урона 1 врагу в вашей зоне. Получите 2 энергии, если на враге есть Анемо.",
  [ECard.FavoniusBladeworkPlus]: "Нанесите 2 урона 1 врагу в вашей зоне и получите 2 энергии. Восстанавливает вам 2 ОЗ.",
  [ECard.GaleBlade]: "Накладывает Анемо и наносит 1 пронзающий урон 1 врагу в вашей зоне. Вы можете поменять местами этого врага с любым другим.",
  [ECard.GaleBladePlus]: "Накладывает Анемо и наносит 1 пронзающий урон 1 врагу в вашей зоне. Вы можете поменять местами этого врага с любым другим",
  [ECard.CeremonialBladework]: "Наносит 3 урона 1 врагу в вашей зоне.",
  [ECard.CeremonialBladeworkPlus]: "Наносит 2 + 1d6 урона 1 врагу в вашей зоне.",
  [ECard.Frostgnaw]: "Наносит Крио всем врагам в вашей зоне. Даёт 1 энергию.",
  [ECard.FrostgnawPlus]: "Наносит Крио всем врагам в вашей зоне. Даёт 2 энергии. Восстанавливает вам 2 ОЗ.",
  [ECard.GaryuuBladework]: "Наносит 3 урона 1 врагу в вашей зоне.",
  [ECard.GaryuuBladeworkPlus]: "Наносит 3 урона 1 врагу в вашей зоне. Если последняя сыгранная карта была Chihayaburu или Рывок, наносит 6 урона.",
  [ECard.Chihayaburu]: "Накладывает Анемо 2 разным врагам где угодно. Вы можете поменять местами этих врагов.",
  [ECard.ChihayaburuPlus]: "Накладывает Анемо на всех врагов в вашей зоне. Вытяните 2 карты.",
  [ECard.YunlaiSwordsmanship]: "Наносит 3 урона 1 врагу в вашей зоне.",
  [ECard.YunlaiSwordsmanshipPlus]: "Накладывает Электро и наносит 3 урона 1 врагу в вашей зоне. Даёт 2 энергии.",
  [ECard.StellarRestoration]: "Накладывает Электро 1 врагу где угодно. Вы можете перевернуть 1 другого врага где угодно лицом вниз, удалив с него все метки, и разместить его сверху первого.",
  [ECard.StellarRestorationPlus]: "Накладывает Электро 3 разным врагам где угодно. Даёт 2 энергии.",
  [ECard.Kaboom]: "Накладывает Пиро и наносит 1 пронзающий урон 1 врагу где угодно. Даёт 1 энергию.",
  [ECard.KaboomPlus]: "Накладывает Пиро и наносит 2 пронзающего урона 1 врагу где угодно. Вы можете потратить 2 энергии, чтобы удвоить этот урон.",
  [ECard.JumpyDumpty]: "Накладывает Пиро и наносит 1 урон 2 разным врагам в вашей зоне. Вы можете вернуть эту карту наверх колоды.",
  [ECard.JumpyDumptyPlus]: "Накладывает Пиро и наносит 1 урон 2 разным врагам в вашей зоне. Вы можете потратить 2 энергии, чтобы повторить этот эффект один раз.",
  [ECard.LightningTouch]: "Накладывает Электро и наносит 1 пронзающий урон 1 врагу где угодно. Вытяните 1 карту.",
  [ECard.LightningTouchPlus]: "Накладывает Электро и наносит 1 пронзающий урон 1 врагу где угодно. Вытяните 1 карту.",
  [ECard.VioletArc]: "Наносит 5 пронзающего урона всем врагам в вашей зоне, если на них есть Электро.",
  [ECard.VioletArcPlus]: "Наносит 5 пронзающего урона всем врагам в вашей зоне, если на них есть Электро.",
  [ECard.ForeignIronwind]: "Наносит 3 урона 1 врагу в вашей зоне.",
  [ECard.ForeignIronwindPlus]: "Накладывает Анемо и наносит 3 урона 1 врагу в вашей зоне. Даёт 2 энергии.",
  [ECard.PalmVortex]: "Наносит 2 урона всем врагам в вашей зоне с наложенными Гидро, Пиро, Крио или Электро.",
  [ECard.PalmVortexPlus]: "Наносит 4 урона всем врагам в вашей зоне с наложенными Гидро, Пиро, Крио или Электро.",
  [ECard.RippleOfFate]: "Накладывает Гидро и наносит 1 пронзающий урон 1 врагу где угодно. Вытягивает 1 карту.",
  [ECard.RippleOfFatePlus]: "Вытягивает 2 карты. Даёт 2 энергии за каждую карту Моны, вытянутую этим эффектом.",
  [ECard.MirrorReflections]: "Выбранный 1 враг, не босс, в вашей зоне не будет атаковать в этом ходу. В начале следующего хода накладывает Гидро и наносит 2 урона всем врагам в вашей зоне.",
  [ECard.MirrorReflectionsPlus]: "Выбранный 1 враг, не босс, в вашей зоне не будет атаковать в этом ходу. В начале следующего хода накладывает Гидро и наносит 2 урона всем врагам в вашей зоне.",
  [ECard.SparklingScatter]: "Накладывает Гео и наносит 1 пронзающий урон 1 врагу где угодно. Вытягивает 1 карту.",
  [ECard.SparklingScatterPlus]: "Накладывает Гео и наносит 2 пронзающего урона 2 разным врагам где угодно.",
  [ECard.JadeScreen]: "Даёт любому 1 игроку 3 Защиты.",
  [ECard.JadeScreenPlus]: "Даёт вам и 1 другому игроку 3 Защиты и 1 энергию.",
  [ECard.MaidsBladework]: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щитов. Вы можете потратить 1 Очко действия, чтобы моментально повторить этот эффект на этом же враге.",
  [ECard.MaidsBladeworkPlus]: "Вытягивает 3 карты. Даёт 2 Защиты.",
  [ECard.Breastplate]: "Накладывает Гео всем врагам в вашей зоне. Восстанавливает вам 1 ОЗ.",
  [ECard.BreastplatePlus]: "Накладывает Гео всем врагам в вашей зоне. На этом ходу ваши обычные атаки восстанавливают 1 ОЗ 1 любому игроку.",
  [ECard.AncientSwordArt]: "Наносит 2 урона 1 врагу в вашей зоне. Даёт 2 энергии, если на враге есть Крио.",
  [ECard.AncientSwordArtPlus]: "Наносит 2 урона 1 врагу в вашей зоне и даёт 2 энергии. Вместо этого наносит 5 урона, если на враге есть Крио.",
  [ECard.HeraldOfFrost]: "Накладывает Крио 1 врагу где угодно. На этом ходу следующий игрок, который атакует этого врага, восстановит 2 ОЗ.",
  [ECard.HeraldOfFrostPlus]: "Накладывает Крио 1 врагу где угодно. На этом ходу следующий игрок, который атакует этого врага, восстановит 3 ОЗ и получит 2 энергии.",
  [ECard.Origin]: "Наносит 2 урона 1 врагу в вашей зоне. Вы можете потратить 2 энергии, чтобы получить 1 Очко Действия.",
  [ECard.OriginPlus]: "Наносит 2 урона 1 врагу в вашей зоне. Наносит 5 урона, если the enemy has Electro applied. Даёт 2 энергии.",
  [ECard.BalefulOmen]: "Накладывает Электро всем врагам в вашей зоне. Размещает 🟣 на другом игроке (макс. 5). Когда игрок использует обычную атаку, он может потратить 🟣 чтобы нанести 1 пронзающий урона 1 врагу на своей зоне.",
  [ECard.BalefulOmenPlus]: "Накладывает Электро всем врагам в вашей зоне. Размещает 2 🟣 на вас и 1 на другом игроке (макс. 5). Когда игрок использует обычную атаку, он может потратить 🟣 чтобы нанести 1 пронзающий урона 1 врагу на своей зоне..",
  [ECard.SteelFang]: "Уничтожает 1 щит 1 врагу в вашей зоне. Вместо этого наносит 2 урона, если на враге нет щитов. Вы можете потратить 1 энергию, чтобы разместить 🟣 на взрыве Рейзора (макс. 3).",
  [ECard.SteelFangPlus]: "Уничтожает 1 щит 1 врагу в вашей зоне и наносит 2 урона этому врагу. Вы можете потратить 1 энергию, чтобы разместить 🟣 на взрыве Рейзора (макс. 3).",
  [ECard.ClawAndThunder]: "Накладывает Электро на всех врагов в вашей зоне. Размещает 🟣 на взрыве Рейзора (макс. 3), если он не был активирован на этом ходу.",
  [ECard.ClawAndThunderPlus]: "Накладывает Электро на всех врагов в вашей зоне. Размещает 🟣 на взрыве Рейзора (макс. 3), если он не был активирован на этом ходу. Вы можете удалить все 🟣 с взрыва Рейзора, чтобы получить 2 энергии за каждый удалённый 🟣.",
  [ECard.SpearOfTheChurch]: "Наносит 1 пронзающий урон 1 врагу в вашей зоне. Вы можете потратить 1 энергию, чтобы нанести 1 пронзающий урон 1 другому врагу где угодно.",
  [ECard.SpearOfTheChurchPlus]: "Накладывает Крио и наносит 3 урона 1 врагу в вашей зоне. Вы можете потратить 1 энергию, чтобы получить 1 Очко Действия.", 
  [ECard.RavagingConfession]: "Накладывает Крио на 1 врага в зоне любого игрока. Наносит 1 урон всем врагам в этой зоне.",
  [ECard.RavagingConfessionPlus]: "Накладывает Крио на 1 врага в зоне любого игрока. Наносит 3 урона всем врагам в этой зоне. Если это добивает врага, даёт 2 энергии.",
  [ECard.WindSpiritCreation]: "Накладывает Анемо и наносит 1 пронзающий урон 1 врагу где угодно. Даёт 1 энергию.",
  [ECard.WindSpiritCreationPlus]: "Накладывает Анемо и наносит 2 пронзающих урона 2 разным врагам где угодно.",
  [ECard.AnemoHypostatis]: "Накладывает Анемо на 1 врага где угодно. Вы можете перевернуть 1 другого врага где угодно лицом вниз, удалив все метки, которые на нём есть, и разместите этого врага сверху первого.",
  [ECard.AnemoHypostatisPlus]: "Накладывает Анемо на всех врагов вашей зоне. За любую реакцию, которую это вызовет, вы можете восстановить 3 ОЗ любому 1 игроку, вместо получения карты 'Рывок'.",
  [ECard.CuttingTorrent]: "Наносит 1 пронзающий урон 1 врагу где угодно. Вы можете потратить 1, чтобы наложить Гидро на этого врага.",
  [ECard.CuttingTorrentPlus]: "Наносит 1 пронзающий урон 1 врагу где угодно. Наносит 3 урона, если на враге есть Гидро.",
  [ECard.RagingTide]: "Вытягивает 3 карты. Вы можете сбросить до 3-х карт, чтобы нанести Гидро 1 врагу в вашей зоне за каждую сброшенную карту.",
  [ECard.RagingTidePlus]: "Вытягивает 3 карты. Вы можете сбросить до 3-х карт, чтобы нанести Гидро 1 врагу в вашей зоне за каждую сброшенную карту.",
  [ECard.DivineArchery]: "Наносит 1 пронзающего урона 1 врагу где угодно. Вы можете потратить 1, чтобы наложить Анемо на этого врага.",
  [ECard.DivineArcheryPlus]: "Наносит 1 пронзающий урон 1 врагу где угодно. Вы можете потратить 1 энергию, чтобы вместо этого нанести 3 пронзающего урона.",
  [ECard.SkywardSonnet]: "Накладывает Анемо на всех врагов в вашей зоне. На этом ходу ваша следующая обычная атака нанесёт +1 урон.",
  [ECard.SkywardSonnetPlus]: "Накладывает Анемо на всех врагов в вашей зоне и зоне любого игрока. На этом ходу ваша следующая обычная атака нанесёт +2 урона.",
  [ECard.DoughFu]: "Наносит 1 пронзающий урон 1 врагу в вашей зоне. Вы можете потратить 1 energy, чтобы нанести 1 пронзающий урон другому врагу где угодно.",
  [ECard.DoughFuPlus]: "Накладывает Пиро и наносит 2 пронзающего урона 1 врагу в вашей зоне. Вы можете потратить 1 энергию, чтобы получить 1 Очко Действия.",
  [ECard.GuobaFire]: "Накладывает Пиро и наносит 2 урона всем врагам в вашей зоне. В начале следующего хода накладывает Пиро и наносит 2 урона всем врагам в вашей зоне.",
  [ECard.GuobaFirePlus]: "Накладывает Пиро и наносит 2 урона всем врагам в вашей зоне. В начале следующего хода накладывает Пиро и наносит 2 урона всем врагам в вашей зоне.",
  [ECard.WhirlwindThrust]: "Наносит 1 пронзающий урон 1 врагу в вашей зоне. Вы можете потратить 1 энергию, чтобы нанести 1 пронзающий урон другому врагу где угодно.",
  [ECard.WhirlwindThrustPlus]: "Накладывает Анемо и наносит 2 пронзающего урона 1 врагу в вашей зоне. Вы можете потратить 1 энергию, чтобы получить 1 Очко Действия.",
  [ECard.LemniscaticWind]: "Накладывает Анемо и наносит 1 пронзающий урон 1 врагу в вашей зоне. Вы можете вернуть эту карту в в вашу руку после использования.",
  [ECard.LemniscaticWindPlus]: "Накладывает Анемо и наносит 2 пронзающего урона 1 врагу в вашей зоне. Если последняя сыгранная вами карта была 'Рывок', наносит 5 пронзающего урона.",
  [ECard.GuhuaStyle]: "Наносит 2 урона 1 врагу в вашей зоне. Даёт 2 энергии, если на враге есть Гидро.",
  [ECard.GuhuaStylePlus]: "Наносит 3 урона 1 врагу в вашей зоне. Наносит 5 урона, если на враге есть Гидро.",
  [ECard.FatalRainscreen]: "Даёт 4 защиты и накладывает Гидро на 1 врага в вашей зоне. Восстанавливает 2 ОЗ 1 любому игроку.",
  [ECard.FatalRainscreenPlus]: "Даёт 4 защиты и накладывает Гидро на 1 врага в вашей зоне. Восстанавливает 2 ОЗ 1 любому игроку.",
  [ECard.DanceOfFire]: "Уничтожает 1 щит 1 врагу в вашей зоне. Наносит 2 урона, если у врага нет щитов. Вы можете потратить 1 Очко действия, чтобы моментально повторить этот эффект на этом же враге.",
  [ECard.DanceOfFirePlus]: "Наносит 1 урон всем врагам в вашей зоне. Если у вас есть защита, наносит 3 урона.",
  [ECard.SweepingFervor]: "Даёт 3 защиты. Накладывает Пиро всем врагам в вашей зоне.",
  [ECard.SweepingFervorPlus]: "Даёт 3 защиты. Накладывает Пиро всем врагам в вашей зоне.",
  [ECard.SealOfApproval]: "Накладывает Пиро и наносит 1 пронзающий урон 1 врагу где угодно.",
  [ECard.SealOfApprovalPlus]: "Накладывает Пиро и наносит 2 пронзающего урона 1 врагу где угодно. Вытягивает 1 карту, есть на взрыве Янь Фэй есть 🔥. Вытягивает 2 карты, если 🔥 3 или больше.",
  [ECard.SignedEdict]: "Накладывает Пиро на 1 врага в вашей зоне и наносит 1 урон каждому врагу за каждый 🔥 на взрыве Янь Фэй.",
  [ECard.SignedEdictPlus]: "Накладывает Пиро на 1 врага в вашей зоне и наносит 1 урон каждому врагу за каждый 🔥 на взрыве Янь Фэй. Вы можете потратить 1 энергию, чтобы атаковать зону другого игрока.",
  [ECard.FireworkFlareUp]: "Наносит 2 урона 1 врагу где угодно. Эта карта стоит 0 Очков Действия, если на враге есть Пиро.",
  [ECard.FireworkFlareUpPlus]: "Накладывает Пиро и наносит 2 урона 3 разным врагам где угодно.",
  [ECard.NiwabiFireDance]: "На этом ходу ваша следующая обычная атака наложит Пиро.",
  [ECard.NiwabiFireDancePlus]: "На этом ходу ваша следующая обычная атака наложит Пиро. Вытягивает 3 карты.",
  [ECard.RainOfStone]: "Наносит 1 пронзающий урон 1 врагу в вашей зоне. Вы можете потратить 1 энергию, чтобы нанести 1 пронзающий урон 1 другому врагу где угодно.",
  [ECard.RainOfStonePlus]: "Накладывает Гео и наносит 2 пронзающего урона 1 врагу в вашей зоне. Вы можете потратить 1 энергию, чтобы получить 1 Очко Действия.",
  [ECard.DominusLapidis]: "Даёт 3 защиты вам и 1 другому игроку. Накладывает Гео всем врагам в вашей зоне. В начале следующего хода накладывает Гео всем врагам в вашей зоне.",
  [ECard.DominusLapidisPlus]: "Даёт 3 защиты вам и 1 другому игроку. Накладывает Гео всем врагам в вашей зоне. В начале следующего хода накладывает Гео всем врагам в вашей зоне.",
  [ECard.Dash]: "Сбросьте эту карту, затем возьмите 2 карты. Вы получаете 1 дополнительное Очко действия для использования в этот ход.",
  [ECard.Overheat]: "Сбросьте эту карту, затем возьмите 2 карты. Следующий нанесённый урон будет увеличен на 1. Если этот урон побеждает врага, получите 2 энергии.",
  [ECard.Burn]: "Получите 1 урон, когда вы берёте эту карту. Получите 2 урона, если это вторая или последующая карта Горение, которую вы взяли за этот ход. Сбросьте все карты «Горение» из руки, когда Гидро или Крио накладывается на врага в вашей зоне.",
  [ECard.Freeze]: "Пока эта карта у вас в руке, вы не можете получать или тратить энергию. Вы можете сбросить все карты Заморозка из руки, потратив 1 Очко действия.",
}
