export const engDescriptions: Record<string, string> = {
  ForeignRockblade: "Deal 3 damage to 1 enemy in your zone.",
  ForeignRockbladePlus: "Apply Geo and deal 3 damage to 1 enemy in your zone. Gain 2 energy.",
  StarfellSword: "Apply Geo and then deal 2 piercing damage to all enemies in your zone.",
  StarfellSwordPlus: "Apply Geo and then deal 2 piercing damage to all enemies in your zone.",
  WeissBladework: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Geo applied.",
  WeissBladeworkPlus: "Deal 3 damage to 1 enemy in your zone. If effect of the Abiogenesis: Solar Isotoma card was triggered This turn: gain 1 Action Point to spend to spend this turn and draw 1 card.",
  SolarIsotoma: "Apply Geo to all enemies in your zone. At the start next turn, apply Geo to all enemies in your zone. You may trash a card from you hand or discard to draw a card.",
  SolarIsotomaPlus: "Apply Geo to all enemies in your zone. At the start next turn, apply Geo to all enemies in your zone. You may trash a card from you hand or discard to draw a card.",
  Sharpshooter: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Pyro to that enemy.",
  SharpshooterPlus: "Deal 1 piercing damage to 1 enemy anywhere. Deal 3 damage instead if the enemy had no shields.",
  ExplosivePuppet: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Pyro and deal 2 damage to all enemies in your zone.",
  ExplosivePuppetPlus: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Pyro and deal 2 damage to all enemies in your zone.",
  WhisperOfWater: "Apply Hydro and deal 1 piercing damage to 1 enemy to anywhere. Draw 1 card.",
  WhisperOfWaterPlus: "Restore 2 HP to yourself and 1 other player.",
  LetTheShowBegin: "Apply Hydro to 1 enemy in your zone. Restore 1 HP to any 1 player. You may spend 2 energy to restore 3 HP instead.",
  LetTheShowBeginPlus: "Apply Hydro to all enemies in your zone. This Turn: your normal attacks will restore 1 HP to any 1 player.",
  Oceanborn: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  OceanbornPlus: "Deal 2 damage to all enemies in your zone. Deal 4 damage instead if you took damage last turn.",
  Tidecaller: "Apply Electro to all enemies in your zone. Gain 2 Guard.",
  TidecallerPlus: "Apply Electro to all enemies in your zone. Gain 3 Guard and add an Overheat card to your hand.",
  StrikeOfFortune: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Pyro applied.",
  StrikeOfFortunePlus: "Deal 3 damage to 1 enemy in your zone. If you have 7 or less HP, deal 1 additional damage and gain 3 energy.",
  PassionOverload: "Apply Pyro and deal 2 damage to 1 enemy in your zone. Discard the top card of your deck. If it was a Burn or Bennett card, take 1 damage and deal 1 damage to all enemies in your zone. Trash Burn cards discarded this way.",
  PassionOverloadPlus: "Apply Pyro and deal 4 damage to 1 enemy in your zone. Discard the top card of your deck. If it was a Burn or Bennett card, take 1 damage and deal 1 damage to all enemies in your zone. Trash Burn cards discarded this way.",
  Demonbane: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  DemonbanePlus: "Deal 2 damage to all enemies in your zone. 1 enemy with Cryo applied takes 4 damage instead.",
  LayeredFrost: "Draw 1 card. This turn: your normal attacks will apply Cryo to any enemies they target.",
  LayeredFrostPlus: "Draw 1 card. This turn: your normal attacks will apply Cryo to any enemies they target.",
  TemperedSword: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  TemperedSwordPlus: "Destroy all shields to 1 enemy in your zone. Deal 4 damage instead if the enemy has no shields.",
  SearingOnslaught: "Apply Pyro and deal 2 damage to 1 enemy in your zone. Immediately repeat this effect 2 more times.",
  SearingOnslaughtPlus: "Apply Pyro and deal 2 damage to 1 enemy in your zone. Immediately repeat this effect 2 more times.",
  KatzleinStyle: "Deal 2 piercing damage to 1 enemy anywhere.",
  KatzleinStylePlus: "Deal 2 piercing damage to 1 enemy anywhere. If you have any Guard, deal 5 piercing damage instead.",
  IcyPaws: "Either gain 3 Guard OR apply Cryo to all enemies in your zone. You may trash a Burn card in your discard.",
  IcyPawsPlus: "Apply Cryo to all enemies in your zone. Gain 3 Guard. You may trash a Burn cards in your discard.",
  EdelBladework: "Destroy 1 shield to 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 2 energy tp apply Cryo to this enemy.",
  EdelBladeworkPlus: "Apply Cryo and deal 2 damage to 1 enemy in your zone. Place a ❄ to Eula's Burst.",
  IcetideVortex: "Apply Cryo to 1 enemy in your zone. Either search your deck for a Eula card and add it to your hand or add all Eula cards from your discard into your hand.",
  IcetideVortexPlus: "Apply Cryo to 1 enemy in your zone. Either search your deck for a Eula card and add it to your hand or add all Eula cards from your discard into your hand.",
  BoltsOfDownfall: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Electro to this enemy.",
  BoltsOfDownfallPlus: "Deal 1 piercing damage to 1 enemy anywhere. If effect of the Nightrider card was triggered This turn: deal 3 piercing damage instead.",
  Nightrider: "Apply Electro and deal 1 piercing damage to 1 enemy in your zone. At the start next turn repeat this effect.",
  NightriderPlus: "Apply Electro and deal 2 piercing damage to 1 enemy anywhere. At the start next turn repeat this effect.",
  LiutianArchery: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Cryo to this enemy.",
  LiutianArcheryPlus: "Deal 2 damage to 1 enemy anywhere. You may spend 2 energy to apply Cryo to this enemy and triple the damage dealt.",
  TrailOfTheQilin: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Cryo and deal 2 damage to all enemies in your zone.",
  TrailOfTheQilinPlus: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Cryo and deal 2 damage to all enemies in your zone.",
  SpearOfWangsheng: "Deal 1 piercing damage to 1 enemy in your zone. If you had 7 or less HP, deal 2 piercing damage instead.",
  SpearOfWangshengPlus: "Take 1 damage. Deal 1 piercing damage to 1 enemy in your zone. If you had 7 or less HP, deal 4 piercing damage instead and shuffle this back into your deck.",
  GuideOfAfterlife: "Take 1 damage. Either gain 1 energy or draw 2 cards. This turn: your Normal Attacks will apply Pyro to any enemies they target.",
  GuideOfAfterlifePlus: "Take 1 damage. Either gain 1 energy or draw 2 cards. This turn: your Normal Attacks will apply Pyro to any enemies they target.",
  FavoniusBladework: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Anemo applied.",
  FavoniusBladeworkPlus: "Deal 2 damage to 1 enemy in your zone and gain 2 energy. Restore 2 HP to yourself.",
  GaleBlade: "Apply Anemo and deal 1 piercing damage to 1 enemy in your zone. You may swap this enemy with any other faceup enemy.",
  GaleBladePlus: "Apply Anemo and deal 1 piercing damage to 1 enemy in your zone. You may swap this enemy with any other faceup enemy.",
  CeremonialBladework: "Deal 3 damage to 1 enemy in your zone.",
  CeremonialBladeworkPlus: "Deal 2 plus 1d6 damage to 1 enemy in your zone.",
  Frostgnaw: "Apply Cryo to all enemies in your zone. Gain 1 energy.",
  FrostgnawPlus: "Apply Cryo to all enemies in your zone. Gain 2 energy. Restore 2 HP to yourself.",
  GaryuuBladework: "Deal 3 damage to 1 enemy in your zone.",
  GaryuuBladeworkPlus: "Deal 3 damage to 1 enemy in your zone. If the last card you played was Chihayaburu or Dash, deal 6 damage instead.",
  Chihayaburu: "Apply Anemo to 2 different enemies anywhere. You may swap these 2 enemies.",
  ChihayaburuPlus: "Apply Anemo to all enemies in your zone. Draw 2 cards.",
  YunlaiSwordsmanship: "Deal 3 damage to 1 enemy in your zone.",
  YunlaiSwordsmanshipPlus: "Apply Electro and deal 3 damage to 1 enemy in your zone. Gain 2 energy.",
  StellarRestoration: "Apply Electro to 1 enemy anywhere. You may flip 1 other enemy anywhere facedown, removing any tokens it had, and place this enemy on top of it.",
  StellarRestorationPlus: "Apply Electro to up to 3 different enemies anywhere/ Gain 2 energy.",
  Kaboom: "Apply Pyro and deal 1 piercing damage to 1 enemy anywhere. Gain 1 energy.",
  KaboomPlus: "Apply Pyro and deal 2 piercing damage to 1 enemy anywhere. You may spend 2 energy to double this damage.",
  JumpyDumpty: "Apply Pyro and deal 1 damage to up to 2 different enemies in your zone. You may return this card to top of your deck after playing it.",
  JumpyDumptyPlus: "Apply Pyro and deal 1 damage to up to 2 different enemies in your zone. You may spend 2 energy to immediately repeat this effect once.",
  LightningTouch: "Apply Electro and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  LightningTouchPlus: "Apply Electro and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  VioletArc: "Deal 5 piercing damage to all enemies in your zone with Electro applied.",
  VioletArcPlus: "Deal 5 piercing damage to all enemies in your zone with Electro applied.",
  ForeignIronwind: "Deal 3 damage to 1 enemy in your zone.",
  ForeignIronwindPlus: "Apply Anemo and deal 3 damage to 1 enemy in your zone. Gain 2 energy.",
  PalmVortex: "Deal 2 energy to all enemies in your zone with Hydro, Pyro, Cryo or Electro applied.",
  PalmVortexPlus: "Deal 4 energy to all enemies in your zone with Hydro, Pyro, Cryo or Electro applied.",
  RippleOfFate: "Apply Hydro and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  RippleOfFatePlus: "Draw 2 cards. Gain 2 energy for every Mona card you drew with this effect.",
  MirrorReflections: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Hydro and deal 2 damage to all enemies in your zone.",
  MirrorReflectionsPlus: "Target 1 non-boss enemy in your zone. It cannot attack this round. At the start of next turn apply Hydro and deal 2 damage to all enemies in your zone.",
  SparklingScatter: "Apply Geo and deal 1 piercing damage to 1 enemy anywhere. Draw 1 card.",
  SparklingScatterPlus: "Apply Geo and deal 2 piercing damage to 2 different enemies anywhere.",
  JadeScreen: "Give any 1 player 3 Guard.",
  JadeScreenPlus: "Give yourself and any 1 other player 3 Guard and 1 energy.",
  MaidsBladework: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  MaidsBladeworkPlus: "Draw 3 cards. Gain 2 Guard.",
  Breastplate: "Apply Geo to all enemies in your zone. Restore 1 HP to yourself.",
  BreastplatePlus: "Apply Geo to all enemies in your zone. This turn: your normal attacks will restore 1 HP to 1 any player.",
  AncientSwordArt: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Cryo applied.",
  AncientSwordArtPlus: "Deal 2 damage to 1 enemy in your zone and gain 2 energy. Deal 5 damage instead if the enemy has Cryo applied.",
  HeraldOfFrost: "Apply Cryo to 1 enemy anywhere. This turn: the next player to target this enemy restores 2 HP.",
  HeraldOfFrostPlus: "Apply Cryo to 1 enemy anywhere. This turn: the next player to target this enemy restores 3 HP and gains 2 energy.",
  Origin: "Deal 2 damage to 1 enemy in your zone. You may spend 2 energy to gain 1 Action Point to spend this turn.",
  OriginPlus: "Deal 2 damage to 1 enemy in your zone. Deal 5 damage instead if he enemy has Electro applied. Gain 2 energy.",
  BalefulOmen: "Apply Electro to all enemies in your zone. Place a 🟣 on another player's board (max 5). Any time played any Normal Attack card, a player may discard a 🟣 to deal 1 piercing damage to 1 enemy in their zone.",
  BalefulOmenPlus: "Apply Electro to all enemies in your zone. Place 2 🟣 on yours and 1 on another player's board (max 5). Any time played any Normal Attack card, a player may discard a 🟣 to deal 1 piercing damage to 1 enemy in their zone.",
  SteelFang: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if he enemy has no shields. You may spend 1 energy to place a 🟣 on Razor's Burst (max 3).",
  SteelFangPlus: "Destroy 1 shield on 1 enemy in your zone and deal 2 damage to that enemy. You may spend 1 energy to place a 🟣 on Razor's Burst (max 3).",
  ClawAndThunder: "Apply Electro to all enemies in our zone. Place a 🟣 on Razor's Burst (max 3) if it has not been activated yet this turn.",
  ClawAndThunderPlus: "Apply Electro to all enemies in your zone. Place a 🟣 on Razor's Burst (max 3) if it has not been activated yet this turn. You may remove all 🟣 from Razor's Burst to gain 2 energy for each 🟣 removed.",
  SpearOfTheChurch: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  SpearOfTheChurchPlus: "Apply Cryo and deal 3 damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  RavagingConfession: "Deal 1 piercing damage to 1 enemy anywhere. You may take the enemy you damaged and place in in your zone.",
  RavagingConfessionPlus: "Apply Cryo and deal 3 damage to 1 enemy anywhere. You may take the enemy you damaged and place in in your zone.",
  WindSpiritCreation: "Apply Anemo and deal 1 piercing damage to 1 enemy anywhere. Gain 1 energy.",
  WindSpiritCreationPlus: "Apply Anemo and deal 2 piercing damage to 2 different enemies anywhere.",
  AnemoHypostatis: "Apply Anemo to 1 enemy anywhere. You may flip 1 other enemy anywhere facedown, removing any tokens it had, and place this enemy on top of it.",
  AnemoHypostatisPlus: "Apply Anemo to all enemies in your zone. For any reactions this triggers, you may choose to restore 3 HP to to any 1 player instead of gaining a Dash card.",
  CuttingTorrent: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Hydro to that enemy.",
  CuttingTorrentPlus: "Deal 1 piercing damage to 1 enemy anywhere. Deal 3 damage instead if the enemy has Hydro applied.",
  RagingTide: "Draw 3 cards. You may discard up to 3 cards to apply Hydro to 1 enemy in your zone per card.",
  RagingTidePlus: "Draw 3 cards. You may discard up to 3 cards to apply Hydro to 1 enemy in your zone per card.",
  DivineArchery: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to apply Anemo to that enemy.",
  DivineArcheryPlus: "Deal 1 piercing damage to 1 enemy anywhere. You may spend 1 energy to deal 3 piercing damage instead.",
  SkywardSonnet: "Apply Anemo to all enemies in your zone. This turn: your next Normal attack has any damage dealt increased by 1.",
  SkywardSonnetPlus: "Apply Anemo to all enemies in your zone and any one player's zone. This turn: your next Normal attack has any damage dealt increased by 2.",
  DoughFu: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to deal 1 piercing damage to a different enemy anywhere.",
  DoughFuPlus: "Apply Pyro and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 action point.",
  GuobaFire: "Apply Pyro and deal 2 damage to all enemies in your zone. At the start next turn, apply Pyro and deal 2 damage to all enemies in your zone.",
  GuobaFirePlus: "Apply Pyro and deal 2 damage to all enemies in your zone. At the start next turn, apply Pyro and deal 2 damage to all enemies in your zone.",
  WhirlwindThrust: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  WhirlwindThrustPlus: "Apply Anemo and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  LemniscaticWind: "Apply Anemo and deal 1 piercing damage to 1 enemy in your zone. You may return this card to your hand after playing it.",
  LemniscaticWindPlus: "Apply Anemo and deal 2 piercing damage to 1 enemy in your zone. if the last card you played was Dash, deal 5 piercing damage instead.",
  GuhuaStyle: "Deal 2 damage to 1 enemy in your zone. Gain 2 energy if the enemy has Hydro applied.",
  GuhuaStylePlus: "Deal 3 damage to 1 enemy in your zone. Deal 5 damage instead if the enemy has Hydro applied.",
  FatalRainscreen: "Gain 4 Guard and apply Hydro to 1 enemy in your zone. Restore 2 HP to 1 any player.",
  FatalRainscreenPlus: "Gain 4 Guard and apply Hydro to 1 enemy in your zone. Restore 2 HP to 1 any player.",
  DanceOfFire: "Destroy 1 shield on 1 enemy in your zone. Deal 2 damage instead if the enemy has no shields. You may spend 1 Action Point to immediately repeat this effect once on the same enemy.",
  DanceOfFirePlus: "Deal 1 damage to all enemies in your zone. If you have Guard, deal 3 damage instead.",
  SweepingFervor: "Gain 3 Guard. Apply Pyro to all enemies in your zone.",
  SweepingFervorPlus: "Gain 3 Guard. Apply Pyro to all enemies in your zone.",
  SealOfApproval: "Apply Pyro and deal 1 piercing damage to 1 enemy anywhere.",
  SealOfApprovalPlus: "Apply Pyro and deal 2 piercing damage to 1 enemy anywhere. Draw 1 card, if there are any 🔥 on Yanfei's Burst. Draw 2 cards instead if there are 3+ 🔥.",
  SignedEdict: "Apply Pyro to 1 enemy in your zone and deal 1 damage to each enemy for each 🔥 on Yanfei's Burst.",
  SignedEdictPlus: "Apply Pyro to 1 enemy in your zone and deal 1 damage to each enemy for each 🔥 on Yanfei's Burst. You may spend 1 energy to target another player's zone instead.",
  FireworkFlareUp: "Deal 2 damage to 1 enemy anywhere. This card costs 0 Action Points if th enemy has Pyro applied.",
  FireworkFlareUpPlus: "Apply Pyro and deal 2 damage to 3 different enemies anywhere.",
  NiwabiFireDance: "This turn: Your next normal attack will apply Pyro to any enemies they target.",
  NiwabiFireDancePlus: "This turn: Your next normal attack will apply Pyro to any enemies they target. Draw 3 cards.",
  RainOfStone: "Deal 1 piercing damage to 1 enemy in your zone. You may spend 1 energy to deal 1 piercing damage to a different enemy anywhere.",
  RainOfStonePlus: "Apply Geo and deal 2 piercing damage to 1 enemy in your zone. You may spend 1 energy to gain 1 Action Point to spend this turn.",
  DominusLapidis: "Give 3 Guard to yourself and 1 other player. Apply Geo to all enemies in your zone. At the start of next turn, apply Geo to all enemies in your zone.",
  DominusLapidisPlus: "Give 3 Guard to yourself and 1 other player. Apply Geo to all enemies in your zone. At the start of next turn, apply Geo to all enemies in your zone.",
};

export const rusDescriptions:Record<string, string>={}
