import { ECard } from "../../types/enums";

export const engCards: Record<ECard, string> = {
  [ECard.ForeignRockblade]: "Foreign Rockblade",
  [ECard.ForeignRockbladePlus]: "Foreign Rockblade+",
  [ECard.StarfellSword]: "Starfell Sword",
  [ECard.StarfellSwordPlus]: "Starfell Sword+",
  [ECard.WeissBladework]: "Weiss Bladework",
  [ECard.WeissBladeworkPlus]: "Weiss Bladework+",
  [ECard.SolarIsotoma]: "Solar Isotoma",
  [ECard.SolarIsotomaPlus]: "Solar Isotoma+",
  [ECard.Sharpshooter]: "Sharpshooter",
  [ECard.SharpshooterPlus]: "Sharpshooter+",
  [ECard.ExplosivePuppet]: "Explosive Puppet",
  [ECard.ExplosivePuppetPlus]: "Explosive Puppet+",
  [ECard.WhisperOfWater]: "Whisper Of Water",
  [ECard.WhisperOfWaterPlus]: "Whisper Of Water+",
  [ECard.LetTheShowBegin]: "Let The Show Begin",
  [ECard.LetTheShowBeginPlus]: "Let The Show Begin+",
  [ECard.Oceanborn]: "Oceanborn",
  [ECard.OceanbornPlus]: "Oceanborn+",
  [ECard.Tidecaller]: "Tidecaller",
  [ECard.TidecallerPlus]: "Tidecaller+",
  [ECard.StrikeOfFortune]: "Strike Of Fortune",
  [ECard.StrikeOfFortunePlus]: "Strike Of Fortune+",
  [ECard.PassionOverload]: "Passion Overload",
  [ECard.PassionOverloadPlus]: "Passion Overload+",
  [ECard.Demonbane]: "Demonbane",
  [ECard.DemonbanePlus]: "Demonbane+",
  [ECard.LayeredFrost]: "Layered Frost",
  [ECard.LayeredFrostPlus]: "Layered Frost+",
  [ECard.TemperedSword]: "Tempered Sword",
  [ECard.TemperedSwordPlus]: "Tempered Sword+",
  [ECard.SearingOnslaught]: "Searing Onslaught",
  [ECard.SearingOnslaughtPlus]: "Searing Onslaught+",
  [ECard.KatzleinStyle]: "Katzlein Style",
  [ECard.KatzleinStylePlus]: "Katzlein Style+",
  [ECard.IcyPaws]: "Icy Paws",
  [ECard.IcyPawsPlus]: "Icy Paws+",
  [ECard.EdelBladework]: "Edel Bladework",
  [ECard.EdelBladeworkPlus]: "Edel Bladework+",
  [ECard.IcetideVortex]: "Icetide Vortex",
  [ECard.IcetideVortexPlus]: "Icetide Vortex+",
  [ECard.BoltsOfDownfall]: "Bolts Of Downfall",
  [ECard.BoltsOfDownfallPlus]: "Bolts Of Downfall+",
  [ECard.Nightrider]: "Nightrider",
  [ECard.NightriderPlus]: "Nightrider+",
  [ECard.LiutianArchery]: "Liutian Archery",
  [ECard.LiutianArcheryPlus]: "Liutian Archery+",
  [ECard.TrailOfTheQilin]: "Trail Of The Qilin",
  [ECard.TrailOfTheQilinPlus]: "Trail Of The Qilin+",
  [ECard.SpearOfWangsheng]: "Spear Of Wangsheng",
  [ECard.SpearOfWangshengPlus]: "Spear Of Wangsheng+",
  [ECard.GuideOfAfterlife]: "Guide Of Afterlife",
  [ECard.GuideOfAfterlifePlus]: "Guide Of Afterlife+",
  [ECard.FavoniusBladework]: "Favonius Bladework",
  [ECard.FavoniusBladeworkPlus]: "Favonius Bladework+",
  [ECard.GaleBlade]: "Gale Blade",
  [ECard.GaleBladePlus]: "Gale Blade+",
  [ECard.CeremonialBladework]: "Ceremonial Bladework",
  [ECard.CeremonialBladeworkPlus]: "Ceremonial Bladework+",
  [ECard.Frostgnaw]: "Frostgnaw",
  [ECard.FrostgnawPlus]: "Frostgnaw+",
  [ECard.GaryuuBladework]: "Garyuu Bladework",
  [ECard.GaryuuBladeworkPlus]: "Garyuu Bladework+",
  [ECard.Chihayaburu]: "Chihayaburu",
  [ECard.ChihayaburuPlus]: "Chihayaburu+",
  [ECard.YunlaiSwordsmanship]: "Yunlai Swordsmanship",
  [ECard.YunlaiSwordsmanshipPlus]: "Yunlai Swordsmanship+",
  [ECard.StellarRestoration]: "Stellar Restoration",
  [ECard.StellarRestorationPlus]: "Stellar Restoration+",
  [ECard.Kaboom]: "Kaboom",
  [ECard.KaboomPlus]: "Kaboom+",
  [ECard.JumpyDumpty]: "Jumpy Dumpty",
  [ECard.JumpyDumptyPlus]: "Jumpy Dumpty+",
  [ECard.LightningTouch]: "Lightning Touch",
  [ECard.LightningTouchPlus]: "Lightning Touch+",
  [ECard.VioletArc]: "Violet Arc",
  [ECard.VioletArcPlus]: "Violet Arc+",
  [ECard.ForeignIronwind]: "Foreign Ironwind",
  [ECard.ForeignIronwindPlus]: "Foreign Ironwind+",
  [ECard.PalmVortex]: "Palm Vortex",
  [ECard.PalmVortexPlus]: "Palm Vortex+",
  [ECard.RippleOfFate]: "Ripple Of Fate",
  [ECard.RippleOfFatePlus]: "Ripple Of Fate+",
  [ECard.MirrorReflections]: "Mirror Reflections",
  [ECard.MirrorReflectionsPlus]: "Mirror Reflections+",
  [ECard.SparklingScatter]: "Sparkling Scatter",
  [ECard.SparklingScatterPlus]: "Sparkling Scatter+",
  [ECard.JadeScreen]: "Jade Screen",
  [ECard.JadeScreenPlus]: "Jade Screen+",
  [ECard.MaidsBladework]: "Maids Bladework",
  [ECard.MaidsBladeworkPlus]: "Maids Bladework+",
  [ECard.Breastplate]: "Breastplate",
  [ECard.BreastplatePlus]: "Breastplate+",
  [ECard.AncientSwordArt]: "Ancient Sword Art",
  [ECard.AncientSwordArtPlus]: "Ancient Sword Art+",
  [ECard.HeraldOfFrost]: "HeraldOfFrost",
  [ECard.HeraldOfFrostPlus]: "Herald Of Frost+",
  [ECard.Origin]: "Origin",
  [ECard.OriginPlus]: "Origin+",
  [ECard.BalefulOmen]: "Baleful Omen",
  [ECard.BalefulOmenPlus]: "Baleful Omen+",
  [ECard.SteelFang]: "Steel Fang",
  [ECard.SteelFangPlus]: "Steel Fang+",
  [ECard.ClawAndThunder]: "Claw And Thunder",
  [ECard.ClawAndThunderPlus]: "Claw And Thunder+",
  [ECard.SpearOfTheChurch]: "Spear Of The Church",
  [ECard.SpearOfTheChurchPlus]: "Spear Of The Church+",
  [ECard.RavagingConfession]: "Ravaging Confession",
  [ECard.RavagingConfessionPlus]: "Ravaging Confession+",
  [ECard.WindSpiritCreation]: "Wind Spirit Creation",
  [ECard.WindSpiritCreationPlus]: "Wind Spirit Creation+",
  [ECard.AnemoHypostatis]: "Anemo Hypostatis",
  [ECard.AnemoHypostatisPlus]: "Anemo Hypostatis+",
  [ECard.CuttingTorrent]: "Cutting Torrent",
  [ECard.CuttingTorrentPlus]: "Cutting Torrent+",
  [ECard.RagingTide]: "Raging Tide",
  [ECard.RagingTidePlus]: "Raging Tide+",
  [ECard.DivineArchery]: "Divine Archery",
  [ECard.DivineArcheryPlus]: "Divine Archery+",
  [ECard.SkywardSonnet]: "Skyward Sonnet",
  [ECard.SkywardSonnetPlus]: "Skyward Sonnet+",
  [ECard.DoughFu]: "Dough Fu",
  [ECard.DoughFuPlus]: "Dough Fu+",
  [ECard.GuobaFire]: "Guoba Fire",
  [ECard.GuobaFirePlus]: "Guoba Fire+",
  [ECard.WhirlwindThrust]: "Whirlwind Thrust",
  [ECard.WhirlwindThrustPlus]: "Whirlwind Thrust+",
  [ECard.LemniscaticWind]: "Lemniscatic Wind",
  [ECard.LemniscaticWindPlus]: "Lemniscatic Wind+",
  [ECard.GuhuaStyle]: "Guhua Style",
  [ECard.GuhuaStylePlus]: "Guhua Style+",
  [ECard.FatalRainscreen]: "Fatal Rainscreen",
  [ECard.FatalRainscreenPlus]: "Fatal Rainscreen+",
  [ECard.DanceOfFire]: "Dance Of Fire",
  [ECard.DanceOfFirePlus]: "Dance Of Fire+",
  [ECard.SweepingFervor]: "Sweeping Fervor",
  [ECard.SweepingFervorPlus]: "Sweeping Fervor+",
  [ECard.SealOfApproval]: "Seal Of Approval",
  [ECard.SealOfApprovalPlus]: "Seal Of Approval+",
  [ECard.SignedEdict]: "Signed Edict",
  [ECard.SignedEdictPlus]: "Signed Edict+",
  [ECard.FireworkFlareUp]: "Firework Flare Up",
  [ECard.FireworkFlareUpPlus]: "Firework Flare Up+",
  [ECard.NiwabiFireDance]: "Niwabi Fire Dance",
  [ECard.NiwabiFireDancePlus]: "Niwabi Fire Dance+",
  [ECard.RainOfStone]: "Rain Of Stone",
  [ECard.RainOfStonePlus]: "Rain Of Stone+",
  [ECard.DominusLapidis]: "Dominus Lapidis",
  [ECard.DominusLapidisPlus]: "Dominus Lapidis+",
  [ECard.Dash]: "Dash",
  [ECard.Overheat]: "Overheat",
  [ECard.Burn]: "Burn",
  [ECard.Freeze]: "Freeze",
};

export const rusCards: Record<ECard, string> = {
  [ECard.ForeignRockblade]: "Каменный меч иноземца",
  [ECard.ForeignRockbladePlus]: "Каменный меч иноземца+",
  [ECard.StarfellSword]: "Меч звездопада",
  [ECard.StarfellSwordPlus]: "Меч звездопада+",
  [ECard.WeissBladework]: "Фехтовальный стиль Фавония: Мел",
  [ECard.WeissBladeworkPlus]: "Фехтовальный стиль Фавония: Мел+",
  [ECard.SolarIsotoma]: "Цветок солнца",
  [ECard.SolarIsotomaPlus]: "Цветок солнца+",
  [ECard.Sharpshooter]: "Первоклассный стрелок",
  [ECard.SharpshooterPlus]: "Первоклассный стрелок+",
  [ECard.ExplosivePuppet]: "Барон Зайчик",
  [ECard.ExplosivePuppetPlus]: "Барон Зайчик+",
  [ECard.WhisperOfWater]: "Шёпот воды",
  [ECard.WhisperOfWaterPlus]: "Шёпот воды+",
  [ECard.LetTheShowBegin]: "Да начнётся шоу",
  [ECard.LetTheShowBeginPlus]: "Да начнётся шоу+",
  [ECard.Oceanborn]: "По волнам",
  [ECard.OceanbornPlus]: "По волнам+",
  [ECard.Tidecaller]: "Призыв волны",
  [ECard.TidecallerPlus]: "Призыв волны+",
  [ECard.StrikeOfFortune]: "Счастливый меч",
  [ECard.StrikeOfFortunePlus]: "Счастливый меч+",
  [ECard.PassionOverload]: "Чрезмерные стремления",
  [ECard.PassionOverloadPlus]: "Чрезмерные стремления+",
  [ECard.Demonbane]: "Искоренение зла",
  [ECard.DemonbanePlus]: "Искоренение зла+",
  [ECard.LayeredFrost]: "Духовное лезвие: Холод Чунхуа",
  [ECard.LayeredFrostPlus]: "Духовное лезвие: Холод Чунхуа+",
  [ECard.TemperedSword]: "Закалённый меч",
  [ECard.TemperedSwordPlus]: "Закалённый меч+",
  [ECard.SearingOnslaught]: "Огненный натиск",
  [ECard.SearingOnslaughtPlus]: "Огненный натиск+",
  [ECard.KatzleinStyle]: "Стиль котёнка",
  [ECard.KatzleinStylePlus]: "Стиль котёнка+",
  [ECard.IcyPaws]: "Морозные коготочки",
  [ECard.IcyPawsPlus]: "Морозные коготочки+",
  [ECard.EdelBladework]: "Фехтовальный стиль Фавония: Знать",
  [ECard.EdelBladeworkPlus]: "Фехтовальный стиль Фавония: Знать+",
  [ECard.IcetideVortex]: "Ледяной прибой",
  [ECard.IcetideVortexPlus]: "Ледяной прибой+",
  [ECard.BoltsOfDownfall]: "Стрела возмездия",
  [ECard.BoltsOfDownfallPlus]: "Стрела возмездия+",
  [ECard.Nightrider]: "Тень расправленных крыльев",
  [ECard.NightriderPlus]: "Тень расправленных крыльев+",
  [ECard.LiutianArchery]: "Небесная стрела",
  [ECard.LiutianArcheryPlus]: "Небесная стрела+",
  [ECard.TrailOfTheQilin]: "След цилиня",
  [ECard.TrailOfTheQilinPlus]: "След цилиня+",
  [ECard.SpearOfWangsheng]: "Скрытое копьё Ваншэн",
  [ECard.SpearOfWangshengPlus]: "Скрытое копьё Ваншэн+",
  [ECard.GuideOfAfterlife]: "Путеводитель по загробной жизни",
  [ECard.GuideOfAfterlifePlus]: "Путеводитель по загробной жизни+",
  [ECard.FavoniusBladework]: "Фехтовальный стиль Фавония",
  [ECard.FavoniusBladeworkPlus]: "Фехтовальный стиль Фавония+",
  [ECard.GaleBlade]: "Клинок ветра",
  [ECard.GaleBladePlus]: "Клинок ветра+",
  [ECard.CeremonialBladework]: "Ритуальное фехтование",
  [ECard.CeremonialBladeworkPlus]: "Ритуальное фехтование+",
  [ECard.Frostgnaw]: "Выпад холода",
  [ECard.FrostgnawPlus]: "Выпад холода+",
  [ECard.GaryuuBladework]: "Фехтовальный стиль Гарю",
  [ECard.GaryuuBladeworkPlus]: "Фехтовальный стиль Гарю+",
  [ECard.Chihayaburu]: "Тихаяфуру",
  [ECard.ChihayaburuPlus]: "Тихаяфуру+",
  [ECard.YunlaiSwordsmanship]: "Грозовое фехтование",
  [ECard.YunlaiSwordsmanshipPlus]: "Грозовое фехтование+",
  [ECard.StellarRestoration]: "Возвращение звезды",
  [ECard.StellarRestorationPlus]: "Возвращение звезды+",
  [ECard.Kaboom]: "Бабах!",
  [ECard.KaboomPlus]: "Бабах!+",
  [ECard.JumpyDumpty]: "Прыг-скок бомба",
  [ECard.JumpyDumptyPlus]: "Прыг-скок бомба+",
  [ECard.LightningTouch]: "Касание молнии",
  [ECard.LightningTouchPlus]: "Касание молнии+",
  [ECard.VioletArc]: "Пурпурная дуга",
  [ECard.VioletArcPlus]: "Пурпурная дуга+",
  [ECard.ForeignIronwind]: "Железный ветер иноземца",
  [ECard.ForeignIronwindPlus]: "Железный ветер иноземца+",
  [ECard.PalmVortex]: "Ладонь вихря",
  [ECard.PalmVortexPlus]: "Ладонь вихря+",
  [ECard.RippleOfFate]: "Круги на воде",
  [ECard.RippleOfFatePlus]: "Круги на воде+",
  [ECard.MirrorReflections]: "Отражение фатума",
  [ECard.MirrorReflectionsPlus]: "Отражение фатума+",
  [ECard.SparklingScatter]: "Сверкающий дождь",
  [ECard.SparklingScatterPlus]: "Сверкающий дождь+",
  [ECard.JadeScreen]: "Нефритовая ширма",
  [ECard.JadeScreenPlus]: "Нефритовая ширма+",
  [ECard.MaidsBladework]: "Фехтовальный стиль Фавония: Горничная",
  [ECard.MaidsBladeworkPlus]: "Фехтовальный стиль Фавония: Горничная+",
  [ECard.Breastplate]: "Бронефартук",
  [ECard.BreastplatePlus]: "Бронефартук+",
  [ECard.AncientSwordArt]: "Облачный меч",
  [ECard.AncientSwordArtPlus]: "Облачный меч+",
  [ECard.HeraldOfFrost]: "Искусство Адепта: Вестник стужи",
  [ECard.HeraldOfFrostPlus]: "Искусство Адепта: Вестник стужи+",
  [ECard.Origin]: "Исток",
  [ECard.OriginPlus]: "Исток+",
  [ECard.BalefulOmen]: "Превосходство: Зловещее знамение",
  [ECard.BalefulOmenPlus]: "Превосходство: Зловещее знамение+",
  [ECard.SteelFang]: "Стальной клык",
  [ECard.SteelFangPlus]: "Стальной клык+",
  [ECard.ClawAndThunder]: "Гром и когти",
  [ECard.ClawAndThunderPlus]: "Гром и когти+",
  [ECard.SpearOfTheChurch]: "Копьё церкви",
  [ECard.SpearOfTheChurchPlus]: "Копьё церкви+",
  [ECard.RavagingConfession]: "Казнящая исповедь",
  [ECard.RavagingConfessionPlus]: "Казнящая исповедь+",
  [ECard.WindSpiritCreation]: "Базовая эссенция ветра",
  [ECard.WindSpiritCreationPlus]: "Базовая эссенция ветра+",
  [ECard.AnemoHypostatis]: "Анемо гипостазис",
  [ECard.AnemoHypostatisPlus]: "Анемо гипостазис+",
  [ECard.CuttingTorrent]: "Дождь расставаний",
  [ECard.CuttingTorrentPlus]: "Дождь расставаний+",
  [ECard.RagingTide]: "Бушующие волны",
  [ECard.RagingTidePlus]: "Бушующие волны+",
  [ECard.DivineArchery]: "Божественная точность",
  [ECard.DivineArcheryPlus]: "Божественная точность+",
  [ECard.SkywardSonnet]: "Небесная поэзия",
  [ECard.SkywardSonnetPlus]: "Небесная поэзия+",
  [ECard.DoughFu]: "Кунг-Тесто",
  [ECard.DoughFuPlus]: "Кунг-Тесто+",
  [ECard.GuobaFire]: "Атака Гобы",
  [ECard.GuobaFirePlus]: "Атака Гобы+",
  [ECard.WhirlwindThrust]: "Вихревой удар",
  [ECard.WhirlwindThrustPlus]: "Вихревой удар+",
  [ECard.LemniscaticWind]: "Лемниската ветра",
  [ECard.LemniscaticWindPlus]: "Лемниската ветра+",
  [ECard.GuhuaStyle]: "Стиль Гухуа",
  [ECard.GuhuaStylePlus]: "Стиль Гухуа+",
  [ECard.FatalRainscreen]: "Завеса дождя",
  [ECard.FatalRainscreenPlus]: "Завеса дождя+",
  [ECard.DanceOfFire]: "Зажигательный танец",
  [ECard.DanceOfFirePlus]: "Зажигательный танец+",
  [ECard.SweepingFervor]: "Решительный жар",
  [ECard.SweepingFervorPlus]: "Решительный жар+",
  [ECard.SealOfApproval]: "Печать одобрения",
  [ECard.SealOfApprovalPlus]: "Печать одобрения+",
  [ECard.SignedEdict]: "Подписанный указ",
  [ECard.SignedEdictPlus]: "Подписанный указ+",
  [ECard.FireworkFlareUp]: "Вспышка фейерверка",
  [ECard.FireworkFlareUpPlus]: "Вспышка фейерверка+",
  [ECard.NiwabiFireDance]: "Огненный танец Ниваби",
  [ECard.NiwabiFireDancePlus]: "Огненный танец Ниваби+",
  [ECard.RainOfStone]: "Каменный дождь",
  [ECard.RainOfStonePlus]: "Каменный дождь+",
  [ECard.DominusLapidis]: "Власть над камнем",
  [ECard.DominusLapidisPlus]: "Власть над камнем+",
  [ECard.Dash]: "Рывок",
  [ECard.Overheat]: "Перегрузка",
  [ECard.Burn]: "Горение",
  [ECard.Freeze]: "Заморозка",
};
