export const engCards: Record<string, string> = {
  ForeignRockblade: "Foreign Rockblade",
  ForeignRockbladePlus: "Foreign Rockblade+",
  StarfellSword: "Starfell Sword",
  StarfellSwordPlus: "Starfell Sword+",
  WeissBladework: "Weiss Bladework",
  WeissBladeworkPlus: "Weiss Bladework+",
  SolarIsotoma: "Solar Isotoma",
  SolarIsotomaPlus: "Solar Isotoma+",
  Sharpshooter: "Sharpshooter",
  SharpshooterPlus: "Sharpshooter+",
  ExplosivePuppet: "Explosive Puppet",
  ExplosivePuppetPlus: "Explosive Puppet+",
  WhisperOfWater: "Whisper Of Water",
  WhisperOfWaterPlus: "Whisper Of Water+",
  LetTheShowBegin: "Let The Show Begin",
  LetTheShowBeginPlus: "Let The Show Begin+",
  Oceanborn: "Oceanborn",
  OceanbornPlus: "Oceanborn+",
  Tidecaller: "Tidecaller",
  TidecallerPlus: "Tidecaller+",
  StrikeOfFortune: "Strike Of Fortune",
  StrikeOfFortunePlus: "Strike Of Fortune+",
  PassionOverload: "Passion Overload",
  PassionOverloadPlus: "Passion Overload+",
  Demonbane: "Demonbane",
  DemonbanePlus: "Demonbane+",
  LayeredFrost: "Layered Frost",
  LayeredFrostPlus: "Layered Frost+",
  TemperedSword: "Tempered Sword",
  TemperedSwordPlus: "Tempered Sword+",
  SearingOnslaught: "Searing Onslaught",
  SearingOnslaughtPlus: "Searing Onslaught+",
  KatzleinStyle: "Katzlein Style",
  KatzleinStylePlus: "Katzlein Style+",
  IcyPaws: "Icy Paws",
  IcyPawsPlus: "Icy Paws+",
  EdelBladework: "Edel Bladework",
  EdelBladeworkPlus: "Edel Bladework+",
  IcetideVortex: "Icetide Vortex",
  IcetideVortexPlus: "Icetide Vortex+",
  BoltsOfDownfall: "Bolts Of Downfall",
  BoltsOfDownfallPlus: "Bolts Of Downfall+",
  Nightrider: "Nightrider",
  NightriderPlus: "Nightrider+",
  LiutianArchery: "Liutian Archery",
  LiutianArcheryPlus: "Liutian Archery+",
  TrailOfTheQilin: "Trail Of The Qilin",
  TrailOfTheQilinPlus: "Trail Of The Qilin+",
  SpearOfWangsheng: "Spear Of Wangsheng",
  SpearOfWangshengPlus: "Spear Of Wangsheng+",
  GuideOfAfterlife: "Guide Of Afterlife",
  GuideOfAfterlifePlus: "Guide Of Afterlife+",
  FavoniusBladework: "Favonius Bladework",
  FavoniusBladeworkPlus: "Favonius Bladework+",
  GaleBlade: "Gale Blade",
  GaleBladePlus: "Gale Blade+",
  CeremonialBladework: "Ceremonial Bladework",
  CeremonialBladeworkPlus: "Ceremonial Bladework+",
  Frostgnaw: "Frostgnaw",
  FrostgnawPlus: "Frostgnaw+",
  GaryuuBladework: "Garyuu Bladework",
  GaryuuBladeworkPlus: "Garyuu Bladework+",
  Chihayaburu: "Chihayaburu",
  ChihayaburuPlus: "Chihayaburu+",
  YunlaiSwordsmanship: "Yunlai Swordsmanship",
  YunlaiSwordsmanshipPlus: "Yunlai Swordsmanship+",
  StellarRestoration: "Stellar Restoration",
  StellarRestorationPlus: "Stellar Restoration+",
  Kaboom: "Kaboom",
  KaboomPlus: "Kaboom+",
  JumpyDumpty: "Jumpy Dumpty",
  JumpyDumptyPlus: "Jumpy Dumpty+",
  LightningTouch: "Lightning Touch",
  LightningTouchPlus: "Lightning Touch+",
  VioletArc: "Violet Arc",
  VioletArcPlus: "Violet Arc+",
  ForeignIronwind: "Foreign Ironwind",
  ForeignIronwindPlus: "Foreign Ironwind+",
  PalmVortex: "Palm Vortex",
  PalmVortexPlus: "Palm Vortex+",
  RippleOfFate: "Ripple Of Fate",
  RippleOfFatePlus: "Ripple Of Fate+",
  MirrorReflections: "Mirror Reflections",
  MirrorReflectionsPlus: "Mirror Reflections+",
  SparklingScatter: "Sparkling Scatter",
  SparklingScatterPlus: "Sparkling Scatter+",
  JadeScreen: "Jade Screen",
  JadeScreenPlus: "Jade Screen+",
  MaidsBladework: "Maids Bladework",
  MaidsBladeworkPlus: "Maids Bladework+",
  Breastplate: "Breastplate",
  BreastplatePlus: "Breastplate+",
  AncientSwordArt: "Ancient Sword Art",
  AncientSwordArtPlus: "Ancient Sword Art+",
  HeraldOfFrost: "HeraldOfFrost",
  HeraldOfFrostPlus: "Herald Of Frost+",
  Origin: "Origin",
  OriginPlus: "Origin+",
  BalefulOmen: "Baleful Omen",
  BalefulOmenPlus: "Baleful Omen+",
  SteelFang: "Steel Fang",
  SteelFangPlus: "Steel Fang+",
  ClawAndThunder: "Claw And Thunder",
  ClawAndThunderPlus: "Claw And Thunder+",
  SpearOfTheChurch: "Spear Of The Church",
  SpearOfTheChurchPlus: "Spear Of The Church+",
  RavagingConfession: "Ravaging Confession",
  RavagingConfessionPlus: "Ravaging Confession+",
  WindSpiritCreation: "Wind Spirit Creation",
  WindSpiritCreationPlus: "Wind Spirit Creation+",
  AnemoHypostatis: "Anemo Hypostatis",
  AnemoHypostatisPlus: "Anemo Hypostatis+",
  CuttingTorrent: "Cutting Torrent",
  CuttingTorrentPlus: "Cutting Torrent+",
  RagingTide: "Raging Tide",
  RagingTidePlus: "Raging Tide+",
  DivineArchery: "Divine Archery",
  DivineArcheryPlus: "Divine Archery+",
  SkywardSonnet: "Skyward Sonnet",
  SkywardSonnetPlus: "Skyward Sonnet+",
  DoughFu: "Dough Fu",
  DoughFuPlus: "Dough Fu+",
  GuobaFire: "Guoba Fire",
  GuobaFirePlus: "Guoba Fire+",
  WhirlwindThrust: "Whirlwind Thrust",
  WhirlwindThrustPlus: "Whirlwind Thrust+",
  LemniscaticWind: "Lemniscatic Wind",
  LemniscaticWindPlus: "Lemniscatic Wind+",
  GuhuaStyle: "Guhua Style",
  GuhuaStylePlus: "Guhua Style+",
  FatalRainscreen: "Fatal Rainscreen",
  FatalRainscreenPlus: "Fatal Rainscreen+",
  DanceOfFire: "Dance Of Fire",
  DanceOfFirePlus: "Dance Of Fire+",
  SweepingFervor: "Sweeping Fervor",
  SweepingFervorPlus: "Sweeping Fervor+",
  SealOfApproval: "Seal Of Approval",
  SealOfApprovalPlus: "Seal Of Approval+",
  SignedEdict: "Signed Edict",
  SignedEdictPlus: "Signed Edict+",
  FireworkFlareUp: "Firework Flare Up",
  FireworkFlareUpPlus: "Firework Flare Up+",
  NiwabiFireDance: "Niwabi Fire Dance",
  NiwabiFireDancePlus: "Niwabi Fire Dance+",
  RainOfStone: "Rain Of Stone",
  RainOfStonePlus: "Rain Of Stone+",
  DominusLapidis: "Dominus Lapidis",
  DominusLapidisPlus: "Dominus Lapidis+",
  Dash: "Dash",
  Overheat: "Overheat",
  Burn: "Burn",
  Freeze: "Freeze",
};

export const rusCards: Record<string, string> = {
  ForeignRockblade: "Каменный меч иноземца",
  ForeignRockbladePlus: "Каменный меч иноземца+",
  StarfellSword: "Меч звездопада",
  StarfellSwordPlus: "Меч звездопада+",
  WeissBladework: "Фехтовальный стиль Фавония: Мел",
  WeissBladeworkPlus: "Фехтовальный стиль Фавония: Мел+",
  SolarIsotoma: "Цветок солнца",
  SolarIsotomaPlus: "Цветок солнца+",
  Sharpshooter: "Первоклассный стрелок",
  SharpshooterPlus: "Первоклассный стрелок+",
  ExplosivePuppet: "Барон Зайчик",
  ExplosivePuppetPlus: "Барон Зайчик+",
  WhisperOfWater: "Шёпот воды",
  WhisperOfWaterPlus: "Шёпот воды+",
  LetTheShowBegin: "Да начнётся шоу",
  LetTheShowBeginPlus: "Да начнётся шоу+",
  Oceanborn: "По волнам",
  OceanbornPlus: "По волнам+",
  Tidecaller: "Призыв волны",
  TidecallerPlus: "Призыв волны+",
  StrikeOfFortune: "Счастливый меч",
  StrikeOfFortunePlus: "Счастливый меч+",
  PassionOverload: "Чрезмерные стремления",
  PassionOverloadPlus: "Чрезмерные стремления+",
  Demonbane: "Искоренение зла",
  DemonbanePlus: "Искоренение зла+",
  LayeredFrost: "Духовное лезвие: Холод Чунхуа",
  LayeredFrostPlus: "Духовное лезвие: Холод Чунхуа+",
  TemperedSword: "Закалённый меч",
  TemperedSwordPlus: "Закалённый меч+",
  SearingOnslaught: "Огненный натиск",
  SearingOnslaughtPlus: "Огненный натиск+",
  KatzleinStyle: "Стиль котёнка",
  KatzleinStylePlus: "Стиль котёнка+",
  IcyPaws: "Морозные коготочки",
  IcyPawsPlus: "Морозные коготочки+",
  EdelBladework: "Фехтовальный стиль Фавония: Знать",
  EdelBladeworkPlus: "Фехтовальный стиль Фавония: Знать+",
  IcetideVortex: "Ледяной прибой",
  IcetideVortexPlus: "Ледяной прибой+",
  BoltsOfDownfall: "Стрела возмездия",
  BoltsOfDownfallPlus: "Стрела возмездия+",
  Nightrider: "Тень расправленных крыльев",
  NightriderPlus: "Тень расправленных крыльев+",
  LiutianArchery: "Небесная стрела",
  LiutianArcheryPlus: "Небесная стрела+",
  TrailOfTheQilin: "След цилиня",
  TrailOfTheQilinPlus: "След цилиня+",
  SpearOfWangsheng: "Скрытое копьё Ваншэн",
  SpearOfWangshengPlus: "Скрытое копьё Ваншэн+",
  GuideOfAfterlife: "Путеводитель по загробной жизни",
  GuideOfAfterlifePlus: "Путеводитель по загробной жизни+",
  FavoniusBladework: "Фехтовальный стиль Фавония",
  FavoniusBladeworkPlus: "Фехтовальный стиль Фавония+",
  GaleBlade: "Клинок ветра",
  GaleBladePlus: "Клинок ветра+",
  CeremonialBladework: "Ритуальное фехтование",
  CeremonialBladeworkPlus: "Ритуальное фехтование+",
  Frostgnaw: "Выпад холода",
  FrostgnawPlus: "Выпад холода+",
  GaryuuBladework: "Фехтовальный стиль Гарю",
  GaryuuBladeworkPlus: "Фехтовальный стиль Гарю+",
  Chihayaburu: "Тихаяфуру",
  ChihayaburuPlus: "Тихаяфуру+",
  YunlaiSwordsmanship: "Грозовое фехтование",
  YunlaiSwordsmanshipPlus: "Грозовое фехтование+",
  StellarRestoration: "Возвращение звезды",
  StellarRestorationPlus: "Возвращение звезды+",
  Kaboom: "Бабах!",
  KaboomPlus: "Бабах!+",
  JumpyDumpty: "Прыг-скок бомба",
  JumpyDumptyPlus: "Прыг-скок бомба+",
  LightningTouch: "Касание молнии",
  LightningTouchPlus: "Касание молнии+",
  VioletArc: "Пурпурная дуга",
  VioletArcPlus: "Пурпурная дуга+",
  ForeignIronwind: "Железный ветер иноземца",
  ForeignIronwindPlus: "Железный ветер иноземца+",
  PalmVortex: "Ладонь вихря",
  PalmVortexPlus: "Ладонь вихря+",
  RippleOfFate: "Круги на воде",
  RippleOfFatePlus: "Круги на воде+",
  MirrorReflections: "Отражение фатума",
  MirrorReflectionsPlus: "Отражение фатума+",
  SparklingScatter: "Сверкающий дождь",
  SparklingScatterPlus: "Сверкающий дождь+",
  JadeScreen: "Нефритовая ширма",
  JadeScreenPlus: "Нефритовая ширма+",
  MaidsBladework: "Фехтовальный стиль Фавония: Горничная",
  MaidsBladeworkPlus: "Фехтовальный стиль Фавония: Горничная+",
  Breastplate: "Бронефартук",
  BreastplatePlus: "Бронефартук+",
  AncientSwordArt: "Облачный меч",
  AncientSwordArtPlus: "Облачный меч+",
  HeraldOfFrost: "Искусство Адепта: Вестник стужи",
  HeraldOfFrostPlus: "Искусство Адепта: Вестник стужи+",
  Origin: "Исток",
  OriginPlus: "Исток+",
  BalefulOmen: "Превосходство: Зловещее знамение",
  BalefulOmenPlus: "Превосходство: Зловещее знамение+",
  SteelFang: "Стальной клык",
  SteelFangPlus: "Стальной клык+",
  ClawAndThunder: "Гром и когти",
  ClawAndThunderPlus: "Гром и когти+",
  SpearOfTheChurch: "Копьё церкви",
  SpearOfTheChurchPlus: "Копьё церкви+",
  RavagingConfession: "Казнящая исповедь",
  RavagingConfessionPlus: "Казнящая исповедь+",
  WindSpiritCreation: "Базовая эссенция ветра",
  WindSpiritCreationPlus: "Базовая эссенция ветра+",
  AnemoHypostatis: "Анемо гипостазис",
  AnemoHypostatisPlus: "Анемо гипостазис+",
  CuttingTorrent: "Дождь расставаний",
  CuttingTorrentPlus: "Дождь расставаний+",
  RagingTide: "Бушующие волны",
  RagingTidePlus: "Бушующие волны+",
  DivineArchery: "Божественная точность",
  DivineArcheryPlus: "Божественная точность+",
  SkywardSonnet: "Небесная поэзия",
  SkywardSonnetPlus: "Небесная поэзия+",
  DoughFu: "Кунг-Тесто",
  DoughFuPlus: "Кунг-Тесто+",
  GuobaFire: "Атака Гобы",
  GuobaFirePlus: "Атака Гобы+",
  WhirlwindThrust: "Вихревой удар",
  WhirlwindThrustPlus: "Вихревой удар+",
  LemniscaticWind: "Лемниската ветра",
  LemniscaticWindPlus: "Лемниската ветра+",
  GuhuaStyle: "Стиль Гухуа",
  GuhuaStylePlus: "Стиль Гухуа+",
  FatalRainscreen: "Завеса дождя",
  FatalRainscreenPlus: "Завеса дождя+",
  DanceOfFire: "Зажигательный танец",
  DanceOfFirePlus: "Зажигательный танец+",
  SweepingFervor: "Решительный жар",
  SweepingFervorPlus: "Решительный жар+",
  SealOfApproval: "Печать одобрения",
  SealOfApprovalPlus: "Печать одобрения+",
  SignedEdict: "Подписанный указ",
  SignedEdictPlus: "Подписанный указ+",
  FireworkFlareUp: "Вспышка фейерверка",
  FireworkFlareUpPlus: "Вспышка фейерверка+",
  NiwabiFireDance: "Огненный танец Ниваби",
  NiwabiFireDancePlus: "Огненный танец Ниваби+",
  RainOfStone: "Каменный дождь",
  RainOfStonePlus: "Каменный дождь+",
  DominusLapidis: "Власть над камнем",
  DominusLapidisPlus: "Власть над камнем+",
  Dash: "Рывок",
  Overheat: "Перегрузка",
  Burn: "Горение",
  Freeze: "Заморозка",
};
